#SPI power signals
set_property IOSTANDARD LVCMOS33 [get_ports cs_c*]
set_property PACKAGE_PIN D19 [get_ports cs_c0_0]
set_property PACKAGE_PIN B15 [get_ports cs_c1_0]
set_property PACKAGE_PIN A16 [get_ports cs_c2_0]
set_property PACKAGE_PIN F20 [get_ports cs_c3_0]
set_property PACKAGE_PIN M17 [get_ports cs_c4_0]
set_property PACKAGE_PIN B21 [get_ports cs_c5_0]
set_property PACKAGE_PIN E22 [get_ports cs_c6_0]
set_property PACKAGE_PIN F18 [get_ports cs_c7_0]
set_property PACKAGE_PIN A19 [get_ports cs_c8_0]
set_property PACKAGE_PIN G20 [get_ports cs_c9_0]
set_property PACKAGE_PIN K21 [get_ports cs_c10_0]
set_property PACKAGE_PIN N22 [get_ports cs_c11_0]
set_property PACKAGE_PIN K19 [get_ports cs_c12_0]
set_property PACKAGE_PIN J19 [get_ports cs_c13_0]
set_property PACKAGE_PIN J21 [get_ports cs_c14_0]
set_property PACKAGE_PIN N20 [get_ports cs_c15_0]
set_property PACKAGE_PIN M18 [get_ports cs_c16_0]
set_property PACKAGE_PIN V14 [get_ports cs_c17_0]
set_property PACKAGE_PIN T14 [get_ports cs_c18_0]
set_property PACKAGE_PIN H14 [get_ports cs_c19_0]
set_property PACKAGE_PIN K14 [get_ports cs_c20_0]
set_property PACKAGE_PIN W17 [get_ports cs_c21_0]
set_property PACKAGE_PIN AB22 [get_ports cs_c22_0]
set_property PACKAGE_PIN AB20 [get_ports cs_c23_0]
set_property PACKAGE_PIN AB18 [get_ports cs_c24_0]
set_property PACKAGE_PIN V10 [get_ports cs_c25_0]
set_property PACKAGE_PIN AA10 [get_ports cs_c26_0]
set_property PACKAGE_PIN W21 [get_ports cs_c27_0]
set_property PACKAGE_PIN Y22 [get_ports cs_c28_0]
set_property PACKAGE_PIN Y19 [get_ports cs_c29_0]
set_property PACKAGE_PIN U22 [get_ports cs_c30_0]
set_property PACKAGE_PIN V19 [get_ports cs_c31_0]

set_property IOSTANDARD LVCMOS33 [get_ports sck_c_0]
set_property PACKAGE_PIN R19 [get_ports sck_c_0]
set_property PACKAGE_PIN R18 [get_ports miso_c_0]
set_property PACKAGE_PIN P19 [get_ports mosi_c_0]
#set_property DIRECTION IN [get_ports miso_c_0]
set_property IOSTANDARD LVCMOS33 [get_ports miso_c_0]
#set_property DIRECTION OUT [get_ports mosi_c_0]
set_property IOSTANDARD LVCMOS33 [get_ports mosi_c_0]

#SPI Monitor signals
set_property IOSTANDARD LVCMOS33 [get_ports cs_m*]
set_property PACKAGE_PIN E19 [get_ports cs_m0_0]
set_property PACKAGE_PIN F19 [get_ports cs_m1_0]
set_property PACKAGE_PIN A15 [get_ports cs_m2_0]
set_property PACKAGE_PIN D17 [get_ports cs_m3_0]
set_property PACKAGE_PIN J16 [get_ports cs_m4_0]
set_property PACKAGE_PIN A21 [get_ports cs_m5_0]
set_property PACKAGE_PIN D21 [get_ports cs_m6_0]
set_property PACKAGE_PIN G22 [get_ports cs_m7_0]
set_property PACKAGE_PIN A18 [get_ports cs_m8_0]
set_property PACKAGE_PIN A13 [get_ports cs_m9_0]
set_property PACKAGE_PIN J22 [get_ports cs_m10_0]
set_property PACKAGE_PIN M22 [get_ports cs_m11_0]
set_property PACKAGE_PIN H17 [get_ports cs_m12_0]
set_property PACKAGE_PIN L21 [get_ports cs_m13_0]
set_property PACKAGE_PIN J20 [get_ports cs_m14_0]
set_property PACKAGE_PIN C14 [get_ports cs_m15_0]
set_property PACKAGE_PIN N18 [get_ports cs_m16_0]
set_property PACKAGE_PIN W11 [get_ports cs_m17_0]
set_property PACKAGE_PIN T15 [get_ports cs_m18_0]
set_property PACKAGE_PIN V17 [get_ports cs_m19_0]
set_property PACKAGE_PIN K13 [get_ports cs_m20_0]
set_property PACKAGE_PIN F16 [get_ports cs_m21_0]
set_property PACKAGE_PIN AB21 [get_ports cs_m22_0]
set_property PACKAGE_PIN AA20 [get_ports cs_m23_0]
set_property PACKAGE_PIN AA18 [get_ports cs_m24_0]
set_property PACKAGE_PIN W22 [get_ports cs_m25_0]
set_property PACKAGE_PIN AA11 [get_ports cs_m26_0]
set_property PACKAGE_PIN N13 [get_ports cs_m27_0]
set_property PACKAGE_PIN Y21 [get_ports cs_m28_0]
set_property PACKAGE_PIN W19 [get_ports cs_m29_0]
set_property PACKAGE_PIN V22 [get_ports cs_m30_0]
set_property PACKAGE_PIN T18 [get_ports cs_m31_0]

set_property PACKAGE_PIN U18 [get_ports sck_m_0]
set_property PACKAGE_PIN U17 [get_ports mosi_m_0]
set_property PACKAGE_PIN P14 [get_ports miso_m_0]
#set_property DIRECTION OUT [get_ports sck_m_0]
set_property IOSTANDARD LVCMOS33 [get_ports sck_m_0]
#set_property DIRECTION IN [get_ports miso_m_0]
set_property IOSTANDARD LVCMOS33 [get_ports miso_m_0]
#set_property DIRECTION OUT [get_ports mosi_m_0]
set_property IOSTANDARD LVCMOS33 [get_ports mosi_m_0]

## Define Master clk in (system clock)
set_property PACKAGE_PIN R4 [get_ports CLK_IN1_D_0_clk_p]
set_property PACKAGE_PIN T4 [get_ports CLK_IN1_D_0_clk_n]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports CLK_IN1_D_0_clk_p]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports CLK_IN1_D_0_clk_n]

#Input clk_elink
#Get the clk_elink from the ethernet socket
#set_property PACKAGE_PIN W9 [get_ports clk_elink_clk_p]
#set_property PACKAGE_PIN Y9 [get_ports clk_elink_clk_n]
#set_property IOSTANDARD DIFF_SSTL15_R [get_ports clk_elink_clk_p]
#set_property IOSTANDARD DIFF_SSTL15_R [get_ports clk_elink_clk_n]

## Input rx_elink
#Get the rx_elink to the ethernet socket
set_property PACKAGE_PIN AA8 [get_ports rx_elink_p_0]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports rx_elink_p_0]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports rx_elink_n_0]


## Output tx_elink
#Get the tx_elink of the ethernet socket
set_property PACKAGE_PIN AB7 [get_ports {tx_elink_p_0[0]}]
set_property PACKAGE_PIN AB6 [get_ports {tx_elink_n_0[0]}]
set_property SLEW SLOW [get_ports {tx_elink_p_0[0]}]
set_property SLEW SLOW [get_ports {tx_elink_n_0[0]}]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports {tx_elink_p_0[0]}]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports {tx_elink_n_0[0]}]


## Define clk out
#Get the clock out of the ethernet socket
set_property PACKAGE_PIN W9 [get_ports clk_out_p_0]
set_property PACKAGE_PIN Y9 [get_ports clk_out_n_0]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports clk_out_p_0]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports clk_out_n_0]
#AUX2 P/N gives output a differential signal from the FPGA.
#AUX1 and AUX3 have a 100 Ohm termination resistor between the P and N lines as they were meant for differential input signals.
#set_property PACKAGE_PIN P16 [get_ports clk_out_p_0]
#set_property PACKAGE_PIN R17 [get_ports clk_out_n_0]
#set_property IOSTANDARD TMDS_33 [get_ports clk_out_p_0]
#set_property IOSTANDARD TMDS_33 [get_ports clk_out_n_0]

#set_property PACKAGE_PIN U19 [get_ports rx_fifo_full_rdy_0]
#Rx CAN signals
set_property IOSTANDARD LVCMOS33 [get_ports rx0_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx1_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx2_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx3_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx4_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx5_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx6_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx7_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx8_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx9_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx10_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx11_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx12_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx13_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx14_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx15_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx16_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx17_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx18_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx19_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx20_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx21_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx22_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx23_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx24_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx25_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx26_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx27_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx28_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx29_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx30_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx31_0]

set_property PACKAGE_PIN Y18 [get_ports rx31_0]
set_property PACKAGE_PIN U20 [get_ports rx30_0]
set_property PACKAGE_PIN AA9 [get_ports rx29_0]
set_property PACKAGE_PIN R14 [get_ports rx28_0]
set_property PACKAGE_PIN U21 [get_ports rx27_0]
set_property PACKAGE_PIN Y17 [get_ports rx26_0]
set_property PACKAGE_PIN AA19 [get_ports rx25_0]
set_property PACKAGE_PIN Y12 [get_ports rx24_0]
set_property PACKAGE_PIN L13 [get_ports rx23_0]
set_property PACKAGE_PIN N14 [get_ports rx22_0]
set_property PACKAGE_PIN V15 [get_ports rx21_0]
set_property PACKAGE_PIN W15 [get_ports rx20_0]
set_property PACKAGE_PIN V13 [get_ports rx19_0]
set_property PACKAGE_PIN H15 [get_ports rx18_0]
set_property PACKAGE_PIN H13 [get_ports rx17_0]
set_property PACKAGE_PIN E17 [get_ports rx16_0]
set_property PACKAGE_PIN N19 [get_ports rx15_0]
set_property PACKAGE_PIN M21 [get_ports rx14_0]
set_property PACKAGE_PIN H18 [get_ports rx13_0]
set_property PACKAGE_PIN G16 [get_ports rx12_0]
set_property PACKAGE_PIN C20 [get_ports rx11_0]
set_property PACKAGE_PIN C15 [get_ports rx10_0]
set_property PACKAGE_PIN H22 [get_ports rx9_0]
set_property PACKAGE_PIN G21 [get_ports rx8_0]
set_property PACKAGE_PIN E21 [get_ports rx7_0]
set_property PACKAGE_PIN C19 [get_ports rx6_0]
set_property PACKAGE_PIN B18 [get_ports rx5_0]
set_property PACKAGE_PIN A14 [get_ports rx4_0]
set_property PACKAGE_PIN B22 [get_ports rx3_0]
set_property PACKAGE_PIN A20 [get_ports rx2_0]
set_property PACKAGE_PIN C17 [get_ports rx1_0]
set_property PACKAGE_PIN D16 [get_ports rx0_0]

#Tx CAN signals
set_property IOSTANDARD LVCMOS33 [get_ports tx0_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx1_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx2_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx3_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx4_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx5_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx6_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx7_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx8_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx9_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx10_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx11_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx12_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx13_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx14_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx15_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx16_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx17_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx18_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx19_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx20_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx21_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx22_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx23_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx24_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx25_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx26_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx27_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx28_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx29_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx30_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx31_0]

set_property PACKAGE_PIN V18 [get_ports tx31_0]
set_property PACKAGE_PIN V20 [get_ports tx30_0]
set_property PACKAGE_PIN AB10 [get_ports tx29_0]
set_property PACKAGE_PIN W20 [get_ports tx28_0]
set_property PACKAGE_PIN T21 [get_ports tx27_0]
set_property PACKAGE_PIN T20 [get_ports tx26_0]
set_property PACKAGE_PIN W10 [get_ports tx25_0]
set_property PACKAGE_PIN Y11 [get_ports tx24_0]
set_property PACKAGE_PIN M13 [get_ports tx23_0]
set_property PACKAGE_PIN AA21 [get_ports tx22_0]
set_property PACKAGE_PIN U15 [get_ports tx21_0]
set_property PACKAGE_PIN W16 [get_ports tx20_0]
set_property PACKAGE_PIN J14 [get_ports tx19_0]
set_property PACKAGE_PIN J15 [get_ports tx18_0]
set_property PACKAGE_PIN G13 [get_ports tx17_0]
set_property PACKAGE_PIN L18 [get_ports tx16_0]
set_property PACKAGE_PIN M20 [get_ports tx15_0]
set_property PACKAGE_PIN K18 [get_ports tx14_0]
set_property PACKAGE_PIN H19 [get_ports tx13_0]
set_property PACKAGE_PIN G15 [get_ports tx12_0]
set_property PACKAGE_PIN D20 [get_ports tx11_0]
set_property PACKAGE_PIN K22 [get_ports tx10_0]
set_property PACKAGE_PIN H20 [get_ports tx9_0]
set_property PACKAGE_PIN D22 [get_ports tx8_0]
set_property PACKAGE_PIN E18 [get_ports tx7_0]
set_property PACKAGE_PIN C18 [get_ports tx6_0]
set_property PACKAGE_PIN B17 [get_ports tx5_0]
set_property PACKAGE_PIN F21 [get_ports tx4_0]
set_property PACKAGE_PIN C22 [get_ports tx3_0]
set_property PACKAGE_PIN B20 [get_ports tx2_0]
set_property PACKAGE_PIN B16 [get_ports tx1_0]
set_property PACKAGE_PIN E16 [get_ports tx0_0]
#UART signals

## DBG Signals
set_property IOSTANDARD LVCMOS33 [get_ports tx_data_rdy_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_data_rdy_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_elink_tra_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_elink_rec_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_can_rec_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_can_tra_0]
#set_property IOSTANDARD LVCMOS33 [get_ports endwait_all_0]
#set_property IOSTANDARD LVCMOS33 [get_ports irq_elink_dbg_0]
#set_property IOSTANDARD LVCMOS33 [get_ports seialize_data_stream_0]
#set_property IOSTANDARD LVCMOS33 [get_ports tx_fifo_full_rdy_0]
#LED1
set_property PACKAGE_PIN E14 [get_ports irq_elink_tra_0]
#LED2
set_property PACKAGE_PIN E13 [get_ports irq_elink_rec_0]
#LED3
set_property PACKAGE_PIN D15 [get_ports tx_data_rdy_0]
#LED4
set_property PACKAGE_PIN D14 [get_ports rx_data_rdy_0]
#LED5
set_property PACKAGE_PIN C13 [get_ports irq_can_rec_0]
#LED6
set_property PACKAGE_PIN B13 [get_ports irq_can_tra_0]
#LED7
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

#MultiBoot Bitstream Properties
#enables the Fallback option. [This enables loading the default bitstream when configuration attempt fails].
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
# allows the FPGA to use an internal configuration mode for configuration.
set_property BITSTREAM.CONFIG.PROG_MODE INTERNAL [current_project]
#This command tells Vivado that the SPI flash memory you are using for configuration can handle 32-bit addresses.
#This allows you to access a larger storage space within the flash memory
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
#The FPGA is configured to reboot (restart) itself automatically after loading a new configuration
set_property BITSTREAM.CONFIG.NEXT_CONFIG_REBOOT ENABLE [current_design]
#set_property BITSTREAM.CONFIG.NEXT_CONFIG_ADDR 0x00510000 [current_design]
#set_property BITSTREAM.CONFIG.NEXT_CONFIG_ADDR 0x00A20000 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 40 [current_design]
#  used to configure the time that the FPGA waits for the configuration process to complete before transitioning to user mode.
#This timer is important because it ensures that the configuration process has been successfully completed before the FPGA starts running your user logic.
#set_property BITSTREAM.CONFIG.TIMER_CFG 0x10000 [current_design]

############################################################
# Debug Core Constraints                                 #
############################################################

