/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ./output/llc2TMR.v                                                                     *
 *                                                                                                  *
 * user    : lucas                                                                                  *
 * host    : DESKTOP-BFDSFP2                                                                        *
 * date    : 05/12/2022 13:28:24                                                                    *
 *                                                                                                  *
 * workdir : /mnt/c/Users/Lucas/Documents/GitHub/mopshub_triplicated/triplicated/mopshub_top_board_16/hdl *
 * cmd     : /mnt/c/Users/Lucas/Documents/GitHub/mopshub_triplicated/tmrg-master/bin/tmrg -vv -c    *
 *           tmrg.cfg                                                                               *
 * tmrg rev: b25f042058e4e97751df2a0933c24aeadd5a78a5                                               *
 *                                                                                                  *
 * src file: llc2.v                                                                                 *
 *           Git SHA           : b25f042058e4e97751df2a0933c24aeadd5a78a5 (?? llc2.v)               *
 *           Modification time : 2022-11-10 21:22:58                                                *
 *           File Size         : 4882                                                               *
 *           MD5 hash          : fee9049c7e053eee8e55e3d47b88025c                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module llc2TMR(
  input wire  clock ,
  input wire  reset ,
  input wire  initreqr ,
  input wire  traregbit ,
  input wire  sucfrecvc ,
  input wire  sucftranc ,
  input wire  sucfrecvr ,
  input wire  sucftranr ,
  input wire  extended ,
  input wire [28:0] accmaskreg ,
  input wire [28:0] idreg ,
  input wire [28:0] idrec ,
  output wire  activtreg ,
  output wire  activrreg ,
  output wire  activgreg ,
  output wire  ldrecid ,
  output wire  sucftrano ,
  output wire  sucfrecvo ,
  output wire  overflowo ,
  output wire  trans ,
  output wire  load ,
  output wire  actvtsft ,
  output wire  actvtcap ,
  output wire  resettra ,
  output wire  resetall 
);
wire equal_i;

llc_fsm2TMR llc_fsm_2 (
    .clock(clock),
    .reset(reset),
    .initreqr(initreqr),
    .traregbit(traregbit),
    .sucfrecvc(sucfrecvc),
    .sucftranc(sucftranc),
    .sucfrecvr(sucfrecvr),
    .sucftranr(sucftranr),
    .equal(equal_i),
    .activtreg(activtreg),
    .activrreg(activrreg),
    .activgreg(activgreg),
    .ldrecid(ldrecid),
    .sucftrano(sucftrano),
    .sucfrecvo(sucfrecvo),
    .overflowo(overflowo),
    .trans(trans),
    .load(load),
    .actvtsft(actvtsft),
    .actvtcap(actvtcap),
    .resettra(resettra),
    .resetall(resetall)
    );

equal_id2TMR equal_id_2 (
    .extended(extended),
    .idregister(idreg),
    .idreceived(idrec),
    .accmask(accmaskreg),
    .equal(equal_i)
    );
endmodule

