/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ./output/node_rec_mux_16_structTMR.v                                                   *
 *                                                                                                  *
 * user    : lucas                                                                                  *
 * host    : DESKTOP-BFDSFP2                                                                        *
 * date    : 05/12/2022 13:28:29                                                                    *
 *                                                                                                  *
 * workdir : /mnt/c/Users/Lucas/Documents/GitHub/mopshub_triplicated/triplicated/mopshub_top_board_16/hdl *
 * cmd     : /mnt/c/Users/Lucas/Documents/GitHub/mopshub_triplicated/tmrg-master/bin/tmrg -vv -c    *
 *           tmrg.cfg                                                                               *
 * tmrg rev: b25f042058e4e97751df2a0933c24aeadd5a78a5                                               *
 *                                                                                                  *
 * src file: node_rec_mux_16_struct.v                                                               *
 *           Git SHA           : b25f042058e4e97751df2a0933c24aeadd5a78a5 (?? node_rec_mux_16_struct.v) *
 *           Modification time : 2022-12-04 15:41:31.666210                                         *
 *           File Size         : 31207                                                              *
 *           MD5 hash          : b65dbed7a93e2f8e7fc57e4b0d4e913a                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`resetall 
`timescale  1ns/10ps
module node_rec_mux_16TMR(
  input wire  clk ,
  input wire  enable_cs_sig ,
  input wire  end_can_proc ,
  input wire  endwait ,
  input wire  irqsucrec0 ,
  input wire  irqsucrec1 ,
  input wire  irqsucrec10 ,
  input wire  irqsucrec11 ,
  input wire  irqsucrec12 ,
  input wire  irqsucrec13 ,
  input wire  irqsucrec14 ,
  input wire  irqsucrec15 ,
  input wire  irqsucrec2 ,
  input wire  irqsucrec3 ,
  input wire  irqsucrec4 ,
  input wire  irqsucrec5 ,
  input wire  irqsucrec6 ,
  input wire  irqsucrec7 ,
  input wire  irqsucrec8 ,
  input wire  irqsucrec9 ,
  input wire  main_timeoutrst ,
  input wire  read_n_sig ,
  input wire [15:0] readdata0 ,
  input wire [15:0] readdata1 ,
  input wire [15:0] readdata10 ,
  input wire [15:0] readdata11 ,
  input wire [15:0] readdata12 ,
  input wire [15:0] readdata13 ,
  input wire [15:0] readdata14 ,
  input wire [15:0] readdata15 ,
  input wire [15:0] readdata2 ,
  input wire [15:0] readdata3 ,
  input wire [15:0] readdata4 ,
  input wire [15:0] readdata5 ,
  input wire [15:0] readdata6 ,
  input wire [15:0] readdata7 ,
  input wire [15:0] readdata8 ,
  input wire [15:0] readdata9 ,
  input wire  rst ,
  output wire [4:0] bus_rec_select ,
  output wire  cs_rec0 ,
  output wire  cs_rec1 ,
  output wire  cs_rec10 ,
  output wire  cs_rec11 ,
  output wire  cs_rec12 ,
  output wire  cs_rec13 ,
  output wire  cs_rec14 ,
  output wire  cs_rec15 ,
  output wire  cs_rec2 ,
  output wire  cs_rec3 ,
  output wire  cs_rec4 ,
  output wire  cs_rec5 ,
  output wire  cs_rec6 ,
  output wire  cs_rec7 ,
  output wire  cs_rec8 ,
  output wire  cs_rec9 ,
  output wire  irq_can_rec ,
  output wire  read_n0 ,
  output wire  read_n1 ,
  output wire  read_n10 ,
  output wire  read_n11 ,
  output wire  read_n12 ,
  output wire  read_n13 ,
  output wire  read_n14 ,
  output wire  read_n15 ,
  output wire  read_n2 ,
  output wire  read_n3 ,
  output wire  read_n4 ,
  output wire  read_n5 ,
  output wire  read_n6 ,
  output wire  read_n7 ,
  output wire  read_n8 ,
  output wire  read_n9 ,
  output wire [15:0] readdata 
);
wire rstC;
wire rstB;
wire rstA;
wire [31:0] mw_spi_bus_fiforeg_nval9C;
wire [31:0] mw_spi_bus_fiforeg_nval9B;
wire [31:0] mw_spi_bus_fiforeg_nval9A;
wire [31:0] mw_spi_bus_fiforeg_nval8C;
wire [31:0] mw_spi_bus_fiforeg_nval8B;
wire [31:0] mw_spi_bus_fiforeg_nval8A;
wire [31:0] mw_spi_bus_fiforeg_nval7C;
wire [31:0] mw_spi_bus_fiforeg_nval7B;
wire [31:0] mw_spi_bus_fiforeg_nval7A;
wire [31:0] mw_spi_bus_fiforeg_nval6C;
wire [31:0] mw_spi_bus_fiforeg_nval6B;
wire [31:0] mw_spi_bus_fiforeg_nval6A;
wire [31:0] mw_spi_bus_fiforeg_nval5C;
wire [31:0] mw_spi_bus_fiforeg_nval5B;
wire [31:0] mw_spi_bus_fiforeg_nval5A;
wire [31:0] mw_spi_bus_fiforeg_nval4C;
wire [31:0] mw_spi_bus_fiforeg_nval4B;
wire [31:0] mw_spi_bus_fiforeg_nval4A;
wire [31:0] mw_spi_bus_fiforeg_nval3C;
wire [31:0] mw_spi_bus_fiforeg_nval3B;
wire [31:0] mw_spi_bus_fiforeg_nval3A;
wire [31:0] mw_spi_bus_fiforeg_nval32C;
wire [31:0] mw_spi_bus_fiforeg_nval32B;
wire [31:0] mw_spi_bus_fiforeg_nval32A;
wire [31:0] mw_spi_bus_fiforeg_nval31C;
wire [31:0] mw_spi_bus_fiforeg_nval31B;
wire [31:0] mw_spi_bus_fiforeg_nval31A;
wire [31:0] mw_spi_bus_fiforeg_nval30C;
wire [31:0] mw_spi_bus_fiforeg_nval30B;
wire [31:0] mw_spi_bus_fiforeg_nval30A;
wire [31:0] mw_spi_bus_fiforeg_nval2C;
wire [31:0] mw_spi_bus_fiforeg_nval2B;
wire [31:0] mw_spi_bus_fiforeg_nval2A;
wire [31:0] mw_spi_bus_fiforeg_nval29C;
wire [31:0] mw_spi_bus_fiforeg_nval29B;
wire [31:0] mw_spi_bus_fiforeg_nval29A;
wire [31:0] mw_spi_bus_fiforeg_nval28C;
wire [31:0] mw_spi_bus_fiforeg_nval28B;
wire [31:0] mw_spi_bus_fiforeg_nval28A;
wire [31:0] mw_spi_bus_fiforeg_nval27C;
wire [31:0] mw_spi_bus_fiforeg_nval27B;
wire [31:0] mw_spi_bus_fiforeg_nval27A;
wire [31:0] mw_spi_bus_fiforeg_nval26C;
wire [31:0] mw_spi_bus_fiforeg_nval26B;
wire [31:0] mw_spi_bus_fiforeg_nval26A;
wire [31:0] mw_spi_bus_fiforeg_nval25C;
wire [31:0] mw_spi_bus_fiforeg_nval25B;
wire [31:0] mw_spi_bus_fiforeg_nval25A;
wire [31:0] mw_spi_bus_fiforeg_nval24C;
wire [31:0] mw_spi_bus_fiforeg_nval24B;
wire [31:0] mw_spi_bus_fiforeg_nval24A;
wire [31:0] mw_spi_bus_fiforeg_nval23C;
wire [31:0] mw_spi_bus_fiforeg_nval23B;
wire [31:0] mw_spi_bus_fiforeg_nval23A;
wire [31:0] mw_spi_bus_fiforeg_nval22C;
wire [31:0] mw_spi_bus_fiforeg_nval22B;
wire [31:0] mw_spi_bus_fiforeg_nval22A;
wire [31:0] mw_spi_bus_fiforeg_nval21C;
wire [31:0] mw_spi_bus_fiforeg_nval21B;
wire [31:0] mw_spi_bus_fiforeg_nval21A;
wire [31:0] mw_spi_bus_fiforeg_nval20C;
wire [31:0] mw_spi_bus_fiforeg_nval20B;
wire [31:0] mw_spi_bus_fiforeg_nval20A;
wire [31:0] mw_spi_bus_fiforeg_nval1C;
wire [31:0] mw_spi_bus_fiforeg_nval1B;
wire [31:0] mw_spi_bus_fiforeg_nval1A;
wire [31:0] mw_spi_bus_fiforeg_nval19C;
wire [31:0] mw_spi_bus_fiforeg_nval19B;
wire [31:0] mw_spi_bus_fiforeg_nval19A;
wire [31:0] mw_spi_bus_fiforeg_nval18C;
wire [31:0] mw_spi_bus_fiforeg_nval18B;
wire [31:0] mw_spi_bus_fiforeg_nval18A;
wire [31:0] mw_spi_bus_fiforeg_nval17C;
wire [31:0] mw_spi_bus_fiforeg_nval17B;
wire [31:0] mw_spi_bus_fiforeg_nval17A;
wire [31:0] mw_spi_bus_fiforeg_nval16C;
wire [31:0] mw_spi_bus_fiforeg_nval16B;
wire [31:0] mw_spi_bus_fiforeg_nval16A;
wire [31:0] mw_spi_bus_fiforeg_nval15C;
wire [31:0] mw_spi_bus_fiforeg_nval15B;
wire [31:0] mw_spi_bus_fiforeg_nval15A;
wire [31:0] mw_spi_bus_fiforeg_nval14C;
wire [31:0] mw_spi_bus_fiforeg_nval14B;
wire [31:0] mw_spi_bus_fiforeg_nval14A;
wire [31:0] mw_spi_bus_fiforeg_nval13C;
wire [31:0] mw_spi_bus_fiforeg_nval13B;
wire [31:0] mw_spi_bus_fiforeg_nval13A;
wire [31:0] mw_spi_bus_fiforeg_nval12C;
wire [31:0] mw_spi_bus_fiforeg_nval12B;
wire [31:0] mw_spi_bus_fiforeg_nval12A;
wire [31:0] mw_spi_bus_fiforeg_nval11C;
wire [31:0] mw_spi_bus_fiforeg_nval11B;
wire [31:0] mw_spi_bus_fiforeg_nval11A;
wire [31:0] mw_spi_bus_fiforeg_nval10C;
wire [31:0] mw_spi_bus_fiforeg_nval10B;
wire [31:0] mw_spi_bus_fiforeg_nval10A;
wire [31:0] mw_spi_bus_fiforeg_nval0C;
wire [31:0] mw_spi_bus_fiforeg_nval0B;
wire [31:0] mw_spi_bus_fiforeg_nval0A;
wire [5:0] mw_spi_bus_fifoaddr_nvalC;
wire [5:0] mw_spi_bus_fifoaddr_nvalB;
wire [5:0] mw_spi_bus_fifoaddr_nvalA;
wire ireqsucrecC;
wire ireqsucrecB;
wire ireqsucrecA;
wire def_value_1C;
wire def_value_1B;
wire def_value_1A;
wire clkC;
wire clkB;
wire clkA;
wor wenaTmrError;
wire wena;
wor mw_spi_bus_fiforeg_cval9TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval9;
wor mw_spi_bus_fiforeg_cval8TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval8;
wor mw_spi_bus_fiforeg_cval7TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval7;
wor mw_spi_bus_fiforeg_cval6TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval6;
wor mw_spi_bus_fiforeg_cval5TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval5;
wor mw_spi_bus_fiforeg_cval4TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval4;
wor mw_spi_bus_fiforeg_cval3TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval3;
wor mw_spi_bus_fiforeg_cval32TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval32;
wor mw_spi_bus_fiforeg_cval31TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval31;
wor mw_spi_bus_fiforeg_cval30TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval30;
wor mw_spi_bus_fiforeg_cval2TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval2;
wor mw_spi_bus_fiforeg_cval29TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval29;
wor mw_spi_bus_fiforeg_cval28TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval28;
wor mw_spi_bus_fiforeg_cval27TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval27;
wor mw_spi_bus_fiforeg_cval26TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval26;
wor mw_spi_bus_fiforeg_cval25TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval25;
wor mw_spi_bus_fiforeg_cval24TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval24;
wor mw_spi_bus_fiforeg_cval23TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval23;
wor mw_spi_bus_fiforeg_cval22TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval22;
wor mw_spi_bus_fiforeg_cval21TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval21;
wor mw_spi_bus_fiforeg_cval20TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval20;
wor mw_spi_bus_fiforeg_cval1TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval1;
wor mw_spi_bus_fiforeg_cval19TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval19;
wor mw_spi_bus_fiforeg_cval18TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval18;
wor mw_spi_bus_fiforeg_cval17TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval17;
wor mw_spi_bus_fiforeg_cval16TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval16;
wor mw_spi_bus_fiforeg_cval15TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval15;
wor mw_spi_bus_fiforeg_cval14TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval14;
wor mw_spi_bus_fiforeg_cval13TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval13;
wor mw_spi_bus_fiforeg_cval12TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval12;
wor mw_spi_bus_fiforeg_cval11TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval11;
wor mw_spi_bus_fiforeg_cval10TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval10;
wor mw_spi_bus_fiforeg_cval0TmrError;
wire [31:0] mw_spi_bus_fiforeg_cval0;
wor mw_spi_bus_fifoaddr_cvalTmrError;
wire [5:0] mw_spi_bus_fifoaddr_cval;
wire a_fifo_empty;
wire canakari_entimeout;
wire canakari_timeoutrst;
wire cs_signal_read;
wire [31:0] data_rec_out;
reg  def_value_0 ;
reg  def_value_1 ;
wire done_bus_loop;
wire end_choose_bus;
wire [31:0] ffout;
wire fifo_read_en;
wire ireqsucrec;
wire [31:0] irqsucrec_signals;
wire read_irqsucrec;
wire start_bus_loop;
reg  [31:0] time_limit ;
wire timeoutrst;
reg  wenaA ;
reg  wenaB ;
reg  wenaC ;
reg  [31:0] mw_spi_bus_fiforeg_cval0A ;
reg  [31:0] mw_spi_bus_fiforeg_cval0B ;
reg  [31:0] mw_spi_bus_fiforeg_cval0C ;
reg  [31:0] mw_spi_bus_fiforeg_cval1A ;
reg  [31:0] mw_spi_bus_fiforeg_cval1B ;
reg  [31:0] mw_spi_bus_fiforeg_cval1C ;
reg  [31:0] mw_spi_bus_fiforeg_cval2A ;
reg  [31:0] mw_spi_bus_fiforeg_cval2B ;
reg  [31:0] mw_spi_bus_fiforeg_cval2C ;
reg  [31:0] mw_spi_bus_fiforeg_cval3A ;
reg  [31:0] mw_spi_bus_fiforeg_cval3B ;
reg  [31:0] mw_spi_bus_fiforeg_cval3C ;
reg  [31:0] mw_spi_bus_fiforeg_cval4A ;
reg  [31:0] mw_spi_bus_fiforeg_cval4B ;
reg  [31:0] mw_spi_bus_fiforeg_cval4C ;
reg  [31:0] mw_spi_bus_fiforeg_cval5A ;
reg  [31:0] mw_spi_bus_fiforeg_cval5B ;
reg  [31:0] mw_spi_bus_fiforeg_cval5C ;
reg  [31:0] mw_spi_bus_fiforeg_cval6A ;
reg  [31:0] mw_spi_bus_fiforeg_cval6B ;
reg  [31:0] mw_spi_bus_fiforeg_cval6C ;
reg  [31:0] mw_spi_bus_fiforeg_cval7A ;
reg  [31:0] mw_spi_bus_fiforeg_cval7B ;
reg  [31:0] mw_spi_bus_fiforeg_cval7C ;
reg  [31:0] mw_spi_bus_fiforeg_cval8A ;
reg  [31:0] mw_spi_bus_fiforeg_cval8B ;
reg  [31:0] mw_spi_bus_fiforeg_cval8C ;
reg  [31:0] mw_spi_bus_fiforeg_cval9A ;
reg  [31:0] mw_spi_bus_fiforeg_cval9B ;
reg  [31:0] mw_spi_bus_fiforeg_cval9C ;
reg  [31:0] mw_spi_bus_fiforeg_cval10A ;
reg  [31:0] mw_spi_bus_fiforeg_cval10B ;
reg  [31:0] mw_spi_bus_fiforeg_cval10C ;
reg  [31:0] mw_spi_bus_fiforeg_cval11A ;
reg  [31:0] mw_spi_bus_fiforeg_cval11B ;
reg  [31:0] mw_spi_bus_fiforeg_cval11C ;
reg  [31:0] mw_spi_bus_fiforeg_cval12A ;
reg  [31:0] mw_spi_bus_fiforeg_cval12B ;
reg  [31:0] mw_spi_bus_fiforeg_cval12C ;
reg  [31:0] mw_spi_bus_fiforeg_cval13A ;
reg  [31:0] mw_spi_bus_fiforeg_cval13B ;
reg  [31:0] mw_spi_bus_fiforeg_cval13C ;
reg  [31:0] mw_spi_bus_fiforeg_cval14A ;
reg  [31:0] mw_spi_bus_fiforeg_cval14B ;
reg  [31:0] mw_spi_bus_fiforeg_cval14C ;
reg  [31:0] mw_spi_bus_fiforeg_cval15A ;
reg  [31:0] mw_spi_bus_fiforeg_cval15B ;
reg  [31:0] mw_spi_bus_fiforeg_cval15C ;
reg  [31:0] mw_spi_bus_fiforeg_cval16A ;
reg  [31:0] mw_spi_bus_fiforeg_cval16B ;
reg  [31:0] mw_spi_bus_fiforeg_cval16C ;
reg  [31:0] mw_spi_bus_fiforeg_cval17A ;
reg  [31:0] mw_spi_bus_fiforeg_cval17B ;
reg  [31:0] mw_spi_bus_fiforeg_cval17C ;
reg  [31:0] mw_spi_bus_fiforeg_cval18A ;
reg  [31:0] mw_spi_bus_fiforeg_cval18B ;
reg  [31:0] mw_spi_bus_fiforeg_cval18C ;
reg  [31:0] mw_spi_bus_fiforeg_cval19A ;
reg  [31:0] mw_spi_bus_fiforeg_cval19B ;
reg  [31:0] mw_spi_bus_fiforeg_cval19C ;
reg  [31:0] mw_spi_bus_fiforeg_cval20A ;
reg  [31:0] mw_spi_bus_fiforeg_cval20B ;
reg  [31:0] mw_spi_bus_fiforeg_cval20C ;
reg  [31:0] mw_spi_bus_fiforeg_cval21A ;
reg  [31:0] mw_spi_bus_fiforeg_cval21B ;
reg  [31:0] mw_spi_bus_fiforeg_cval21C ;
reg  [31:0] mw_spi_bus_fiforeg_cval22A ;
reg  [31:0] mw_spi_bus_fiforeg_cval22B ;
reg  [31:0] mw_spi_bus_fiforeg_cval22C ;
reg  [31:0] mw_spi_bus_fiforeg_cval23A ;
reg  [31:0] mw_spi_bus_fiforeg_cval23B ;
reg  [31:0] mw_spi_bus_fiforeg_cval23C ;
reg  [31:0] mw_spi_bus_fiforeg_cval24A ;
reg  [31:0] mw_spi_bus_fiforeg_cval24B ;
reg  [31:0] mw_spi_bus_fiforeg_cval24C ;
reg  [31:0] mw_spi_bus_fiforeg_cval25A ;
reg  [31:0] mw_spi_bus_fiforeg_cval25B ;
reg  [31:0] mw_spi_bus_fiforeg_cval25C ;
reg  [31:0] mw_spi_bus_fiforeg_cval26A ;
reg  [31:0] mw_spi_bus_fiforeg_cval26B ;
reg  [31:0] mw_spi_bus_fiforeg_cval26C ;
reg  [31:0] mw_spi_bus_fiforeg_cval27A ;
reg  [31:0] mw_spi_bus_fiforeg_cval27B ;
reg  [31:0] mw_spi_bus_fiforeg_cval27C ;
reg  [31:0] mw_spi_bus_fiforeg_cval28A ;
reg  [31:0] mw_spi_bus_fiforeg_cval28B ;
reg  [31:0] mw_spi_bus_fiforeg_cval28C ;
reg  [31:0] mw_spi_bus_fiforeg_cval29A ;
reg  [31:0] mw_spi_bus_fiforeg_cval29B ;
reg  [31:0] mw_spi_bus_fiforeg_cval29C ;
reg  [31:0] mw_spi_bus_fiforeg_cval30A ;
reg  [31:0] mw_spi_bus_fiforeg_cval30B ;
reg  [31:0] mw_spi_bus_fiforeg_cval30C ;
reg  [31:0] mw_spi_bus_fiforeg_cval31A ;
reg  [31:0] mw_spi_bus_fiforeg_cval31B ;
reg  [31:0] mw_spi_bus_fiforeg_cval31C ;
reg  [31:0] mw_spi_bus_fiforeg_cval32A ;
reg  [31:0] mw_spi_bus_fiforeg_cval32B ;
reg  [31:0] mw_spi_bus_fiforeg_cval32C ;
wire [31:0] mw_spi_bus_fiforeg_nval0;
wire [31:0] mw_spi_bus_fiforeg_nval1;
wire [31:0] mw_spi_bus_fiforeg_nval2;
wire [31:0] mw_spi_bus_fiforeg_nval3;
wire [31:0] mw_spi_bus_fiforeg_nval4;
wire [31:0] mw_spi_bus_fiforeg_nval5;
wire [31:0] mw_spi_bus_fiforeg_nval6;
wire [31:0] mw_spi_bus_fiforeg_nval7;
wire [31:0] mw_spi_bus_fiforeg_nval8;
wire [31:0] mw_spi_bus_fiforeg_nval9;
wire [31:0] mw_spi_bus_fiforeg_nval10;
wire [31:0] mw_spi_bus_fiforeg_nval11;
wire [31:0] mw_spi_bus_fiforeg_nval12;
wire [31:0] mw_spi_bus_fiforeg_nval13;
wire [31:0] mw_spi_bus_fiforeg_nval14;
wire [31:0] mw_spi_bus_fiforeg_nval15;
wire [31:0] mw_spi_bus_fiforeg_nval16;
wire [31:0] mw_spi_bus_fiforeg_nval17;
wire [31:0] mw_spi_bus_fiforeg_nval18;
wire [31:0] mw_spi_bus_fiforeg_nval19;
wire [31:0] mw_spi_bus_fiforeg_nval20;
wire [31:0] mw_spi_bus_fiforeg_nval21;
wire [31:0] mw_spi_bus_fiforeg_nval22;
wire [31:0] mw_spi_bus_fiforeg_nval23;
wire [31:0] mw_spi_bus_fiforeg_nval24;
wire [31:0] mw_spi_bus_fiforeg_nval25;
wire [31:0] mw_spi_bus_fiforeg_nval26;
wire [31:0] mw_spi_bus_fiforeg_nval27;
wire [31:0] mw_spi_bus_fiforeg_nval28;
wire [31:0] mw_spi_bus_fiforeg_nval29;
wire [31:0] mw_spi_bus_fiforeg_nval30;
wire [31:0] mw_spi_bus_fiforeg_nval31;
wire [31:0] mw_spi_bus_fiforeg_nval32;
wire mw_spi_bus_fifotemp_rena;
wire mw_spi_bus_fifotemp_wena;
wire mw_spi_bus_fifotemp_full;
wire mw_spi_bus_fifotemp_empty;
reg  [5:0] mw_spi_bus_fifoaddr_cvalA ;
reg  [5:0] mw_spi_bus_fifoaddr_cvalB ;
reg  [5:0] mw_spi_bus_fifoaddr_cvalC ;
wire [5:0] mw_spi_bus_fifoaddr_nval;
wire [31:0] mw_spi_bus_fiforeg_cval0V =  mw_spi_bus_fiforeg_cval0;
wire [31:0] mw_spi_bus_fiforeg_cval1V =  mw_spi_bus_fiforeg_cval1;
wire [31:0] mw_spi_bus_fiforeg_cval2V =  mw_spi_bus_fiforeg_cval2;
wire [31:0] mw_spi_bus_fiforeg_cval3V =  mw_spi_bus_fiforeg_cval3;
wire [31:0] mw_spi_bus_fiforeg_cval4V =  mw_spi_bus_fiforeg_cval4;
wire [31:0] mw_spi_bus_fiforeg_cval5V =  mw_spi_bus_fiforeg_cval5;
wire [31:0] mw_spi_bus_fiforeg_cval6V =  mw_spi_bus_fiforeg_cval6;
wire [31:0] mw_spi_bus_fiforeg_cval7V =  mw_spi_bus_fiforeg_cval7;
wire [31:0] mw_spi_bus_fiforeg_cval8V =  mw_spi_bus_fiforeg_cval8;
wire [31:0] mw_spi_bus_fiforeg_cval9V =  mw_spi_bus_fiforeg_cval9;
wire [31:0] mw_spi_bus_fiforeg_cval10V =  mw_spi_bus_fiforeg_cval10;
wire [31:0] mw_spi_bus_fiforeg_cval11V =  mw_spi_bus_fiforeg_cval11;
wire [31:0] mw_spi_bus_fiforeg_cval12V =  mw_spi_bus_fiforeg_cval12;
wire [31:0] mw_spi_bus_fiforeg_cval13V =  mw_spi_bus_fiforeg_cval13;
wire [31:0] mw_spi_bus_fiforeg_cval14V =  mw_spi_bus_fiforeg_cval14;
wire [31:0] mw_spi_bus_fiforeg_cval15V =  mw_spi_bus_fiforeg_cval15;
wire [31:0] mw_spi_bus_fiforeg_cval16V =  mw_spi_bus_fiforeg_cval16;
wire [31:0] mw_spi_bus_fiforeg_cval17V =  mw_spi_bus_fiforeg_cval17;
wire [31:0] mw_spi_bus_fiforeg_cval18V =  mw_spi_bus_fiforeg_cval18;
wire [31:0] mw_spi_bus_fiforeg_cval19V =  mw_spi_bus_fiforeg_cval19;
wire [31:0] mw_spi_bus_fiforeg_cval20V =  mw_spi_bus_fiforeg_cval20;
wire [31:0] mw_spi_bus_fiforeg_cval21V =  mw_spi_bus_fiforeg_cval21;
wire [31:0] mw_spi_bus_fiforeg_cval22V =  mw_spi_bus_fiforeg_cval22;
wire [31:0] mw_spi_bus_fiforeg_cval23V =  mw_spi_bus_fiforeg_cval23;
wire [31:0] mw_spi_bus_fiforeg_cval24V =  mw_spi_bus_fiforeg_cval24;
wire [31:0] mw_spi_bus_fiforeg_cval25V =  mw_spi_bus_fiforeg_cval25;
wire [31:0] mw_spi_bus_fiforeg_cval26V =  mw_spi_bus_fiforeg_cval26;
wire [31:0] mw_spi_bus_fiforeg_cval27V =  mw_spi_bus_fiforeg_cval27;
wire [31:0] mw_spi_bus_fiforeg_cval28V =  mw_spi_bus_fiforeg_cval28;
wire [31:0] mw_spi_bus_fiforeg_cval29V =  mw_spi_bus_fiforeg_cval29;
wire [31:0] mw_spi_bus_fiforeg_cval30V =  mw_spi_bus_fiforeg_cval30;
wire [31:0] mw_spi_bus_fiforeg_cval31V =  mw_spi_bus_fiforeg_cval31;
wire [31:0] mw_spi_bus_fiforeg_cval32V =  mw_spi_bus_fiforeg_cval32;
wire [5:0] mw_spi_bus_fifoaddr_cvalV =  mw_spi_bus_fifoaddr_cval;
wire wenaV =  wena;

bus_rec_SMTMR bus_rec_SM0 (
    .bus_rec_select(bus_rec_select),
    .entimeout(canakari_entimeout),
    .can_rec(data_rec_out),
    .irq_can_rec(irq_can_rec),
    .clk(clk),
    .end_choose_bus(end_choose_bus),
    .endwait(endwait),
    .start_bus_loop(start_bus_loop),
    .ireqsucrec(a_fifo_empty),
    .rst(rst),
    .done_bus_loop(done_bus_loop),
    .read_irqsucrec(read_irqsucrec),
    .timeoutrst(canakari_timeoutrst),
    .end_can_proc(end_can_proc),
    .fifo_read_en(fifo_read_en)
    );

dec16_1_16bitTMR dec16_1_16bit_irq (
    .clk(clk),
    .rst(rst),
    .Input0(irqsucrec0),
    .Input1(irqsucrec1),
    .Input2(irqsucrec2),
    .Input3(irqsucrec3),
    .Input4(irqsucrec4),
    .Input5(irqsucrec5),
    .Input6(irqsucrec6),
    .Input7(irqsucrec7),
    .Input8(irqsucrec8),
    .Input9(irqsucrec9),
    .Input10(irqsucrec10),
    .Input11(irqsucrec11),
    .Input12(irqsucrec12),
    .Input13(irqsucrec13),
    .Input14(irqsucrec14),
    .Input15(irqsucrec15),
    .data_tra_out(irqsucrec_signals)
    );

dec1_1_32bitTMR dec1_1_32bit_bus_rec_select (
    .clk(clk),
    .rst(rst),
    .buffer_en(read_irqsucrec),
    .rst_bus_sig(end_choose_bus),
    .bus_rec_select(bus_rec_select),
    .data_rec_in(ffout),
    .data_rec_out(data_rec_out)
    );

demux1_16_1bitTMR demux1_16_1bit_cs (
    .def_value(def_value_0),
    .sel(bus_rec_select),
    .input_port(cs_signal_read),
    .output0(cs_rec0),
    .output1(cs_rec1),
    .output2(cs_rec2),
    .output3(cs_rec3),
    .output4(cs_rec4),
    .output5(cs_rec5),
    .output6(cs_rec6),
    .output7(cs_rec7),
    .output8(cs_rec8),
    .output9(cs_rec9),
    .output10(cs_rec10),
    .output11(cs_rec11),
    .output12(cs_rec12),
    .output13(cs_rec13),
    .output14(cs_rec14),
    .output15(cs_rec15)
    );

demux1_16_1bitTMR demux1_16_1bit_read (
    .def_value(def_value_1),
    .sel(bus_rec_select),
    .input_port(read_n_sig),
    .output0(read_n0),
    .output1(read_n1),
    .output2(read_n2),
    .output3(read_n3),
    .output4(read_n4),
    .output5(read_n5),
    .output6(read_n6),
    .output7(read_n7),
    .output8(read_n8),
    .output9(read_n9),
    .output10(read_n10),
    .output11(read_n11),
    .output12(read_n12),
    .output13(read_n13),
    .output14(read_n14),
    .output15(read_n15)
    );

mux16_1_16bitTMR mux16_1_16bit (
    .clk(clk),
    .rst(rst),
    .data0(readdata0),
    .data1(readdata1),
    .data2(readdata2),
    .data3(readdata3),
    .data4(readdata4),
    .data5(readdata5),
    .data6(readdata6),
    .data7(readdata7),
    .data8(readdata8),
    .data9(readdata9),
    .data10(readdata10),
    .data11(readdata11),
    .data12(readdata12),
    .data13(readdata13),
    .data14(readdata14),
    .data15(readdata15),
    .sel(bus_rec_select),
    .data_out(readdata)
    );

timout_rstTMR timout_rst1 (
    .clk(clk),
    .entimeout(canakari_entimeout),
    .time_limit(time_limit),
    .rst(rst),
    .timeoutrst(timeoutrst)
    );
initial
  begin
    def_value_0 =  1'b0;
    def_value_1 =  1'b1;
    time_limit =  32'd25000000;
  end
assign ireqsucrec =  irqsucrec0|irqsucrec1|irqsucrec2|irqsucrec3|irqsucrec4|irqsucrec5|irqsucrec6|irqsucrec7|irqsucrec8|irqsucrec9|irqsucrec10|irqsucrec11|irqsucrec12|irqsucrec13|irqsucrec14|irqsucrec15;

always @( posedge clkA )
  begin
    if (!rstA)
      wenaA <= 0;
    else
      if (ireqsucrecA)
        wenaA <= 1;
      else
        wenaA <= 0;
  end

always @( posedge clkB )
  begin
    if (!rstB)
      wenaB <= 0;
    else
      if (ireqsucrecB)
        wenaB <= 1;
      else
        wenaB <= 0;
  end

always @( posedge clkC )
  begin
    if (!rstC)
      wenaC <= 0;
    else
      if (ireqsucrecC)
        wenaC <= 1;
      else
        wenaC <= 0;
  end
assign cs_signal_read =  (enable_cs_sig&&!read_n_sig);
assign canakari_timeoutrst =  (main_timeoutrst||timeoutrst);
assign ffout =  mw_spi_bus_fiforeg_cval0;
assign a_fifo_empty =  ~(mw_spi_bus_fifotemp_empty);
assign mw_spi_bus_fifotemp_rena =  rst&fifo_read_en&~mw_spi_bus_fifotemp_empty;
assign mw_spi_bus_fifotemp_wena =  rst&wena&~mw_spi_bus_fifotemp_full;
assign mw_spi_bus_fifotemp_empty =  (mw_spi_bus_fifoaddr_cval==0);
assign mw_spi_bus_fifotemp_full =  (mw_spi_bus_fifoaddr_cval==32);
assign mw_spi_bus_fifoaddr_nval =  (~ rst ) ? 0 : mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? mw_spi_bus_fifoaddr_cval : mw_spi_bus_fifoaddr_cval+1'b1 : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fifoaddr_cval-1'b1 : mw_spi_bus_fifoaddr_cval;

always @( posedge clkA )
  begin : spi_bus_fifoseq_procA
    if (def_value_1A)
      mw_spi_bus_fifoaddr_cvalA =  mw_spi_bus_fifoaddr_nvalA;
  end

always @( posedge clkB )
  begin : spi_bus_fifoseq_procB
    if (def_value_1B)
      mw_spi_bus_fifoaddr_cvalB =  mw_spi_bus_fifoaddr_nvalB;
  end

always @( posedge clkC )
  begin : spi_bus_fifoseq_procC
    if (def_value_1C)
      mw_spi_bus_fifoaddr_cvalC =  mw_spi_bus_fifoaddr_nvalC;
  end

always @( posedge clkA )
  begin : spi_bus_fifomove_procA
    if (def_value_1A)
      begin
        mw_spi_bus_fiforeg_cval0A[31:0]  =  mw_spi_bus_fiforeg_nval0A[31:0] ;
        mw_spi_bus_fiforeg_cval1A[31:0]  =  mw_spi_bus_fiforeg_nval1A[31:0] ;
        mw_spi_bus_fiforeg_cval2A[31:0]  =  mw_spi_bus_fiforeg_nval2A[31:0] ;
        mw_spi_bus_fiforeg_cval3A[31:0]  =  mw_spi_bus_fiforeg_nval3A[31:0] ;
        mw_spi_bus_fiforeg_cval4A[31:0]  =  mw_spi_bus_fiforeg_nval4A[31:0] ;
        mw_spi_bus_fiforeg_cval5A[31:0]  =  mw_spi_bus_fiforeg_nval5A[31:0] ;
        mw_spi_bus_fiforeg_cval6A[31:0]  =  mw_spi_bus_fiforeg_nval6A[31:0] ;
        mw_spi_bus_fiforeg_cval7A[31:0]  =  mw_spi_bus_fiforeg_nval7A[31:0] ;
        mw_spi_bus_fiforeg_cval8A[31:0]  =  mw_spi_bus_fiforeg_nval8A[31:0] ;
        mw_spi_bus_fiforeg_cval9A[31:0]  =  mw_spi_bus_fiforeg_nval9A[31:0] ;
        mw_spi_bus_fiforeg_cval10A[31:0]  =  mw_spi_bus_fiforeg_nval10A[31:0] ;
        mw_spi_bus_fiforeg_cval11A[31:0]  =  mw_spi_bus_fiforeg_nval11A[31:0] ;
        mw_spi_bus_fiforeg_cval12A[31:0]  =  mw_spi_bus_fiforeg_nval12A[31:0] ;
        mw_spi_bus_fiforeg_cval13A[31:0]  =  mw_spi_bus_fiforeg_nval13A[31:0] ;
        mw_spi_bus_fiforeg_cval14A[31:0]  =  mw_spi_bus_fiforeg_nval14A[31:0] ;
        mw_spi_bus_fiforeg_cval15A[31:0]  =  mw_spi_bus_fiforeg_nval15A[31:0] ;
        mw_spi_bus_fiforeg_cval16A[31:0]  =  mw_spi_bus_fiforeg_nval16A[31:0] ;
        mw_spi_bus_fiforeg_cval17A[31:0]  =  mw_spi_bus_fiforeg_nval17A[31:0] ;
        mw_spi_bus_fiforeg_cval18A[31:0]  =  mw_spi_bus_fiforeg_nval18A[31:0] ;
        mw_spi_bus_fiforeg_cval19A[31:0]  =  mw_spi_bus_fiforeg_nval19A[31:0] ;
        mw_spi_bus_fiforeg_cval20A[31:0]  =  mw_spi_bus_fiforeg_nval20A[31:0] ;
        mw_spi_bus_fiforeg_cval21A[31:0]  =  mw_spi_bus_fiforeg_nval21A[31:0] ;
        mw_spi_bus_fiforeg_cval22A[31:0]  =  mw_spi_bus_fiforeg_nval22A[31:0] ;
        mw_spi_bus_fiforeg_cval23A[31:0]  =  mw_spi_bus_fiforeg_nval23A[31:0] ;
        mw_spi_bus_fiforeg_cval24A[31:0]  =  mw_spi_bus_fiforeg_nval24A[31:0] ;
        mw_spi_bus_fiforeg_cval25A[31:0]  =  mw_spi_bus_fiforeg_nval25A[31:0] ;
        mw_spi_bus_fiforeg_cval26A[31:0]  =  mw_spi_bus_fiforeg_nval26A[31:0] ;
        mw_spi_bus_fiforeg_cval27A[31:0]  =  mw_spi_bus_fiforeg_nval27A[31:0] ;
        mw_spi_bus_fiforeg_cval28A[31:0]  =  mw_spi_bus_fiforeg_nval28A[31:0] ;
        mw_spi_bus_fiforeg_cval29A[31:0]  =  mw_spi_bus_fiforeg_nval29A[31:0] ;
        mw_spi_bus_fiforeg_cval30A[31:0]  =  mw_spi_bus_fiforeg_nval30A[31:0] ;
        mw_spi_bus_fiforeg_cval31A[31:0]  =  mw_spi_bus_fiforeg_nval31A[31:0] ;
        mw_spi_bus_fiforeg_cval32A[31:0]  =  mw_spi_bus_fiforeg_nval32A[31:0] ;
      end
  end

always @( posedge clkB )
  begin : spi_bus_fifomove_procB
    if (def_value_1B)
      begin
        mw_spi_bus_fiforeg_cval0B[31:0]  =  mw_spi_bus_fiforeg_nval0B[31:0] ;
        mw_spi_bus_fiforeg_cval1B[31:0]  =  mw_spi_bus_fiforeg_nval1B[31:0] ;
        mw_spi_bus_fiforeg_cval2B[31:0]  =  mw_spi_bus_fiforeg_nval2B[31:0] ;
        mw_spi_bus_fiforeg_cval3B[31:0]  =  mw_spi_bus_fiforeg_nval3B[31:0] ;
        mw_spi_bus_fiforeg_cval4B[31:0]  =  mw_spi_bus_fiforeg_nval4B[31:0] ;
        mw_spi_bus_fiforeg_cval5B[31:0]  =  mw_spi_bus_fiforeg_nval5B[31:0] ;
        mw_spi_bus_fiforeg_cval6B[31:0]  =  mw_spi_bus_fiforeg_nval6B[31:0] ;
        mw_spi_bus_fiforeg_cval7B[31:0]  =  mw_spi_bus_fiforeg_nval7B[31:0] ;
        mw_spi_bus_fiforeg_cval8B[31:0]  =  mw_spi_bus_fiforeg_nval8B[31:0] ;
        mw_spi_bus_fiforeg_cval9B[31:0]  =  mw_spi_bus_fiforeg_nval9B[31:0] ;
        mw_spi_bus_fiforeg_cval10B[31:0]  =  mw_spi_bus_fiforeg_nval10B[31:0] ;
        mw_spi_bus_fiforeg_cval11B[31:0]  =  mw_spi_bus_fiforeg_nval11B[31:0] ;
        mw_spi_bus_fiforeg_cval12B[31:0]  =  mw_spi_bus_fiforeg_nval12B[31:0] ;
        mw_spi_bus_fiforeg_cval13B[31:0]  =  mw_spi_bus_fiforeg_nval13B[31:0] ;
        mw_spi_bus_fiforeg_cval14B[31:0]  =  mw_spi_bus_fiforeg_nval14B[31:0] ;
        mw_spi_bus_fiforeg_cval15B[31:0]  =  mw_spi_bus_fiforeg_nval15B[31:0] ;
        mw_spi_bus_fiforeg_cval16B[31:0]  =  mw_spi_bus_fiforeg_nval16B[31:0] ;
        mw_spi_bus_fiforeg_cval17B[31:0]  =  mw_spi_bus_fiforeg_nval17B[31:0] ;
        mw_spi_bus_fiforeg_cval18B[31:0]  =  mw_spi_bus_fiforeg_nval18B[31:0] ;
        mw_spi_bus_fiforeg_cval19B[31:0]  =  mw_spi_bus_fiforeg_nval19B[31:0] ;
        mw_spi_bus_fiforeg_cval20B[31:0]  =  mw_spi_bus_fiforeg_nval20B[31:0] ;
        mw_spi_bus_fiforeg_cval21B[31:0]  =  mw_spi_bus_fiforeg_nval21B[31:0] ;
        mw_spi_bus_fiforeg_cval22B[31:0]  =  mw_spi_bus_fiforeg_nval22B[31:0] ;
        mw_spi_bus_fiforeg_cval23B[31:0]  =  mw_spi_bus_fiforeg_nval23B[31:0] ;
        mw_spi_bus_fiforeg_cval24B[31:0]  =  mw_spi_bus_fiforeg_nval24B[31:0] ;
        mw_spi_bus_fiforeg_cval25B[31:0]  =  mw_spi_bus_fiforeg_nval25B[31:0] ;
        mw_spi_bus_fiforeg_cval26B[31:0]  =  mw_spi_bus_fiforeg_nval26B[31:0] ;
        mw_spi_bus_fiforeg_cval27B[31:0]  =  mw_spi_bus_fiforeg_nval27B[31:0] ;
        mw_spi_bus_fiforeg_cval28B[31:0]  =  mw_spi_bus_fiforeg_nval28B[31:0] ;
        mw_spi_bus_fiforeg_cval29B[31:0]  =  mw_spi_bus_fiforeg_nval29B[31:0] ;
        mw_spi_bus_fiforeg_cval30B[31:0]  =  mw_spi_bus_fiforeg_nval30B[31:0] ;
        mw_spi_bus_fiforeg_cval31B[31:0]  =  mw_spi_bus_fiforeg_nval31B[31:0] ;
        mw_spi_bus_fiforeg_cval32B[31:0]  =  mw_spi_bus_fiforeg_nval32B[31:0] ;
      end
  end

always @( posedge clkC )
  begin : spi_bus_fifomove_procC
    if (def_value_1C)
      begin
        mw_spi_bus_fiforeg_cval0C[31:0]  =  mw_spi_bus_fiforeg_nval0C[31:0] ;
        mw_spi_bus_fiforeg_cval1C[31:0]  =  mw_spi_bus_fiforeg_nval1C[31:0] ;
        mw_spi_bus_fiforeg_cval2C[31:0]  =  mw_spi_bus_fiforeg_nval2C[31:0] ;
        mw_spi_bus_fiforeg_cval3C[31:0]  =  mw_spi_bus_fiforeg_nval3C[31:0] ;
        mw_spi_bus_fiforeg_cval4C[31:0]  =  mw_spi_bus_fiforeg_nval4C[31:0] ;
        mw_spi_bus_fiforeg_cval5C[31:0]  =  mw_spi_bus_fiforeg_nval5C[31:0] ;
        mw_spi_bus_fiforeg_cval6C[31:0]  =  mw_spi_bus_fiforeg_nval6C[31:0] ;
        mw_spi_bus_fiforeg_cval7C[31:0]  =  mw_spi_bus_fiforeg_nval7C[31:0] ;
        mw_spi_bus_fiforeg_cval8C[31:0]  =  mw_spi_bus_fiforeg_nval8C[31:0] ;
        mw_spi_bus_fiforeg_cval9C[31:0]  =  mw_spi_bus_fiforeg_nval9C[31:0] ;
        mw_spi_bus_fiforeg_cval10C[31:0]  =  mw_spi_bus_fiforeg_nval10C[31:0] ;
        mw_spi_bus_fiforeg_cval11C[31:0]  =  mw_spi_bus_fiforeg_nval11C[31:0] ;
        mw_spi_bus_fiforeg_cval12C[31:0]  =  mw_spi_bus_fiforeg_nval12C[31:0] ;
        mw_spi_bus_fiforeg_cval13C[31:0]  =  mw_spi_bus_fiforeg_nval13C[31:0] ;
        mw_spi_bus_fiforeg_cval14C[31:0]  =  mw_spi_bus_fiforeg_nval14C[31:0] ;
        mw_spi_bus_fiforeg_cval15C[31:0]  =  mw_spi_bus_fiforeg_nval15C[31:0] ;
        mw_spi_bus_fiforeg_cval16C[31:0]  =  mw_spi_bus_fiforeg_nval16C[31:0] ;
        mw_spi_bus_fiforeg_cval17C[31:0]  =  mw_spi_bus_fiforeg_nval17C[31:0] ;
        mw_spi_bus_fiforeg_cval18C[31:0]  =  mw_spi_bus_fiforeg_nval18C[31:0] ;
        mw_spi_bus_fiforeg_cval19C[31:0]  =  mw_spi_bus_fiforeg_nval19C[31:0] ;
        mw_spi_bus_fiforeg_cval20C[31:0]  =  mw_spi_bus_fiforeg_nval20C[31:0] ;
        mw_spi_bus_fiforeg_cval21C[31:0]  =  mw_spi_bus_fiforeg_nval21C[31:0] ;
        mw_spi_bus_fiforeg_cval22C[31:0]  =  mw_spi_bus_fiforeg_nval22C[31:0] ;
        mw_spi_bus_fiforeg_cval23C[31:0]  =  mw_spi_bus_fiforeg_nval23C[31:0] ;
        mw_spi_bus_fiforeg_cval24C[31:0]  =  mw_spi_bus_fiforeg_nval24C[31:0] ;
        mw_spi_bus_fiforeg_cval25C[31:0]  =  mw_spi_bus_fiforeg_nval25C[31:0] ;
        mw_spi_bus_fiforeg_cval26C[31:0]  =  mw_spi_bus_fiforeg_nval26C[31:0] ;
        mw_spi_bus_fiforeg_cval27C[31:0]  =  mw_spi_bus_fiforeg_nval27C[31:0] ;
        mw_spi_bus_fiforeg_cval28C[31:0]  =  mw_spi_bus_fiforeg_nval28C[31:0] ;
        mw_spi_bus_fiforeg_cval29C[31:0]  =  mw_spi_bus_fiforeg_nval29C[31:0] ;
        mw_spi_bus_fiforeg_cval30C[31:0]  =  mw_spi_bus_fiforeg_nval30C[31:0] ;
        mw_spi_bus_fiforeg_cval31C[31:0]  =  mw_spi_bus_fiforeg_nval31C[31:0] ;
        mw_spi_bus_fiforeg_cval32C[31:0]  =  mw_spi_bus_fiforeg_nval32C[31:0] ;
      end
  end
assign mw_spi_bus_fiforeg_nval0[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==0) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval1[31:0]  : mw_spi_bus_fiforeg_cval0[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval1[31:0]  : mw_spi_bus_fiforeg_cval0[31:0] ;
assign mw_spi_bus_fiforeg_nval1[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==1) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval2[31:0]  : (mw_spi_bus_fifoaddr_cval==0) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval1[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval2[31:0]  : mw_spi_bus_fiforeg_cval1[31:0] ;
assign mw_spi_bus_fiforeg_nval2[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==2) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval3[31:0]  : (mw_spi_bus_fifoaddr_cval==1) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval2[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval3[31:0]  : mw_spi_bus_fiforeg_cval2[31:0] ;
assign mw_spi_bus_fiforeg_nval3[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==3) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval4[31:0]  : (mw_spi_bus_fifoaddr_cval==2) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval3[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval4[31:0]  : mw_spi_bus_fiforeg_cval3[31:0] ;
assign mw_spi_bus_fiforeg_nval4[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==4) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval5[31:0]  : (mw_spi_bus_fifoaddr_cval==3) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval4[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval5[31:0]  : mw_spi_bus_fiforeg_cval4[31:0] ;
assign mw_spi_bus_fiforeg_nval5[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==5) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval6[31:0]  : (mw_spi_bus_fifoaddr_cval==4) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval5[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval6[31:0]  : mw_spi_bus_fiforeg_cval5[31:0] ;
assign mw_spi_bus_fiforeg_nval6[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==6) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval7[31:0]  : (mw_spi_bus_fifoaddr_cval==5) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval6[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval7[31:0]  : mw_spi_bus_fiforeg_cval6[31:0] ;
assign mw_spi_bus_fiforeg_nval7[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==7) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval8[31:0]  : (mw_spi_bus_fifoaddr_cval==6) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval7[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval8[31:0]  : mw_spi_bus_fiforeg_cval7[31:0] ;
assign mw_spi_bus_fiforeg_nval8[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==8) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval9[31:0]  : (mw_spi_bus_fifoaddr_cval==7) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval8[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval9[31:0]  : mw_spi_bus_fiforeg_cval8[31:0] ;
assign mw_spi_bus_fiforeg_nval9[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==9) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval10[31:0]  : (mw_spi_bus_fifoaddr_cval==8) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval9[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval10[31:0]  : mw_spi_bus_fiforeg_cval9[31:0] ;
assign mw_spi_bus_fiforeg_nval10[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==10) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval11[31:0]  : (mw_spi_bus_fifoaddr_cval==9) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval10[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval11[31:0]  : mw_spi_bus_fiforeg_cval10[31:0] ;
assign mw_spi_bus_fiforeg_nval11[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==11) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval12[31:0]  : (mw_spi_bus_fifoaddr_cval==10) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval11[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval12[31:0]  : mw_spi_bus_fiforeg_cval11[31:0] ;
assign mw_spi_bus_fiforeg_nval12[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==12) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval13[31:0]  : (mw_spi_bus_fifoaddr_cval==11) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval12[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval13[31:0]  : mw_spi_bus_fiforeg_cval12[31:0] ;
assign mw_spi_bus_fiforeg_nval13[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==13) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval14[31:0]  : (mw_spi_bus_fifoaddr_cval==12) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval13[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval14[31:0]  : mw_spi_bus_fiforeg_cval13[31:0] ;
assign mw_spi_bus_fiforeg_nval14[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==14) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval15[31:0]  : (mw_spi_bus_fifoaddr_cval==13) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval14[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval15[31:0]  : mw_spi_bus_fiforeg_cval14[31:0] ;
assign mw_spi_bus_fiforeg_nval15[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==15) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval16[31:0]  : (mw_spi_bus_fifoaddr_cval==14) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval15[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval16[31:0]  : mw_spi_bus_fiforeg_cval15[31:0] ;
assign mw_spi_bus_fiforeg_nval16[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==16) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval17[31:0]  : (mw_spi_bus_fifoaddr_cval==15) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval16[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval17[31:0]  : mw_spi_bus_fiforeg_cval16[31:0] ;
assign mw_spi_bus_fiforeg_nval17[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==17) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval18[31:0]  : (mw_spi_bus_fifoaddr_cval==16) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval17[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval18[31:0]  : mw_spi_bus_fiforeg_cval17[31:0] ;
assign mw_spi_bus_fiforeg_nval18[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==18) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval19[31:0]  : (mw_spi_bus_fifoaddr_cval==17) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval18[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval19[31:0]  : mw_spi_bus_fiforeg_cval18[31:0] ;
assign mw_spi_bus_fiforeg_nval19[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==19) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval20[31:0]  : (mw_spi_bus_fifoaddr_cval==18) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval19[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval20[31:0]  : mw_spi_bus_fiforeg_cval19[31:0] ;
assign mw_spi_bus_fiforeg_nval20[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==20) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval21[31:0]  : (mw_spi_bus_fifoaddr_cval==19) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval20[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval21[31:0]  : mw_spi_bus_fiforeg_cval20[31:0] ;
assign mw_spi_bus_fiforeg_nval21[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==21) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval22[31:0]  : (mw_spi_bus_fifoaddr_cval==20) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval21[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval22[31:0]  : mw_spi_bus_fiforeg_cval21[31:0] ;
assign mw_spi_bus_fiforeg_nval22[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==22) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval23[31:0]  : (mw_spi_bus_fifoaddr_cval==21) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval22[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval23[31:0]  : mw_spi_bus_fiforeg_cval22[31:0] ;
assign mw_spi_bus_fiforeg_nval23[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==23) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval24[31:0]  : (mw_spi_bus_fifoaddr_cval==22) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval23[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval24[31:0]  : mw_spi_bus_fiforeg_cval23[31:0] ;
assign mw_spi_bus_fiforeg_nval24[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==24) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval25[31:0]  : (mw_spi_bus_fifoaddr_cval==23) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval24[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval25[31:0]  : mw_spi_bus_fiforeg_cval24[31:0] ;
assign mw_spi_bus_fiforeg_nval25[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==25) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval26[31:0]  : (mw_spi_bus_fifoaddr_cval==24) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval25[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval26[31:0]  : mw_spi_bus_fiforeg_cval25[31:0] ;
assign mw_spi_bus_fiforeg_nval26[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==26) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval27[31:0]  : (mw_spi_bus_fifoaddr_cval==25) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval26[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval27[31:0]  : mw_spi_bus_fiforeg_cval26[31:0] ;
assign mw_spi_bus_fiforeg_nval27[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==27) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval28[31:0]  : (mw_spi_bus_fifoaddr_cval==26) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval27[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval28[31:0]  : mw_spi_bus_fiforeg_cval27[31:0] ;
assign mw_spi_bus_fiforeg_nval28[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==28) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval29[31:0]  : (mw_spi_bus_fifoaddr_cval==27) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval28[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval29[31:0]  : mw_spi_bus_fiforeg_cval28[31:0] ;
assign mw_spi_bus_fiforeg_nval29[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==29) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval30[31:0]  : (mw_spi_bus_fifoaddr_cval==28) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval29[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval30[31:0]  : mw_spi_bus_fiforeg_cval29[31:0] ;
assign mw_spi_bus_fiforeg_nval30[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==30) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval31[31:0]  : (mw_spi_bus_fifoaddr_cval==29) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval30[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval31[31:0]  : mw_spi_bus_fiforeg_cval30[31:0] ;
assign mw_spi_bus_fiforeg_nval31[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? (mw_spi_bus_fifoaddr_cval==31) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval32[31:0]  : (mw_spi_bus_fifoaddr_cval==30) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval31[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval32[31:0]  : mw_spi_bus_fiforeg_cval31[31:0] ;
assign mw_spi_bus_fiforeg_nval32[31:0]  =  mw_spi_bus_fifotemp_wena ? mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval32[31:0]  : (mw_spi_bus_fifoaddr_cval==31) ? irqsucrec_signals : mw_spi_bus_fiforeg_cval32[31:0]  : mw_spi_bus_fifotemp_rena ? mw_spi_bus_fiforeg_cval32[31:0]  : mw_spi_bus_fiforeg_cval32[31:0] ;

majorityVoter #(.WIDTH(6)) mw_spi_bus_fifoaddr_cvalVoter (
    .inA(mw_spi_bus_fifoaddr_cvalA),
    .inB(mw_spi_bus_fifoaddr_cvalB),
    .inC(mw_spi_bus_fifoaddr_cvalC),
    .out(mw_spi_bus_fifoaddr_cval),
    .tmrErr(mw_spi_bus_fifoaddr_cvalTmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval0Voter (
    .inA(mw_spi_bus_fiforeg_cval0A),
    .inB(mw_spi_bus_fiforeg_cval0B),
    .inC(mw_spi_bus_fiforeg_cval0C),
    .out(mw_spi_bus_fiforeg_cval0),
    .tmrErr(mw_spi_bus_fiforeg_cval0TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval10Voter (
    .inA(mw_spi_bus_fiforeg_cval10A),
    .inB(mw_spi_bus_fiforeg_cval10B),
    .inC(mw_spi_bus_fiforeg_cval10C),
    .out(mw_spi_bus_fiforeg_cval10),
    .tmrErr(mw_spi_bus_fiforeg_cval10TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval11Voter (
    .inA(mw_spi_bus_fiforeg_cval11A),
    .inB(mw_spi_bus_fiforeg_cval11B),
    .inC(mw_spi_bus_fiforeg_cval11C),
    .out(mw_spi_bus_fiforeg_cval11),
    .tmrErr(mw_spi_bus_fiforeg_cval11TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval12Voter (
    .inA(mw_spi_bus_fiforeg_cval12A),
    .inB(mw_spi_bus_fiforeg_cval12B),
    .inC(mw_spi_bus_fiforeg_cval12C),
    .out(mw_spi_bus_fiforeg_cval12),
    .tmrErr(mw_spi_bus_fiforeg_cval12TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval13Voter (
    .inA(mw_spi_bus_fiforeg_cval13A),
    .inB(mw_spi_bus_fiforeg_cval13B),
    .inC(mw_spi_bus_fiforeg_cval13C),
    .out(mw_spi_bus_fiforeg_cval13),
    .tmrErr(mw_spi_bus_fiforeg_cval13TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval14Voter (
    .inA(mw_spi_bus_fiforeg_cval14A),
    .inB(mw_spi_bus_fiforeg_cval14B),
    .inC(mw_spi_bus_fiforeg_cval14C),
    .out(mw_spi_bus_fiforeg_cval14),
    .tmrErr(mw_spi_bus_fiforeg_cval14TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval15Voter (
    .inA(mw_spi_bus_fiforeg_cval15A),
    .inB(mw_spi_bus_fiforeg_cval15B),
    .inC(mw_spi_bus_fiforeg_cval15C),
    .out(mw_spi_bus_fiforeg_cval15),
    .tmrErr(mw_spi_bus_fiforeg_cval15TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval16Voter (
    .inA(mw_spi_bus_fiforeg_cval16A),
    .inB(mw_spi_bus_fiforeg_cval16B),
    .inC(mw_spi_bus_fiforeg_cval16C),
    .out(mw_spi_bus_fiforeg_cval16),
    .tmrErr(mw_spi_bus_fiforeg_cval16TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval17Voter (
    .inA(mw_spi_bus_fiforeg_cval17A),
    .inB(mw_spi_bus_fiforeg_cval17B),
    .inC(mw_spi_bus_fiforeg_cval17C),
    .out(mw_spi_bus_fiforeg_cval17),
    .tmrErr(mw_spi_bus_fiforeg_cval17TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval18Voter (
    .inA(mw_spi_bus_fiforeg_cval18A),
    .inB(mw_spi_bus_fiforeg_cval18B),
    .inC(mw_spi_bus_fiforeg_cval18C),
    .out(mw_spi_bus_fiforeg_cval18),
    .tmrErr(mw_spi_bus_fiforeg_cval18TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval19Voter (
    .inA(mw_spi_bus_fiforeg_cval19A),
    .inB(mw_spi_bus_fiforeg_cval19B),
    .inC(mw_spi_bus_fiforeg_cval19C),
    .out(mw_spi_bus_fiforeg_cval19),
    .tmrErr(mw_spi_bus_fiforeg_cval19TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval1Voter (
    .inA(mw_spi_bus_fiforeg_cval1A),
    .inB(mw_spi_bus_fiforeg_cval1B),
    .inC(mw_spi_bus_fiforeg_cval1C),
    .out(mw_spi_bus_fiforeg_cval1),
    .tmrErr(mw_spi_bus_fiforeg_cval1TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval20Voter (
    .inA(mw_spi_bus_fiforeg_cval20A),
    .inB(mw_spi_bus_fiforeg_cval20B),
    .inC(mw_spi_bus_fiforeg_cval20C),
    .out(mw_spi_bus_fiforeg_cval20),
    .tmrErr(mw_spi_bus_fiforeg_cval20TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval21Voter (
    .inA(mw_spi_bus_fiforeg_cval21A),
    .inB(mw_spi_bus_fiforeg_cval21B),
    .inC(mw_spi_bus_fiforeg_cval21C),
    .out(mw_spi_bus_fiforeg_cval21),
    .tmrErr(mw_spi_bus_fiforeg_cval21TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval22Voter (
    .inA(mw_spi_bus_fiforeg_cval22A),
    .inB(mw_spi_bus_fiforeg_cval22B),
    .inC(mw_spi_bus_fiforeg_cval22C),
    .out(mw_spi_bus_fiforeg_cval22),
    .tmrErr(mw_spi_bus_fiforeg_cval22TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval23Voter (
    .inA(mw_spi_bus_fiforeg_cval23A),
    .inB(mw_spi_bus_fiforeg_cval23B),
    .inC(mw_spi_bus_fiforeg_cval23C),
    .out(mw_spi_bus_fiforeg_cval23),
    .tmrErr(mw_spi_bus_fiforeg_cval23TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval24Voter (
    .inA(mw_spi_bus_fiforeg_cval24A),
    .inB(mw_spi_bus_fiforeg_cval24B),
    .inC(mw_spi_bus_fiforeg_cval24C),
    .out(mw_spi_bus_fiforeg_cval24),
    .tmrErr(mw_spi_bus_fiforeg_cval24TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval25Voter (
    .inA(mw_spi_bus_fiforeg_cval25A),
    .inB(mw_spi_bus_fiforeg_cval25B),
    .inC(mw_spi_bus_fiforeg_cval25C),
    .out(mw_spi_bus_fiforeg_cval25),
    .tmrErr(mw_spi_bus_fiforeg_cval25TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval26Voter (
    .inA(mw_spi_bus_fiforeg_cval26A),
    .inB(mw_spi_bus_fiforeg_cval26B),
    .inC(mw_spi_bus_fiforeg_cval26C),
    .out(mw_spi_bus_fiforeg_cval26),
    .tmrErr(mw_spi_bus_fiforeg_cval26TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval27Voter (
    .inA(mw_spi_bus_fiforeg_cval27A),
    .inB(mw_spi_bus_fiforeg_cval27B),
    .inC(mw_spi_bus_fiforeg_cval27C),
    .out(mw_spi_bus_fiforeg_cval27),
    .tmrErr(mw_spi_bus_fiforeg_cval27TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval28Voter (
    .inA(mw_spi_bus_fiforeg_cval28A),
    .inB(mw_spi_bus_fiforeg_cval28B),
    .inC(mw_spi_bus_fiforeg_cval28C),
    .out(mw_spi_bus_fiforeg_cval28),
    .tmrErr(mw_spi_bus_fiforeg_cval28TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval29Voter (
    .inA(mw_spi_bus_fiforeg_cval29A),
    .inB(mw_spi_bus_fiforeg_cval29B),
    .inC(mw_spi_bus_fiforeg_cval29C),
    .out(mw_spi_bus_fiforeg_cval29),
    .tmrErr(mw_spi_bus_fiforeg_cval29TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval2Voter (
    .inA(mw_spi_bus_fiforeg_cval2A),
    .inB(mw_spi_bus_fiforeg_cval2B),
    .inC(mw_spi_bus_fiforeg_cval2C),
    .out(mw_spi_bus_fiforeg_cval2),
    .tmrErr(mw_spi_bus_fiforeg_cval2TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval30Voter (
    .inA(mw_spi_bus_fiforeg_cval30A),
    .inB(mw_spi_bus_fiforeg_cval30B),
    .inC(mw_spi_bus_fiforeg_cval30C),
    .out(mw_spi_bus_fiforeg_cval30),
    .tmrErr(mw_spi_bus_fiforeg_cval30TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval31Voter (
    .inA(mw_spi_bus_fiforeg_cval31A),
    .inB(mw_spi_bus_fiforeg_cval31B),
    .inC(mw_spi_bus_fiforeg_cval31C),
    .out(mw_spi_bus_fiforeg_cval31),
    .tmrErr(mw_spi_bus_fiforeg_cval31TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval32Voter (
    .inA(mw_spi_bus_fiforeg_cval32A),
    .inB(mw_spi_bus_fiforeg_cval32B),
    .inC(mw_spi_bus_fiforeg_cval32C),
    .out(mw_spi_bus_fiforeg_cval32),
    .tmrErr(mw_spi_bus_fiforeg_cval32TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval3Voter (
    .inA(mw_spi_bus_fiforeg_cval3A),
    .inB(mw_spi_bus_fiforeg_cval3B),
    .inC(mw_spi_bus_fiforeg_cval3C),
    .out(mw_spi_bus_fiforeg_cval3),
    .tmrErr(mw_spi_bus_fiforeg_cval3TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval4Voter (
    .inA(mw_spi_bus_fiforeg_cval4A),
    .inB(mw_spi_bus_fiforeg_cval4B),
    .inC(mw_spi_bus_fiforeg_cval4C),
    .out(mw_spi_bus_fiforeg_cval4),
    .tmrErr(mw_spi_bus_fiforeg_cval4TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval5Voter (
    .inA(mw_spi_bus_fiforeg_cval5A),
    .inB(mw_spi_bus_fiforeg_cval5B),
    .inC(mw_spi_bus_fiforeg_cval5C),
    .out(mw_spi_bus_fiforeg_cval5),
    .tmrErr(mw_spi_bus_fiforeg_cval5TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval6Voter (
    .inA(mw_spi_bus_fiforeg_cval6A),
    .inB(mw_spi_bus_fiforeg_cval6B),
    .inC(mw_spi_bus_fiforeg_cval6C),
    .out(mw_spi_bus_fiforeg_cval6),
    .tmrErr(mw_spi_bus_fiforeg_cval6TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval7Voter (
    .inA(mw_spi_bus_fiforeg_cval7A),
    .inB(mw_spi_bus_fiforeg_cval7B),
    .inC(mw_spi_bus_fiforeg_cval7C),
    .out(mw_spi_bus_fiforeg_cval7),
    .tmrErr(mw_spi_bus_fiforeg_cval7TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval8Voter (
    .inA(mw_spi_bus_fiforeg_cval8A),
    .inB(mw_spi_bus_fiforeg_cval8B),
    .inC(mw_spi_bus_fiforeg_cval8C),
    .out(mw_spi_bus_fiforeg_cval8),
    .tmrErr(mw_spi_bus_fiforeg_cval8TmrError)
    );

majorityVoter #(.WIDTH(32)) mw_spi_bus_fiforeg_cval9Voter (
    .inA(mw_spi_bus_fiforeg_cval9A),
    .inB(mw_spi_bus_fiforeg_cval9B),
    .inC(mw_spi_bus_fiforeg_cval9C),
    .out(mw_spi_bus_fiforeg_cval9),
    .tmrErr(mw_spi_bus_fiforeg_cval9TmrError)
    );

majorityVoter wenaVoter (
    .inA(wenaA),
    .inB(wenaB),
    .inC(wenaC),
    .out(wena),
    .tmrErr(wenaTmrError)
    );

fanout clkFanout (
    .in(clk),
    .outA(clkA),
    .outB(clkB),
    .outC(clkC)
    );

fanout def_value_1Fanout (
    .in(def_value_1),
    .outA(def_value_1A),
    .outB(def_value_1B),
    .outC(def_value_1C)
    );

fanout ireqsucrecFanout (
    .in(ireqsucrec),
    .outA(ireqsucrecA),
    .outB(ireqsucrecB),
    .outC(ireqsucrecC)
    );

fanout #(.WIDTH(6)) mw_spi_bus_fifoaddr_nvalFanout (
    .in(mw_spi_bus_fifoaddr_nval),
    .outA(mw_spi_bus_fifoaddr_nvalA),
    .outB(mw_spi_bus_fifoaddr_nvalB),
    .outC(mw_spi_bus_fifoaddr_nvalC)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval0Fanout (
    .in(mw_spi_bus_fiforeg_nval0),
    .outA(mw_spi_bus_fiforeg_nval0A),
    .outB(mw_spi_bus_fiforeg_nval0B),
    .outC(mw_spi_bus_fiforeg_nval0C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval10Fanout (
    .in(mw_spi_bus_fiforeg_nval10),
    .outA(mw_spi_bus_fiforeg_nval10A),
    .outB(mw_spi_bus_fiforeg_nval10B),
    .outC(mw_spi_bus_fiforeg_nval10C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval11Fanout (
    .in(mw_spi_bus_fiforeg_nval11),
    .outA(mw_spi_bus_fiforeg_nval11A),
    .outB(mw_spi_bus_fiforeg_nval11B),
    .outC(mw_spi_bus_fiforeg_nval11C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval12Fanout (
    .in(mw_spi_bus_fiforeg_nval12),
    .outA(mw_spi_bus_fiforeg_nval12A),
    .outB(mw_spi_bus_fiforeg_nval12B),
    .outC(mw_spi_bus_fiforeg_nval12C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval13Fanout (
    .in(mw_spi_bus_fiforeg_nval13),
    .outA(mw_spi_bus_fiforeg_nval13A),
    .outB(mw_spi_bus_fiforeg_nval13B),
    .outC(mw_spi_bus_fiforeg_nval13C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval14Fanout (
    .in(mw_spi_bus_fiforeg_nval14),
    .outA(mw_spi_bus_fiforeg_nval14A),
    .outB(mw_spi_bus_fiforeg_nval14B),
    .outC(mw_spi_bus_fiforeg_nval14C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval15Fanout (
    .in(mw_spi_bus_fiforeg_nval15),
    .outA(mw_spi_bus_fiforeg_nval15A),
    .outB(mw_spi_bus_fiforeg_nval15B),
    .outC(mw_spi_bus_fiforeg_nval15C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval16Fanout (
    .in(mw_spi_bus_fiforeg_nval16),
    .outA(mw_spi_bus_fiforeg_nval16A),
    .outB(mw_spi_bus_fiforeg_nval16B),
    .outC(mw_spi_bus_fiforeg_nval16C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval17Fanout (
    .in(mw_spi_bus_fiforeg_nval17),
    .outA(mw_spi_bus_fiforeg_nval17A),
    .outB(mw_spi_bus_fiforeg_nval17B),
    .outC(mw_spi_bus_fiforeg_nval17C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval18Fanout (
    .in(mw_spi_bus_fiforeg_nval18),
    .outA(mw_spi_bus_fiforeg_nval18A),
    .outB(mw_spi_bus_fiforeg_nval18B),
    .outC(mw_spi_bus_fiforeg_nval18C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval19Fanout (
    .in(mw_spi_bus_fiforeg_nval19),
    .outA(mw_spi_bus_fiforeg_nval19A),
    .outB(mw_spi_bus_fiforeg_nval19B),
    .outC(mw_spi_bus_fiforeg_nval19C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval1Fanout (
    .in(mw_spi_bus_fiforeg_nval1),
    .outA(mw_spi_bus_fiforeg_nval1A),
    .outB(mw_spi_bus_fiforeg_nval1B),
    .outC(mw_spi_bus_fiforeg_nval1C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval20Fanout (
    .in(mw_spi_bus_fiforeg_nval20),
    .outA(mw_spi_bus_fiforeg_nval20A),
    .outB(mw_spi_bus_fiforeg_nval20B),
    .outC(mw_spi_bus_fiforeg_nval20C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval21Fanout (
    .in(mw_spi_bus_fiforeg_nval21),
    .outA(mw_spi_bus_fiforeg_nval21A),
    .outB(mw_spi_bus_fiforeg_nval21B),
    .outC(mw_spi_bus_fiforeg_nval21C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval22Fanout (
    .in(mw_spi_bus_fiforeg_nval22),
    .outA(mw_spi_bus_fiforeg_nval22A),
    .outB(mw_spi_bus_fiforeg_nval22B),
    .outC(mw_spi_bus_fiforeg_nval22C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval23Fanout (
    .in(mw_spi_bus_fiforeg_nval23),
    .outA(mw_spi_bus_fiforeg_nval23A),
    .outB(mw_spi_bus_fiforeg_nval23B),
    .outC(mw_spi_bus_fiforeg_nval23C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval24Fanout (
    .in(mw_spi_bus_fiforeg_nval24),
    .outA(mw_spi_bus_fiforeg_nval24A),
    .outB(mw_spi_bus_fiforeg_nval24B),
    .outC(mw_spi_bus_fiforeg_nval24C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval25Fanout (
    .in(mw_spi_bus_fiforeg_nval25),
    .outA(mw_spi_bus_fiforeg_nval25A),
    .outB(mw_spi_bus_fiforeg_nval25B),
    .outC(mw_spi_bus_fiforeg_nval25C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval26Fanout (
    .in(mw_spi_bus_fiforeg_nval26),
    .outA(mw_spi_bus_fiforeg_nval26A),
    .outB(mw_spi_bus_fiforeg_nval26B),
    .outC(mw_spi_bus_fiforeg_nval26C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval27Fanout (
    .in(mw_spi_bus_fiforeg_nval27),
    .outA(mw_spi_bus_fiforeg_nval27A),
    .outB(mw_spi_bus_fiforeg_nval27B),
    .outC(mw_spi_bus_fiforeg_nval27C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval28Fanout (
    .in(mw_spi_bus_fiforeg_nval28),
    .outA(mw_spi_bus_fiforeg_nval28A),
    .outB(mw_spi_bus_fiforeg_nval28B),
    .outC(mw_spi_bus_fiforeg_nval28C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval29Fanout (
    .in(mw_spi_bus_fiforeg_nval29),
    .outA(mw_spi_bus_fiforeg_nval29A),
    .outB(mw_spi_bus_fiforeg_nval29B),
    .outC(mw_spi_bus_fiforeg_nval29C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval2Fanout (
    .in(mw_spi_bus_fiforeg_nval2),
    .outA(mw_spi_bus_fiforeg_nval2A),
    .outB(mw_spi_bus_fiforeg_nval2B),
    .outC(mw_spi_bus_fiforeg_nval2C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval30Fanout (
    .in(mw_spi_bus_fiforeg_nval30),
    .outA(mw_spi_bus_fiforeg_nval30A),
    .outB(mw_spi_bus_fiforeg_nval30B),
    .outC(mw_spi_bus_fiforeg_nval30C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval31Fanout (
    .in(mw_spi_bus_fiforeg_nval31),
    .outA(mw_spi_bus_fiforeg_nval31A),
    .outB(mw_spi_bus_fiforeg_nval31B),
    .outC(mw_spi_bus_fiforeg_nval31C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval32Fanout (
    .in(mw_spi_bus_fiforeg_nval32),
    .outA(mw_spi_bus_fiforeg_nval32A),
    .outB(mw_spi_bus_fiforeg_nval32B),
    .outC(mw_spi_bus_fiforeg_nval32C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval3Fanout (
    .in(mw_spi_bus_fiforeg_nval3),
    .outA(mw_spi_bus_fiforeg_nval3A),
    .outB(mw_spi_bus_fiforeg_nval3B),
    .outC(mw_spi_bus_fiforeg_nval3C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval4Fanout (
    .in(mw_spi_bus_fiforeg_nval4),
    .outA(mw_spi_bus_fiforeg_nval4A),
    .outB(mw_spi_bus_fiforeg_nval4B),
    .outC(mw_spi_bus_fiforeg_nval4C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval5Fanout (
    .in(mw_spi_bus_fiforeg_nval5),
    .outA(mw_spi_bus_fiforeg_nval5A),
    .outB(mw_spi_bus_fiforeg_nval5B),
    .outC(mw_spi_bus_fiforeg_nval5C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval6Fanout (
    .in(mw_spi_bus_fiforeg_nval6),
    .outA(mw_spi_bus_fiforeg_nval6A),
    .outB(mw_spi_bus_fiforeg_nval6B),
    .outC(mw_spi_bus_fiforeg_nval6C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval7Fanout (
    .in(mw_spi_bus_fiforeg_nval7),
    .outA(mw_spi_bus_fiforeg_nval7A),
    .outB(mw_spi_bus_fiforeg_nval7B),
    .outC(mw_spi_bus_fiforeg_nval7C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval8Fanout (
    .in(mw_spi_bus_fiforeg_nval8),
    .outA(mw_spi_bus_fiforeg_nval8A),
    .outB(mw_spi_bus_fiforeg_nval8B),
    .outC(mw_spi_bus_fiforeg_nval8C)
    );

fanout #(.WIDTH(32)) mw_spi_bus_fiforeg_nval9Fanout (
    .in(mw_spi_bus_fiforeg_nval9),
    .outA(mw_spi_bus_fiforeg_nval9A),
    .outB(mw_spi_bus_fiforeg_nval9B),
    .outC(mw_spi_bus_fiforeg_nval9C)
    );

fanout rstFanout (
    .in(rst),
    .outA(rstA),
    .outB(rstB),
    .outC(rstC)
    );
endmodule

