set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet clk_out_n]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet clk_out_n]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet clk_out_p]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet clk_out_p]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet shift_clk]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet shift_clk]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 10.000 [get_ports -no_traverse -quiet shift_clk]
set_property -quiet IS_IP_OOC_CELL TRUE [get_cells -of [get_ports -no_traverse -quiet clk_40]]
