#make_diff_pair_ports AUX[1] AUX_N[1]
#make_diff_pair_ports AUX[2] AUX_N[2]
#make_diff_pair_ports AUX[3] AUX_N[3]
#make_diff_pair_ports CLK200MHZ CLK200MHZ_N
#make_diff_pair_ports ELINK_CLK ELINK_CLK_N
#make_diff_pair_ports ELINK_RX ELINK_RX_N
#make_diff_pair_ports ELINK_TX ELINK_TX_N
#set_property DCI_CASCADE {} [get_iobanks 34]

















set_property PACKAGE_PIN V18 [get_ports {FPGA_TX[32]}]
set_property PACKAGE_PIN V20 [get_ports {FPGA_TX[31]}]
set_property PACKAGE_PIN AB10 [get_ports {FPGA_TX[30]}]
set_property PACKAGE_PIN W20 [get_ports {FPGA_TX[29]}]
set_property PACKAGE_PIN T21 [get_ports {FPGA_TX[28]}]
set_property PACKAGE_PIN T20 [get_ports {FPGA_TX[27]}]
set_property PACKAGE_PIN W10 [get_ports {FPGA_TX[26]}]
set_property PACKAGE_PIN Y11 [get_ports {FPGA_TX[25]}]


set_property PACKAGE_PIN M13 [get_ports {FPGA_TX[24]}]
set_property PACKAGE_PIN AA21 [get_ports {FPGA_TX[23]}]
set_property PACKAGE_PIN U15 [get_ports {FPGA_TX[22]}]
set_property PACKAGE_PIN W16 [get_ports {FPGA_TX[21]}]
set_property PACKAGE_PIN J14 [get_ports {FPGA_TX[20]}]
set_property PACKAGE_PIN J15 [get_ports {FPGA_TX[19]}]
set_property PACKAGE_PIN G13 [get_ports {FPGA_TX[18]}]
set_property PACKAGE_PIN L18 [get_ports {FPGA_TX[17]}]


set_property PACKAGE_PIN M20 [get_ports {FPGA_TX[16]}]
set_property PACKAGE_PIN K18 [get_ports {FPGA_TX[15]}]
set_property PACKAGE_PIN H19 [get_ports {FPGA_TX[14]}]
set_property PACKAGE_PIN G15 [get_ports {FPGA_TX[13]}]
set_property PACKAGE_PIN D20 [get_ports {FPGA_TX[12]}]
set_property PACKAGE_PIN K22 [get_ports {FPGA_TX[11]}]
set_property PACKAGE_PIN H20 [get_ports {FPGA_TX[10]}]
set_property PACKAGE_PIN D22 [get_ports {FPGA_TX[9]}]

set_property PACKAGE_PIN E18 [get_ports {FPGA_TX[8]}]
set_property PACKAGE_PIN C18 [get_ports {FPGA_TX[7]}]
set_property PACKAGE_PIN B17 [get_ports {FPGA_TX[6]}]
set_property PACKAGE_PIN F21 [get_ports {FPGA_TX[5]}]
set_property PACKAGE_PIN C22 [get_ports {FPGA_TX[4]}]
set_property PACKAGE_PIN B20 [get_ports {FPGA_TX[3]}]
set_property PACKAGE_PIN B16 [get_ports {FPGA_TX[2]}]
set_property PACKAGE_PIN E16 [get_ports {FPGA_TX[1]}]











set_property PACKAGE_PIN D16 [get_ports {FPGA_RX[1]}]
set_property PACKAGE_PIN C17 [get_ports {FPGA_RX[2]}]
set_property PACKAGE_PIN A20 [get_ports {FPGA_RX[3]}]
set_property PACKAGE_PIN B22 [get_ports {FPGA_RX[4]}]
set_property PACKAGE_PIN A14 [get_ports {FPGA_RX[5]}]
set_property PACKAGE_PIN B18 [get_ports {FPGA_RX[6]}]
set_property PACKAGE_PIN C19 [get_ports {FPGA_RX[7]}]
set_property PACKAGE_PIN E21 [get_ports {FPGA_RX[8]}]
set_property PACKAGE_PIN G21 [get_ports {FPGA_RX[9]}]
set_property PACKAGE_PIN H22 [get_ports {FPGA_RX[10]}]
set_property PACKAGE_PIN C15 [get_ports {FPGA_RX[11]}]


set_property PACKAGE_PIN C20 [get_ports {FPGA_RX[12]}]
set_property PACKAGE_PIN G16 [get_ports {FPGA_RX[13]}]
set_property PACKAGE_PIN H18 [get_ports {FPGA_RX[14]}]
set_property PACKAGE_PIN M21 [get_ports {FPGA_RX[15]}]
set_property PACKAGE_PIN N19 [get_ports {FPGA_RX[16]}]

set_property PACKAGE_PIN E17 [get_ports {FPGA_RX[17]}]
set_property PACKAGE_PIN H13 [get_ports {FPGA_RX[18]}]
set_property PACKAGE_PIN H15 [get_ports {FPGA_RX[19]}]
set_property PACKAGE_PIN V13 [get_ports {FPGA_RX[20]}]
set_property PACKAGE_PIN W15 [get_ports {FPGA_RX[21]}]
set_property PACKAGE_PIN V15 [get_ports {FPGA_RX[22]}]
set_property PACKAGE_PIN N14 [get_ports {FPGA_RX[23]}]
set_property PACKAGE_PIN L13 [get_ports {FPGA_RX[24]}]

set_property PACKAGE_PIN Y12 [get_ports {FPGA_RX[25]}]
set_property PACKAGE_PIN AA19 [get_ports {FPGA_RX[26]}]
set_property PACKAGE_PIN Y17 [get_ports {FPGA_RX[27]}]
set_property PACKAGE_PIN U21 [get_ports {FPGA_RX[28]}]
set_property PACKAGE_PIN R14 [get_ports {FPGA_RX[29]}]
set_property PACKAGE_PIN AA9 [get_ports {FPGA_RX[30]}]
set_property PACKAGE_PIN U20 [get_ports {FPGA_RX[31]}]
set_property PACKAGE_PIN Y18 [get_ports {FPGA_RX[32]}]












set_property PACKAGE_PIN D19 [get_ports {C_CSF[1]}]
set_property PACKAGE_PIN B15 [get_ports {C_CSF[2]}]
set_property PACKAGE_PIN A16 [get_ports {C_CSF[3]}]
set_property PACKAGE_PIN F20 [get_ports {C_CSF[4]}]
set_property PACKAGE_PIN M17 [get_ports {C_CSF[5]}]
set_property PACKAGE_PIN B21 [get_ports {C_CSF[6]}]
set_property PACKAGE_PIN E22 [get_ports {C_CSF[7]}]
set_property PACKAGE_PIN F18 [get_ports {C_CSF[8]}]
set_property PACKAGE_PIN A19 [get_ports {C_CSF[9]}]
set_property PACKAGE_PIN G20 [get_ports {C_CSF[10]}]
set_property PACKAGE_PIN K21 [get_ports {C_CSF[11]}]
set_property PACKAGE_PIN N22 [get_ports {C_CSF[12]}]
set_property PACKAGE_PIN K19 [get_ports {C_CSF[13]}]
set_property PACKAGE_PIN J19 [get_ports {C_CSF[14]}]
set_property PACKAGE_PIN J21 [get_ports {C_CSF[15]}]
set_property PACKAGE_PIN N20 [get_ports {C_CSF[16]}]
set_property PACKAGE_PIN M18 [get_ports {C_CSF[17]}]
set_property PACKAGE_PIN V14 [get_ports {C_CSF[18]}]
set_property PACKAGE_PIN T14 [get_ports {C_CSF[19]}]
set_property PACKAGE_PIN H14 [get_ports {C_CSF[20]}]
set_property PACKAGE_PIN K14 [get_ports {C_CSF[21]}]
set_property PACKAGE_PIN W17 [get_ports {C_CSF[22]}]
set_property PACKAGE_PIN AB22 [get_ports {C_CSF[23]}]
set_property PACKAGE_PIN AB20 [get_ports {C_CSF[24]}]
set_property PACKAGE_PIN AB18 [get_ports {C_CSF[25]}]
set_property PACKAGE_PIN V10 [get_ports {C_CSF[26]}]
set_property PACKAGE_PIN AA10 [get_ports {C_CSF[27]}]
set_property PACKAGE_PIN W21 [get_ports {C_CSF[28]}]
set_property PACKAGE_PIN Y22 [get_ports {C_CSF[29]}]
set_property PACKAGE_PIN Y19 [get_ports {C_CSF[30]}]
set_property PACKAGE_PIN U22 [get_ports {C_CSF[31]}]
set_property PACKAGE_PIN V19 [get_ports {C_CSF[32]}]








set_property PACKAGE_PIN E19 [get_ports {M_CSF[1]}]
set_property PACKAGE_PIN F19 [get_ports {M_CSF[2]}]
set_property PACKAGE_PIN A15 [get_ports {M_CSF[3]}]
set_property PACKAGE_PIN D17 [get_ports {M_CSF[4]}]
set_property PACKAGE_PIN J16 [get_ports {M_CSF[5]}]
set_property PACKAGE_PIN A21 [get_ports {M_CSF[6]}]
set_property PACKAGE_PIN D21 [get_ports {M_CSF[7]}]
set_property PACKAGE_PIN G22 [get_ports {M_CSF[8]}]
set_property PACKAGE_PIN A18 [get_ports {M_CSF[9]}]
set_property PACKAGE_PIN A13 [get_ports {M_CSF[10]}]
set_property PACKAGE_PIN J22 [get_ports {M_CSF[11]}]
set_property PACKAGE_PIN M22 [get_ports {M_CSF[12]}]
set_property PACKAGE_PIN H17 [get_ports {M_CSF[13]}]
set_property PACKAGE_PIN L21 [get_ports {M_CSF[14]}]
set_property PACKAGE_PIN J20 [get_ports {M_CSF[15]}]
set_property PACKAGE_PIN C14 [get_ports {M_CSF[16]}]
set_property PACKAGE_PIN N18 [get_ports {M_CSF[17]}]
set_property PACKAGE_PIN W11 [get_ports {M_CSF[18]}]
set_property PACKAGE_PIN T15 [get_ports {M_CSF[19]}]
set_property PACKAGE_PIN V17 [get_ports {M_CSF[20]}]
set_property PACKAGE_PIN K13 [get_ports {M_CSF[21]}]
set_property PACKAGE_PIN F16 [get_ports {M_CSF[22]}]
set_property PACKAGE_PIN AB21 [get_ports {M_CSF[23]}]
set_property PACKAGE_PIN AA20 [get_ports {M_CSF[24]}]
set_property PACKAGE_PIN AA18 [get_ports {M_CSF[25]}]
set_property PACKAGE_PIN W22 [get_ports {M_CSF[26]}]
set_property PACKAGE_PIN AA11 [get_ports {M_CSF[27]}]
set_property PACKAGE_PIN N13 [get_ports {M_CSF[28]}]
set_property PACKAGE_PIN Y21 [get_ports {M_CSF[29]}]
set_property PACKAGE_PIN W19 [get_ports {M_CSF[30]}]
set_property PACKAGE_PIN V22 [get_ports {M_CSF[31]}]
set_property PACKAGE_PIN T18 [get_ports {M_CSF[32]}]



set_property PACKAGE_PIN E14 [get_ports {LED[1]}]
set_property PACKAGE_PIN E13 [get_ports {LED[2]}]
set_property PACKAGE_PIN D15 [get_ports {LED[3]}]
set_property PACKAGE_PIN D14 [get_ports {LED[4]}]
set_property PACKAGE_PIN C13 [get_ports {LED[5]}]
set_property PACKAGE_PIN B13 [get_ports {LED[6]}]
set_property PACKAGE_PIN W5 [get_ports LED_SOM]

set_property PACKAGE_PIN R19 [get_ports C_SCLK_F]
set_property PACKAGE_PIN P19 [get_ports C_SDI_F] //MOSI
set_property PACKAGE_PIN R18 [get_ports C_SDO_F] //MISO
set_property PACKAGE_PIN U18 [get_ports M_SCLK]
set_property PACKAGE_PIN U17 [get_ports M_SDI_F]//MOSI
set_property PACKAGE_PIN P14 [get_ports M_SDO_F]//MISO

set_property PACKAGE_PIN R4 [get_ports CLK200MHZ]
set_property PACKAGE_PIN T4 [get_ports CLK200MHZ_N]

set_property PACKAGE_PIN AB7 [get_ports ELINK_TX]
set_property PACKAGE_PIN AB6 [get_ports ELINK_TX_N]
set_property PACKAGE_PIN AA8 [get_ports ELINK_RX]
set_property PACKAGE_PIN AB8 [get_ports ELINK_RX_N]
set_property PACKAGE_PIN W9 [get_ports ELINK_CLK]
set_property PACKAGE_PIN Y9 [get_ports ELINK_CLK_N]

set_property PACKAGE_PIN N15 [get_ports AUX_4]
set_property PACKAGE_PIN P15 [get_ports {AUX[1]}]
set_property PACKAGE_PIN R16 [get_ports {AUX_N[1]}]
set_property PACKAGE_PIN P16 [get_ports {AUX[2]}]
set_property PACKAGE_PIN R17 [get_ports {AUX_N[2]}]
set_property PACKAGE_PIN N17 [get_ports {AUX[3]}]
set_property PACKAGE_PIN P17 [get_ports {AUX_N[3]}]

set_property IOSTANDARD LVDS_25 [get_ports CLK200MHZ]
set_property IOSTANDARD LVDS_25 [get_ports CLK200MHZ_N]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_CLK]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_CLK_N]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_RX]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_RX_N]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_TX]
set_property SLEW SLOW [get_ports ELINK_TX]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_TX_N]
set_property SLEW SLOW [get_ports ELINK_TX_N]

set_property IOSTANDARD TMDS_33 [get_ports {AUX[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {AUX[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {AUX[3]}]
set_property IOSTANDARD TMDS_33 [get_ports {AUX_N[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {AUX_N[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {AUX_N[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[10]}]
set_property DRIVE 12 [get_ports {C_CSF[10]}]
set_property SLEW SLOW [get_ports {C_CSF[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[11]}]
set_property DRIVE 12 [get_ports {C_CSF[11]}]
set_property SLEW SLOW [get_ports {C_CSF[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[12]}]
set_property DRIVE 12 [get_ports {C_CSF[12]}]
set_property SLEW SLOW [get_ports {C_CSF[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[13]}]
set_property DRIVE 12 [get_ports {C_CSF[13]}]
set_property SLEW SLOW [get_ports {C_CSF[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[14]}]
set_property DRIVE 12 [get_ports {C_CSF[14]}]
set_property SLEW SLOW [get_ports {C_CSF[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[15]}]
set_property DRIVE 12 [get_ports {C_CSF[15]}]
set_property SLEW SLOW [get_ports {C_CSF[15]}]
#set_property DIRECTION OUT [get_ports {C_CSF[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[16]}]
set_property DRIVE 12 [get_ports {C_CSF[16]}]
set_property SLEW SLOW [get_ports {C_CSF[16]}]
#set_property DIRECTION OUT [get_ports {C_CSF[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[17]}]
set_property DRIVE 12 [get_ports {C_CSF[17]}]
set_property SLEW SLOW [get_ports {C_CSF[17]}]
#set_property DIRECTION OUT [get_ports {C_CSF[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[18]}]
set_property DRIVE 12 [get_ports {C_CSF[18]}]
set_property SLEW SLOW [get_ports {C_CSF[18]}]
#set_property DIRECTION OUT [get_ports {C_CSF[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[19]}]
set_property DRIVE 12 [get_ports {C_CSF[19]}]
set_property SLEW SLOW [get_ports {C_CSF[19]}]
#set_property DIRECTION OUT [get_ports {C_CSF[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[1]}]
set_property DRIVE 12 [get_ports {C_CSF[1]}]
set_property SLEW SLOW [get_ports {C_CSF[1]}]
#set_property DIRECTION OUT [get_ports {C_CSF[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[20]}]
set_property DRIVE 12 [get_ports {C_CSF[20]}]
set_property SLEW SLOW [get_ports {C_CSF[20]}]
#set_property DIRECTION OUT [get_ports {C_CSF[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[21]}]
set_property DRIVE 12 [get_ports {C_CSF[21]}]
set_property SLEW SLOW [get_ports {C_CSF[21]}]
#set_property DIRECTION OUT [get_ports {C_CSF[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[22]}]
set_property DRIVE 12 [get_ports {C_CSF[22]}]
set_property SLEW SLOW [get_ports {C_CSF[22]}]
#set_property DIRECTION OUT [get_ports {C_CSF[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[23]}]
set_property DRIVE 12 [get_ports {C_CSF[23]}]
set_property SLEW SLOW [get_ports {C_CSF[23]}]
#set_property DIRECTION OUT [get_ports {C_CSF[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[24]}]
set_property DRIVE 12 [get_ports {C_CSF[24]}]
set_property SLEW SLOW [get_ports {C_CSF[24]}]
#set_property DIRECTION OUT [get_ports {C_CSF[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[25]}]
set_property DRIVE 12 [get_ports {C_CSF[25]}]
set_property SLEW SLOW [get_ports {C_CSF[25]}]
#set_property DIRECTION OUT [get_ports {C_CSF[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[26]}]
set_property DRIVE 12 [get_ports {C_CSF[26]}]
set_property SLEW SLOW [get_ports {C_CSF[26]}]
#set_property DIRECTION OUT [get_ports {C_CSF[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[27]}]
set_property DRIVE 12 [get_ports {C_CSF[27]}]
set_property SLEW SLOW [get_ports {C_CSF[27]}]
#set_property DIRECTION OUT [get_ports {C_CSF[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[28]}]
set_property DRIVE 12 [get_ports {C_CSF[28]}]
set_property SLEW SLOW [get_ports {C_CSF[28]}]
#set_property DIRECTION OUT [get_ports {C_CSF[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[29]}]
set_property DRIVE 12 [get_ports {C_CSF[29]}]
set_property SLEW SLOW [get_ports {C_CSF[29]}]
#set_property DIRECTION OUT [get_ports {C_CSF[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[2]}]
set_property DRIVE 12 [get_ports {C_CSF[2]}]
set_property SLEW SLOW [get_ports {C_CSF[2]}]
#set_property DIRECTION OUT [get_ports {C_CSF[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[30]}]
set_property DRIVE 12 [get_ports {C_CSF[30]}]
set_property SLEW SLOW [get_ports {C_CSF[30]}]
#set_property DIRECTION OUT [get_ports {C_CSF[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[31]}]
set_property DRIVE 12 [get_ports {C_CSF[31]}]
set_property SLEW SLOW [get_ports {C_CSF[31]}]
#set_property DIRECTION OUT [get_ports {C_CSF[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[32]}]
set_property DRIVE 12 [get_ports {C_CSF[32]}]
set_property SLEW SLOW [get_ports {C_CSF[32]}]
#set_property DIRECTION OUT [get_ports {C_CSF[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[3]}]
set_property DRIVE 12 [get_ports {C_CSF[3]}]
set_property SLEW SLOW [get_ports {C_CSF[3]}]
#set_property DIRECTION OUT [get_ports {C_CSF[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[4]}]
set_property DRIVE 12 [get_ports {C_CSF[4]}]
set_property SLEW SLOW [get_ports {C_CSF[4]}]
#set_property DIRECTION OUT [get_ports {C_CSF[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[5]}]
set_property DRIVE 12 [get_ports {C_CSF[5]}]
set_property SLEW SLOW [get_ports {C_CSF[5]}]
#set_property DIRECTION OUT [get_ports {C_CSF[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[6]}]
set_property DRIVE 12 [get_ports {C_CSF[6]}]
set_property SLEW SLOW [get_ports {C_CSF[6]}]
#set_property DIRECTION OUT [get_ports {C_CSF[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[7]}]
set_property DRIVE 12 [get_ports {C_CSF[7]}]
set_property SLEW SLOW [get_ports {C_CSF[7]}]
#set_property DIRECTION OUT [get_ports {C_CSF[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[8]}]
set_property DRIVE 12 [get_ports {C_CSF[8]}]
set_property SLEW SLOW [get_ports {C_CSF[8]}]
#set_property DIRECTION OUT [get_ports {C_CSF[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[9]}]
set_property DRIVE 12 [get_ports {C_CSF[9]}]
set_property SLEW SLOW [get_ports {C_CSF[9]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[10]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[11]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[12]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[13]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[14]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[15]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[16]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[17]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[18]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[19]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[1]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[20]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[21]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[22]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[23]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[24]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[25]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[26]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[27]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[28]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[29]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[2]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[30]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[31]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[32]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[3]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[4]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[5]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[6]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[7]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[8]}]
#set_property DIRECTION IN [get_ports {FPGA_RX[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[9]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[10]}]
set_property DRIVE 12 [get_ports {FPGA_TX[10]}]
set_property SLEW SLOW [get_ports {FPGA_TX[10]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[11]}]
set_property DRIVE 12 [get_ports {FPGA_TX[11]}]
set_property SLEW SLOW [get_ports {FPGA_TX[11]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[12]}]
set_property DRIVE 12 [get_ports {FPGA_TX[12]}]
set_property SLEW SLOW [get_ports {FPGA_TX[12]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[13]}]
set_property DRIVE 12 [get_ports {FPGA_TX[13]}]
set_property SLEW SLOW [get_ports {FPGA_TX[13]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[14]}]
set_property DRIVE 12 [get_ports {FPGA_TX[14]}]
set_property SLEW SLOW [get_ports {FPGA_TX[14]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[15]}]
set_property DRIVE 12 [get_ports {FPGA_TX[15]}]
set_property SLEW SLOW [get_ports {FPGA_TX[15]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[16]}]
set_property DRIVE 12 [get_ports {FPGA_TX[16]}]
set_property SLEW SLOW [get_ports {FPGA_TX[16]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[17]}]
set_property DRIVE 12 [get_ports {FPGA_TX[17]}]
set_property SLEW SLOW [get_ports {FPGA_TX[17]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[18]}]
set_property DRIVE 12 [get_ports {FPGA_TX[18]}]
set_property SLEW SLOW [get_ports {FPGA_TX[18]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[19]}]
set_property DRIVE 12 [get_ports {FPGA_TX[19]}]
set_property SLEW SLOW [get_ports {FPGA_TX[19]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[1]}]
set_property DRIVE 12 [get_ports {FPGA_TX[1]}]
set_property SLEW SLOW [get_ports {FPGA_TX[1]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[20]}]
set_property DRIVE 12 [get_ports {FPGA_TX[20]}]
set_property SLEW SLOW [get_ports {FPGA_TX[20]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[21]}]
set_property DRIVE 12 [get_ports {FPGA_TX[21]}]
set_property SLEW SLOW [get_ports {FPGA_TX[21]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[22]}]
set_property DRIVE 12 [get_ports {FPGA_TX[22]}]
set_property SLEW SLOW [get_ports {FPGA_TX[22]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[23]}]
set_property DRIVE 12 [get_ports {FPGA_TX[23]}]
set_property SLEW SLOW [get_ports {FPGA_TX[23]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[24]}]
set_property DRIVE 12 [get_ports {FPGA_TX[24]}]
set_property SLEW SLOW [get_ports {FPGA_TX[24]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[25]}]
set_property DRIVE 12 [get_ports {FPGA_TX[25]}]
set_property SLEW SLOW [get_ports {FPGA_TX[25]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[26]}]
set_property DRIVE 12 [get_ports {FPGA_TX[26]}]
set_property SLEW SLOW [get_ports {FPGA_TX[26]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[27]}]
set_property DRIVE 12 [get_ports {FPGA_TX[27]}]
set_property SLEW SLOW [get_ports {FPGA_TX[27]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[28]}]
set_property DRIVE 12 [get_ports {FPGA_TX[28]}]
set_property SLEW SLOW [get_ports {FPGA_TX[28]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[29]}]
set_property DRIVE 12 [get_ports {FPGA_TX[29]}]
set_property SLEW SLOW [get_ports {FPGA_TX[29]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[2]}]
set_property DRIVE 12 [get_ports {FPGA_TX[2]}]
set_property SLEW SLOW [get_ports {FPGA_TX[2]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[30]}]
set_property DRIVE 12 [get_ports {FPGA_TX[30]}]
set_property SLEW SLOW [get_ports {FPGA_TX[30]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[31]}]
set_property DRIVE 12 [get_ports {FPGA_TX[31]}]
set_property SLEW SLOW [get_ports {FPGA_TX[31]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[32]}]
set_property DRIVE 12 [get_ports {FPGA_TX[32]}]
set_property SLEW SLOW [get_ports {FPGA_TX[32]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[3]}]
set_property DRIVE 12 [get_ports {FPGA_TX[3]}]
set_property SLEW SLOW [get_ports {FPGA_TX[3]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[4]}]
set_property DRIVE 12 [get_ports {FPGA_TX[4]}]
set_property SLEW SLOW [get_ports {FPGA_TX[4]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[5]}]
set_property DRIVE 12 [get_ports {FPGA_TX[5]}]
set_property SLEW SLOW [get_ports {FPGA_TX[5]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[6]}]
set_property DRIVE 12 [get_ports {FPGA_TX[6]}]
set_property SLEW SLOW [get_ports {FPGA_TX[6]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[7]}]
set_property DRIVE 12 [get_ports {FPGA_TX[7]}]
set_property SLEW SLOW [get_ports {FPGA_TX[7]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[8]}]
set_property DRIVE 12 [get_ports {FPGA_TX[8]}]
set_property SLEW SLOW [get_ports {FPGA_TX[8]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[9]}]
set_property DRIVE 12 [get_ports {FPGA_TX[9]}]
set_property SLEW SLOW [get_ports {FPGA_TX[9]}]
#set_property DIRECTION OUT [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property DRIVE 12 [get_ports {LED[1]}]
set_property SLEW SLOW [get_ports {LED[1]}]
#set_property DIRECTION OUT [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property DRIVE 12 [get_ports {LED[2]}]
set_property SLEW SLOW [get_ports {LED[2]}]
#set_property DIRECTION OUT [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property DRIVE 12 [get_ports {LED[3]}]
set_property SLEW SLOW [get_ports {LED[3]}]
#set_property DIRECTION OUT [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property DRIVE 12 [get_ports {LED[4]}]
set_property SLEW SLOW [get_ports {LED[4]}]
#set_property DIRECTION OUT [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property DRIVE 12 [get_ports {LED[5]}]
set_property SLEW SLOW [get_ports {LED[5]}]
#set_property DIRECTION OUT [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property DRIVE 12 [get_ports {LED[6]}]
set_property SLEW SLOW [get_ports {LED[6]}]
#set_property DIRECTION OUT [get_ports {M_CSF[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[10]}]
set_property DRIVE 12 [get_ports {M_CSF[10]}]
set_property SLEW SLOW [get_ports {M_CSF[10]}]
#set_property DIRECTION OUT [get_ports {M_CSF[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[11]}]
set_property DRIVE 12 [get_ports {M_CSF[11]}]
set_property SLEW SLOW [get_ports {M_CSF[11]}]
#set_property DIRECTION OUT [get_ports {M_CSF[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[12]}]
set_property DRIVE 12 [get_ports {M_CSF[12]}]
set_property SLEW SLOW [get_ports {M_CSF[12]}]
#set_property DIRECTION OUT [get_ports {M_CSF[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[13]}]
set_property DRIVE 12 [get_ports {M_CSF[13]}]
set_property SLEW SLOW [get_ports {M_CSF[13]}]
#set_property DIRECTION OUT [get_ports {M_CSF[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[14]}]
set_property DRIVE 12 [get_ports {M_CSF[14]}]
set_property SLEW SLOW [get_ports {M_CSF[14]}]
#set_property DIRECTION OUT [get_ports {M_CSF[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[15]}]
set_property DRIVE 12 [get_ports {M_CSF[15]}]
set_property SLEW SLOW [get_ports {M_CSF[15]}]
#set_property DIRECTION OUT [get_ports {M_CSF[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[16]}]
set_property DRIVE 12 [get_ports {M_CSF[16]}]
set_property SLEW SLOW [get_ports {M_CSF[16]}]
#set_property DIRECTION OUT [get_ports {M_CSF[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[17]}]
set_property DRIVE 12 [get_ports {M_CSF[17]}]
set_property SLEW SLOW [get_ports {M_CSF[17]}]
#set_property DIRECTION OUT [get_ports {M_CSF[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[18]}]
set_property DRIVE 12 [get_ports {M_CSF[18]}]
set_property SLEW SLOW [get_ports {M_CSF[18]}]
#set_property DIRECTION OUT [get_ports {M_CSF[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[19]}]
set_property DRIVE 12 [get_ports {M_CSF[19]}]
set_property SLEW SLOW [get_ports {M_CSF[19]}]
#set_property DIRECTION OUT [get_ports {M_CSF[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[1]}]
set_property DRIVE 12 [get_ports {M_CSF[1]}]
set_property SLEW SLOW [get_ports {M_CSF[1]}]
#set_property DIRECTION OUT [get_ports {M_CSF[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[20]}]
set_property DRIVE 12 [get_ports {M_CSF[20]}]
set_property SLEW SLOW [get_ports {M_CSF[20]}]
#set_property DIRECTION OUT [get_ports {M_CSF[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[21]}]
set_property DRIVE 12 [get_ports {M_CSF[21]}]
set_property SLEW SLOW [get_ports {M_CSF[21]}]
#set_property DIRECTION OUT [get_ports {M_CSF[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[22]}]
set_property DRIVE 12 [get_ports {M_CSF[22]}]
set_property SLEW SLOW [get_ports {M_CSF[22]}]
#set_property DIRECTION OUT [get_ports {M_CSF[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[23]}]
set_property DRIVE 12 [get_ports {M_CSF[23]}]
set_property SLEW SLOW [get_ports {M_CSF[23]}]
#set_property DIRECTION OUT [get_ports {M_CSF[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[24]}]
set_property DRIVE 12 [get_ports {M_CSF[24]}]
set_property SLEW SLOW [get_ports {M_CSF[24]}]
#set_property DIRECTION OUT [get_ports {M_CSF[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[25]}]
set_property DRIVE 12 [get_ports {M_CSF[25]}]
set_property SLEW SLOW [get_ports {M_CSF[25]}]
#set_property DIRECTION OUT [get_ports {M_CSF[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[26]}]
set_property DRIVE 12 [get_ports {M_CSF[26]}]
set_property SLEW SLOW [get_ports {M_CSF[26]}]
#set_property DIRECTION OUT [get_ports {M_CSF[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[27]}]
set_property DRIVE 12 [get_ports {M_CSF[27]}]
set_property SLEW SLOW [get_ports {M_CSF[27]}]
#set_property DIRECTION OUT [get_ports {M_CSF[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[28]}]
set_property DRIVE 12 [get_ports {M_CSF[28]}]
set_property SLEW SLOW [get_ports {M_CSF[28]}]
#set_property DIRECTION OUT [get_ports {M_CSF[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[29]}]
set_property DRIVE 12 [get_ports {M_CSF[29]}]
set_property SLEW SLOW [get_ports {M_CSF[29]}]
#set_property DIRECTION OUT [get_ports {M_CSF[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[2]}]
set_property DRIVE 12 [get_ports {M_CSF[2]}]
set_property SLEW SLOW [get_ports {M_CSF[2]}]
#set_property DIRECTION OUT [get_ports {M_CSF[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[30]}]
set_property DRIVE 12 [get_ports {M_CSF[30]}]
set_property SLEW SLOW [get_ports {M_CSF[30]}]
#set_property DIRECTION OUT [get_ports {M_CSF[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[31]}]
set_property DRIVE 12 [get_ports {M_CSF[31]}]
set_property SLEW SLOW [get_ports {M_CSF[31]}]
#set_property DIRECTION OUT [get_ports {M_CSF[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[32]}]
set_property DRIVE 12 [get_ports {M_CSF[32]}]
set_property SLEW SLOW [get_ports {M_CSF[32]}]
#set_property DIRECTION OUT [get_ports {M_CSF[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[3]}]
set_property DRIVE 12 [get_ports {M_CSF[3]}]
set_property SLEW SLOW [get_ports {M_CSF[3]}]
#set_property DIRECTION OUT [get_ports {M_CSF[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[4]}]
set_property DRIVE 12 [get_ports {M_CSF[4]}]
set_property SLEW SLOW [get_ports {M_CSF[4]}]
#set_property DIRECTION OUT [get_ports {M_CSF[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[5]}]
set_property DRIVE 12 [get_ports {M_CSF[5]}]
set_property SLEW SLOW [get_ports {M_CSF[5]}]
#set_property DIRECTION OUT [get_ports {M_CSF[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[6]}]
set_property DRIVE 12 [get_ports {M_CSF[6]}]
set_property SLEW SLOW [get_ports {M_CSF[6]}]
#set_property DIRECTION OUT [get_ports {M_CSF[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[7]}]
set_property DRIVE 12 [get_ports {M_CSF[7]}]
set_property SLEW SLOW [get_ports {M_CSF[7]}]
#set_property DIRECTION OUT [get_ports {M_CSF[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[8]}]
set_property DRIVE 12 [get_ports {M_CSF[8]}]
set_property SLEW SLOW [get_ports {M_CSF[8]}]
#set_property DIRECTION OUT [get_ports {M_CSF[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[9]}]
set_property DRIVE 12 [get_ports {M_CSF[9]}]
set_property SLEW SLOW [get_ports {M_CSF[9]}]

#set_property DIRECTION INOUT [get_ports AUX_4]
set_property IOSTANDARD LVCMOS33 [get_ports AUX_4]
set_property DRIVE 12 [get_ports AUX_4]
set_property SLEW SLOW [get_ports AUX_4]
#set_property DIRECTION OUT [get_ports C_SCLK_F]
set_property IOSTANDARD LVCMOS33 [get_ports C_SCLK_F]
set_property DRIVE 12 [get_ports C_SCLK_F]
set_property SLEW FAST [get_ports C_SCLK_F]
#set_property DIRECTION IN [get_ports C_SDI_F]
set_property IOSTANDARD LVCMOS33 [get_ports C_SDI_F]
#set_property DIRECTION OUT [get_ports C_SDO_F]
set_property IOSTANDARD LVCMOS33 [get_ports C_SDO_F]
set_property DRIVE 12 [get_ports C_SDO_F]
set_property SLEW SLOW [get_ports C_SDO_F]
#set_property DIRECTION OUT [get_ports M_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports M_SCLK]
set_property DRIVE 12 [get_ports M_SCLK]
set_property SLEW FAST [get_ports M_SCLK]
#set_property DIRECTION IN [get_ports M_SDI_F]
set_property IOSTANDARD LVCMOS33 [get_ports M_SDI_F]
#set_property DIRECTION OUT [get_ports M_SDO_F]
set_property IOSTANDARD LVCMOS33 [get_ports M_SDO_F]
set_property DRIVE 12 [get_ports M_SDO_F]
set_property SLEW SLOW [get_ports M_SDO_F]


#set_property DIRECTION OUT [get_ports LED_SOM]
set_property IOSTANDARD LVCMOS15 [get_ports LED_SOM]
set_property DRIVE 12 [get_ports LED_SOM]
set_property SLEW SLOW [get_ports LED_SOM]
#revert back to original instance
current_instance -quiet




















#SPI power signals
set_property PACKAGE_PIN D19 [get_ports cs_c0_0]
set_property PACKAGE_PIN B15 [get_ports cs_c1_0]
set_property PACKAGE_PIN A16 [get_ports cs_c2_0]
set_property PACKAGE_PIN F20 [get_ports cs_c3_0]
set_property PACKAGE_PIN M17 [get_ports cs_c4_0]
set_property PACKAGE_PIN B21 [get_ports cs_c5_0]
set_property PACKAGE_PIN E22 [get_ports cs_c6_0]
set_property PACKAGE_PIN F18 [get_ports cs_c7_0]
set_property PACKAGE_PIN A19 [get_ports cs_c8_0]
set_property PACKAGE_PIN G20 [get_ports cs_c9_0]
set_property PACKAGE_PIN K21 [get_ports cs_c10_0]
set_property PACKAGE_PIN N22 [get_ports cs_c11_0]
set_property PACKAGE_PIN K19 [get_ports cs_c12_0]
set_property PACKAGE_PIN J19 [get_ports cs_c13_0]
set_property PACKAGE_PIN J21 [get_ports cs_c14_0]
set_property PACKAGE_PIN N20 [get_ports cs_c15_0]
set_property PACKAGE_PIN M18 [get_ports cs_c16_0]
set_property PACKAGE_PIN V14 [get_ports cs_c17_0]
set_property PACKAGE_PIN T14 [get_ports cs_c18_0]
set_property PACKAGE_PIN H14 [get_ports cs_c19_0]
set_property PACKAGE_PIN K14 [get_ports cs_c20_0]
set_property PACKAGE_PIN W17 [get_ports cs_c21_0]
set_property PACKAGE_PIN AB22 [get_ports cs_c22_0]
set_property PACKAGE_PIN AB20 [get_ports cs_c23_0]
set_property PACKAGE_PIN AB18 [get_ports cs_c24_0]
set_property PACKAGE_PIN V10 [get_ports cs_c25_0]

#The current active pins for mini board
set_property PACKAGE_PIN AA10[get_ports cs_c26_0]
set_property PACKAGE_PIN W21 [get_ports cs_c27_0]
set_property PACKAGE_PIN Y22 [get_ports cs_c28_0]
set_property PACKAGE_PIN Y19 [get_ports cs_c29_0]
set_property PACKAGE_PIN U22 [get_ports cs_c30_0]
set_property PACKAGE_PIN V19 [get_ports cs_c31_0]


set_property IOSTANDARD LVCMOS33 [get_ports cs_c0_0]
set_property DRIVE 12 [get_ports cs_c0_0]
set_property SLEW SLOW [get_ports cs_c0_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c1_0]
set_property DRIVE 12 [get_ports cs_c1_0]
set_property SLEW SLOW [get_ports cs_c1_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c2_0]
set_property DRIVE 12 [get_ports cs_c2_0]
set_property SLEW SLOW [get_ports cs_c2_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c3_0]
set_property DRIVE 12 [get_ports cs_c3_0]
set_property SLEW SLOW [get_ports cs_c3_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c4_0]
set_property DRIVE 12 [get_ports cs_c4_0]
set_property SLEW SLOW [get_ports cs_c4_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c5_0]
set_property DRIVE 12 [get_ports cs_c5_0]
set_property SLEW SLOW [get_ports cs_c5_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c6_0]
set_property DRIVE 12 [get_ports cs_c6_0]
set_property SLEW SLOW [get_ports cs_c6_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c7_0]
set_property DRIVE 12 [get_ports cs_c7_0]
set_property SLEW SLOW [get_ports cs_c7_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c8_0]
set_property DRIVE 12 [get_ports cs_c8_0]
set_property SLEW SLOW [get_ports cs_c8_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c9_0]
set_property DRIVE 12 [get_ports cs_c9_0]
set_property SLEW SLOW [get_ports cs_c9_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c10_0]
set_property DRIVE 12 [get_ports cs_c10_0]
set_property SLEW SLOW [get_ports cs_c10_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c11_0]
set_property DRIVE 12 [get_ports cs_c11_0]
set_property SLEW SLOW [get_ports cs_c11_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c12_0]
set_property DRIVE 12 [get_ports cs_c12_0]
set_property SLEW SLOW [get_ports cs_c12_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c13_0]
set_property DRIVE 12 [get_ports cs_c13_0]
set_property SLEW SLOW [get_ports cs_c13_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c14_0]
set_property DRIVE 12 [get_ports cs_c14_0]
set_property SLEW SLOW [get_ports cs_c14_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c15_0]
set_property DRIVE 12 [get_ports cs_c15_0]
set_property SLEW SLOW [get_ports cs_c15_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c16_0]
set_property DRIVE 12 [get_ports cs_c16_0]
set_property SLEW SLOW [get_ports cs_c16_0}]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c17_0]
set_property DRIVE 12 [get_ports cs_c17_0]
set_property SLEW SLOW [get_ports cs_c17_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c18_0]
set_property DRIVE 12 [get_ports cs_c18_0]
set_property SLEW SLOW [get_ports cs_c18_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c19_0]
set_property DRIVE 12 [get_ports cs_c19_0]
set_property SLEW SLOW [get_ports cs_c19_0]



set_property IOSTANDARD LVCMOS33 [get_ports cs_c20_0]
set_property DRIVE 12 [get_ports cs_c20_0]
set_property SLEW SLOW [get_ports cs_c20_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c21_0]
set_property DRIVE 12 [get_ports cs_c21_0]
set_property SLEW SLOW [get_ports cs_c21_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c22_0]
set_property DRIVE 12 [get_ports cs_c22_0]
set_property SLEW SLOW [get_ports cs_c22_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c23_0]
set_property DRIVE 12 [get_ports cs_c23_0]
set_property SLEW SLOW [get_ports cs_c23_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c24_0]
set_property DRIVE 12 [get_ports cs_c24_0]
set_property SLEW SLOW [get_ports cs_c24_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c25_0]
set_property DRIVE 12 [get_ports cs_c25_0]
set_property SLEW SLOW [get_ports cs_c25_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c26_0]
set_property DRIVE 12 [get_ports cs_c26_0]
set_property SLEW SLOW [get_ports cs_c26_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c27_0]
set_property DRIVE 12 [get_ports cs_c27_0]
set_property SLEW SLOW [get_ports cs_c27_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c28_0]
set_property DRIVE 12 [get_ports cs_c28_0]
set_property SLEW SLOW [get_ports cs_c28_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c29_0]
set_property DRIVE 12 [get_ports cs_c29_0]
set_property SLEW SLOW [get_ports cs_c29_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c30_0]
set_property DRIVE 12 [get_ports cs_c30_0]
set_property SLEW SLOW [get_ports cs_c30_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_c31_0]
set_property DRIVE 12 [get_ports cs_c31_0]
set_property SLEW SLOW [get_ports cs_c31_0]

set_property PACKAGE_PIN R19 [get_ports sck_c_0]
set_property PACKAGE_PIN R18  [get_ports miso_c_0]
set_property PACKAGE_PIN P19 [get_ports mosi_c_0]

set_property IOSTANDARD LVCMOS33 [get_ports sck_c_0]
set_property DRIVE 12 [get_ports sck_c_0]
set_property SLEW FAST [get_ports sck_c_0]

#set_property DIRECTION IN [get_ports miso_c_0]
set_property IOSTANDARD LVCMOS33 [get_ports miso_c_0]

#set_property DIRECTION OUT [get_ports mosi_c_0]
set_property IOSTANDARD LVCMOS33 [get_ports mosi_c_0]
set_property DRIVE 12 [get_ports mosi_c_0]
set_property SLEW SLOW [get_ports mosi_c_0]


#SPI Monitor signals
set_property PACKAGE_PIN E19 [get_ports cs_m0_0]
set_property PACKAGE_PIN F19 [get_ports cs_m1_0]
set_property PACKAGE_PIN A15 [get_ports cs_m2_0]
set_property PACKAGE_PIN D17 [get_ports cs_m3_0]
set_property PACKAGE_PIN J16 [get_ports cs_m4_0]
set_property PACKAGE_PIN A21 [get_ports cs_m5_0]
set_property PACKAGE_PIN D21 [get_ports cs_m6_0]
set_property PACKAGE_PIN G22 [get_ports cs_m7_0]
set_property PACKAGE_PIN A18 [get_ports cs_m8_0]
set_property PACKAGE_PIN A13 [get_ports cs_m9_0]
set_property PACKAGE_PIN J22 [get_ports cs_m10_0]
set_property PACKAGE_PIN M22 [get_ports cs_m11_0]
set_property PACKAGE_PIN H17 [get_ports cs_m12_0]
set_property PACKAGE_PIN L21 [get_ports cs_m13_0]
set_property PACKAGE_PIN J20 [get_ports cs_m14_0]
set_property PACKAGE_PIN C14 [get_ports cs_m15_0]
set_property PACKAGE_PIN N18 [get_ports cs_m16_0]
set_property PACKAGE_PIN W11 [get_ports cs_m17_0]
set_property PACKAGE_PIN T15 [get_ports cs_m18_0]
set_property PACKAGE_PIN V17 [get_ports cs_m19_0]
set_property PACKAGE_PIN K13 [get_ports cs_m20_0]
set_property PACKAGE_PIN F16 [get_ports cs_m21_0]
set_property PACKAGE_PIN AB21 [get_ports cs_m22_0]
set_property PACKAGE_PIN AA20 [get_ports cs_m23_0]
set_property PACKAGE_PIN AA18 [get_ports cs_m24_0]
set_property PACKAGE_PIN W22 [get_ports cs_m25_0]

#The current active pins for mini board
set_property PACKAGE_PIN AA11[get_ports cs_m26_0]
set_property PACKAGE_PIN N13 [get_ports cs_m27_0]
set_property PACKAGE_PIN Y21 [get_ports cs_m28_0]
set_property PACKAGE_PIN W19 [get_ports cs_m29_0]
set_property PACKAGE_PIN V22 [get_ports cs_m30_0]
set_property PACKAGE_PIN T18 [get_ports cs_m31_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m0_0]
set_property DRIVE 12 [get_ports cs_m0_0]
set_property SLEW SLOW [get_ports cs_m0_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m1_0]
set_property DRIVE 12 [get_ports cs_m1_0]
set_property SLEW SLOW [get_ports cs_m1_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m2_0]
set_property DRIVE 12 [get_ports cs_m2_0]
set_property SLEW SLOW [get_ports cs_m2_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m3_0]
set_property DRIVE 12 [get_ports cs_m3_0]
set_property SLEW SLOW [get_ports cs_m3_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m4_0]
set_property DRIVE 12 [get_ports cs_m4_0]
set_property SLEW SLOW [get_ports cs_m4_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m5_0]
set_property DRIVE 12 [get_ports cs_m5_0]
set_property SLEW SLOW [get_ports cs_m5_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m6_0]
set_property DRIVE 12 [get_ports cs_m6_0]
set_property SLEW SLOW [get_ports cs_m6_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m7_0]
set_property DRIVE 12 [get_ports cs_m7_0]
set_property SLEW SLOW [get_ports cs_m7_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m8_0]
set_property DRIVE 12 [get_ports cs_m8_0]
set_property SLEW SLOW [get_ports cs_m8_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m9_0]
set_property DRIVE 12 [get_ports cs_m9_0]
set_property SLEW SLOW [get_ports cs_m9_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m10_0]
set_property DRIVE 12 [get_ports cs_m10_0]
set_property SLEW SLOW [get_ports cs_m10_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m11_0]
set_property DRIVE 12 [get_ports cs_m11_0]
set_property SLEW SLOW [get_ports cs_m11_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m12_0]
set_property DRIVE 12 [get_ports cs_m12_0]
set_property SLEW SLOW [get_ports cs_m12_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m13_0]
set_property DRIVE 12 [get_ports cs_m13_0]
set_property SLEW SLOW [get_ports cs_m13_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m14_0]
set_property DRIVE 12 [get_ports cs_m14_0]
set_property SLEW SLOW [get_ports cs_m14_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m15_0]
set_property DRIVE 12 [get_ports cs_m15_0]
set_property SLEW SLOW [get_ports cs_m15_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m16_0]
set_property DRIVE 12 [get_ports cs_m16_0]
set_property SLEW SLOW [get_ports cs_m16_0}]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m17_0]
set_property DRIVE 12 [get_ports cs_m17_0]
set_property SLEW SLOW [get_ports cs_m17_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m18_0]
set_property DRIVE 12 [get_ports cs_m18_0]
set_property SLEW SLOW [get_ports cs_m18_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m19_0]
set_property DRIVE 12 [get_ports cs_m19_0]
set_property SLEW SLOW [get_ports cs_m19_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m20_0]
set_property DRIVE 12 [get_ports cs_m20_0]
set_property SLEW SLOW [get_ports cs_m20_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m21_0]
set_property DRIVE 12 [get_ports cs_m21_0]
set_property SLEW SLOW [get_ports cs_m21_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m22_0]
set_property DRIVE 12 [get_ports cs_m22_0]
set_property SLEW SLOW [get_ports cs_m22_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m23_0]
set_property DRIVE 12 [get_ports cs_m23_0]
set_property SLEW SLOW [get_ports cs_m23_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m24_0]
set_property DRIVE 12 [get_ports cs_m24_0]
set_property SLEW SLOW [get_ports cs_m24_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m25_0]
set_property DRIVE 12 [get_ports cs_m25_0]
set_property SLEW SLOW [get_ports cs_m25_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m26_0]
set_property DRIVE 12 [get_ports cs_m26_0]
set_property SLEW SLOW [get_ports cs_m26_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m27_0]
set_property DRIVE 12 [get_ports cs_m27_0]
set_property SLEW SLOW [get_ports cs_m27_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m28_0]
set_property DRIVE 12 [get_ports cs_m28_0]
set_property SLEW SLOW [get_ports cs_m28_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m29_0]
set_property DRIVE 12 [get_ports cs_m29_0]
set_property SLEW SLOW [get_ports cs_m29_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m30_0]
set_property DRIVE 12 [get_ports cs_m30_0]
set_property SLEW SLOW [get_ports cs_m30_0]

set_property IOSTANDARD LVCMOS33 [get_ports cs_m31_0]
set_property DRIVE 12 [get_ports cs_m31_0]
set_property SLEW SLOW [get_ports cs_m31_0]

set_property PACKAGE_PIN U18 [get_ports sck_m_0]
set_property PACKAGE_PIN U17 [get_ports mosi_m_0]
set_property PACKAGE_PIN P14 [get_ports miso_m_0]

#set_property DIRECTION OUT [get_ports sck_m_0]
set_property IOSTANDARD LVCMOS33 [get_ports sck_m_0]
set_property DRIVE 12 [get_ports sck_m_0]
set_property SLEW FAST [get_ports sck_m_0]
#set_property DIRECTION IN [get_ports miso_m_0]
set_property IOSTANDARD LVCMOS33 [get_ports miso_m_0]
#set_property DIRECTION OUT [get_ports mosi_m_0]
set_property IOSTANDARD LVCMOS33 [get_ports mosi_m_0]
set_property DRIVE 12 [get_ports mosi_m_0]
set_property SLEW SLOW [get_ports mosi_m_0]

## DBG Signals
## Define Master clk in
set_property PACKAGE_PIN R4 [get_ports CLK_IN1_D_0_clk_p]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports CLK_IN1_D_0_clk_p]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports CLK_IN1_D_0_clk_n]

## Output tx_elink
set_property PACKAGE_PIN AB7 [get_ports {tx_elink_p_0[0]}]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports {tx_elink_p_0[0]}]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports {tx_elink_n_0[0]}]

## Input rx_elink
set_property PACKAGE_PIN AA8 [get_ports rx_elink_p_0]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports rx_elink_p_0]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports rx_elink_n_0]
set_property DIFF_TERM TRUE [get_ports rx_elink_p_0]
set_property DIFF_TERM TRUE [get_ports rx_elink_n_0]

## Define clk out
set_property IOSTANDARD DIFF_SSTL15_R [get_ports clk_out_p_0]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports clk_out_n_0]
set_property PACKAGE_PIN W9 [get_ports clk_out_p_0]

#set_property PACKAGE_PIN U19 [get_ports rx_fifo_full_rdy_0]
#Rx CAN signals
set_property IOSTANDARD LVCMOS33 [get_ports rx0_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx1_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx2_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx3_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx4_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx5_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx6_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx7_0]
set_property PACKAGE_PIN Y18 [get_ports rx0_0]
set_property PACKAGE_PIN U20 [get_ports rx1_0]
set_property PACKAGE_PIN AA9 [get_ports rx2_0]
set_property PACKAGE_PIN R14 [get_ports rx3_0]
set_property PACKAGE_PIN U21 [get_ports rx4_0]
set_property PACKAGE_PIN Y17 [get_ports rx5_0]
set_property PACKAGE_PIN AA19 [get_ports rx6_0]
set_property PACKAGE_PIN Y12 [get_ports rx7_0]
#Tx CAN signals
set_property IOSTANDARD LVCMOS33 [get_ports tx0_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx1_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx2_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx3_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx7_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx4_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx5_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx6_0]
set_property PACKAGE_PIN V18 [get_ports tx0_0]
set_property PACKAGE_PIN V20 [get_ports tx1_0]
set_property PACKAGE_PIN AB10 [get_ports tx2_0]
set_property PACKAGE_PIN W20 [get_ports tx3_0]
set_property PACKAGE_PIN T21 [get_ports tx4_0]
set_property PACKAGE_PIN T20 [get_ports tx5_0]
set_property PACKAGE_PIN W10 [get_ports tx6_0]
set_property PACKAGE_PIN Y11 [get_ports tx7_0]

## DBG Signals
set_property IOSTANDARD LVCMOS33 [get_ports tx_data_rdy_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_data_rdy_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_elink_tra_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_elink_rec_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_can_rec_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_can_tra_0]
set_property IOSTANDARD LVCMOS33 [get_ports endwait_all_0]
set_property IOSTANDARD LVCMOS33 [get_ports irq_elink_dbg_0]
set_property IOSTANDARD LVCMOS33 [get_ports seialize_data_stream_0]
#set_property IOSTANDARD LVCMOS33 [get_ports tx_fifo_full_rdy_0]

set_property PACKAGE_PIN E14 [get_ports irq_elink_tra_0]
set_property PACKAGE_PIN E13 [get_ports irq_elink_rec_0]
set_property PACKAGE_PIN D15 [get_ports tx_data_rdy_0]
set_property PACKAGE_PIN D14 [get_ports rx_data_rdy_0]
set_property PACKAGE_PIN C13 [get_ports irq_can_rec_0]
set_property PACKAGE_PIN B13 [get_ports irq_can_tra_0]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_board_0/irq_can_rec]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_board_0/irq_can_tra]


connect_debug_port u_ila_0/clk [get_nets [list mopshub_design_i/clk_wiz_s/inst/clk_40_s]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_40_s]








create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list mopshub_design_i/clk_wiz_s/inst/clk_40]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list mopshub_design_i/mopshub_top_board_0/irq_can_rec]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list mopshub_design_i/mopshub_top_board_0/irq_can_tra]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_40]

