set_property SRC_FILE_INFO {cfile:/home/dcs/git/mopshub/mopshub_synthesis_slave/mopshub_synthesis_slave.srcs/sources_1/bd/mopshub_design/ip/mopshub_design_clk_wiz_0_0/mopshub_design_clk_wiz_0_0.xdc rfile:../../../../../mopshub_synthesis_slave.srcs/sources_1/bd/mopshub_design/ip/mopshub_design_clk_wiz_0_0/mopshub_design_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:mopshub_design_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dcs/git/mopshub/mopshub_synthesis_slave/mopshub_synthesis_slave.srcs/sources_1/bd/mopshub_design/ip/mopshub_design_processing_system7_0_1/mopshub_design_processing_system7_0_1.xdc rfile:../../../../../mopshub_synthesis_slave.srcs/sources_1/bd/mopshub_design/ip/mopshub_design_processing_system7_0_1/mopshub_design_processing_system7_0_1.xdc id:2 order:EARLY scoped_inst:mopshub_design_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dcs/git/mopshub/mopshub_synthesis_slave/mopshub_synthesis_slave.srcs/constrs_1/new/mopshub_constraints.xdc rfile:../../../../../mopshub_synthesis_slave.srcs/constrs_1/new/mopshub_constraints.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dcs/git/mopshub/mopshub_synthesis_slave/mopshub_synthesis_slave.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_100in_clk_p [get_ports clk_100in_clk_p]
current_instance mopshub_design_i/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PHASESHIFT_MODE WAVEFORM [get_cells mmcm_adv_inst]
current_instance
current_instance mopshub_design_i/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name clk_fpga_0 [get_pins {PS7_i/FCLKCLK[0]}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrp]
set_property src_info {type:SCOPED_XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrp]
set_property src_info {type:SCOPED_XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrp]
set_property src_info {type:SCOPED_XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrn]
set_property src_info {type:SCOPED_XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrn]
set_property src_info {type:SCOPED_XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrn]
set_property src_info {type:SCOPED_XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_we_n]
set_property src_info {type:SCOPED_XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_we_n]
set_property src_info {type:SCOPED_XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_we_n]
set_property src_info {type:SCOPED_XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_ras_n]
set_property src_info {type:SCOPED_XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_ras_n]
set_property src_info {type:SCOPED_XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_ras_n]
set_property src_info {type:SCOPED_XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_odt]
set_property src_info {type:SCOPED_XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_odt]
set_property src_info {type:SCOPED_XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_odt]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports DDR_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dm[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dm[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_cs_n]
set_property src_info {type:SCOPED_XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_cs_n]
set_property src_info {type:SCOPED_XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cs_n]
set_property src_info {type:SCOPED_XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_cke]
set_property src_info {type:SCOPED_XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_cke]
set_property src_info {type:SCOPED_XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cke]
set_property src_info {type:SCOPED_XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_p]
set_property src_info {type:SCOPED_XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_ck_p]
set_property src_info {type:SCOPED_XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_p]
set_property src_info {type:SCOPED_XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_n]
set_property src_info {type:SCOPED_XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_ck_n]
set_property src_info {type:SCOPED_XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_n]
set_property src_info {type:SCOPED_XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_cas_n]
set_property src_info {type:SCOPED_XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_cas_n]
set_property src_info {type:SCOPED_XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cas_n]
set_property src_info {type:SCOPED_XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_ba[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_porb]
set_property src_info {type:SCOPED_XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ps_porb]
set_property src_info {type:SCOPED_XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_srstb]
set_property src_info {type:SCOPED_XDC file:2 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ps_srstb]
set_property src_info {type:SCOPED_XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_clk]
set_property src_info {type:SCOPED_XDC file:2 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ps_clk]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfbout_mopshub_design_clk_wiz_0_0 -source [get_pins mopshub_design_i/clk_wiz_0/inst/mmcm_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks clk_100in_clk_p] [get_pins mopshub_design_i/clk_wiz_0/inst/mmcm_adv_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_40_mopshub_design_clk_wiz_0_0 -source [get_pins mopshub_design_i/clk_wiz_0/inst/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 7.500 15.000} -add -master_clock [get_clocks clk_100in_clk_p] [get_pins mopshub_design_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_80_mopshub_design_clk_wiz_0_0 -source [get_pins mopshub_design_i/clk_wiz_0/inst/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 1.250 2.500} -add -master_clock [get_clocks clk_100in_clk_p] [get_pins mopshub_design_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_100_mopshub_design_clk_wiz_0_0 -source [get_pins mopshub_design_i/clk_wiz_0/inst/mmcm_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks clk_100in_clk_p] [get_pins mopshub_design_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT2]
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx0_0]
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx0_0]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports osc_auto_trim_mopshub_0]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports end_cnt_dbg_0]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx_data_rdy_0]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx_data_rdy_0]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports reset_0]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports irq_elink_tra_dbg_0]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports irq_elink_rec_dbg_0]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports can_tra_dbg_0]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports can_rec_dbg_0]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports led_0]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports clk_100in_clk_p]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports clk_100in_clk_n]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports clk_100out_n_0]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports clk_100out_p_0]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {tx_elink_p[0]}]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {tx_elink_n[0]}]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {rx_elink_p[0]}]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS_25 [get_ports {rx_elink_n[0]}]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx_fifo_full_rdy_0]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {rx_elink_p[0]}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports {rx_elink_n[0]}]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports clk_100in_clk_p]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports clk_100in_clk_n]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx1_0]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx2_0]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx3_0]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx7_0]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx4_0]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx5_0]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tx6_0]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx1_0]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx2_0]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx3_0]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx4_0]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx5_0]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx6_0]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rx7_0]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/irq_can_rec_dbg]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/irq_can_tra_dbg]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/irq_elink_rec]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/irq_elink_tra]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/rx_data_rdy_in]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/tx_data_rdy_in]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[14]}]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[3]}]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[6]}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[7]}]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[11]}]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[15]}]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[19]}]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[22]}]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[23]}]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_rec_uplink[67]}]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/start_read_elink]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/start_write_link]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/end_write_elink]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/end_read_elink]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[34]}]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[16]}]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[7]}]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[4]}]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[0]}]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[2]}]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[6]}]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[48]}]
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[50]}]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[52]}]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[54]}]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[46]}]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[44]}]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[42]}]
set_property src_info {type:XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[40]}]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[38]}]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[36]}]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[32]}]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[30]}]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[28]}]
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[26]}]
set_property src_info {type:XDC file:3 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[24]}]
set_property src_info {type:XDC file:3 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[22]}]
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[20]}]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[18]}]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[14]}]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[12]}]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[10]}]
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[62]}]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[56]}]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[58]}]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[60]}]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[64]}]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[66]}]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[68]}]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[70]}]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[72]}]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[74]}]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[17]}]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[1]}]
set_property src_info {type:XDC file:3 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[3]}]
set_property src_info {type:XDC file:3 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[5]}]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[8]}]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[11]}]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[13]}]
set_property src_info {type:XDC file:3 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[15]}]
set_property src_info {type:XDC file:3 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[19]}]
set_property src_info {type:XDC file:3 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[21]}]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[23]}]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[25]}]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[27]}]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[29]}]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[31]}]
set_property src_info {type:XDC file:3 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[33]}]
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[35]}]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[37]}]
set_property src_info {type:XDC file:3 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[39]}]
set_property src_info {type:XDC file:3 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[41]}]
set_property src_info {type:XDC file:3 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[43]}]
set_property src_info {type:XDC file:3 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[45]}]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[47]}]
set_property src_info {type:XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[49]}]
set_property src_info {type:XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[51]}]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[53]}]
set_property src_info {type:XDC file:3 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[9]}]
set_property src_info {type:XDC file:3 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[61]}]
set_property src_info {type:XDC file:3 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[55]}]
set_property src_info {type:XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[57]}]
set_property src_info {type:XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[59]}]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[63]}]
set_property src_info {type:XDC file:3 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[65]}]
set_property src_info {type:XDC file:3 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[67]}]
set_property src_info {type:XDC file:3 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[69]}]
set_property src_info {type:XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[71]}]
set_property src_info {type:XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/data_tra_downlink[73]}]
set_property src_info {type:XDC file:3 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mopshub_design_i/mopshub_top_diff_por_0/inst/mopshub_top_0/elink_core0/elink_to_fifo0/elink_proc_in0/data_8b10b_rdy]
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/clk_wiz_0/inst]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/selectio_wiz_0/inst]
set_property src_info {type:XDC file:4 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/selectio_wiz_1/inst]
set_property src_info {type:XDC file:4 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/processing_system7_0/inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/mopshub_top_diff_por_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/xlconstant_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/clk_wiz_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/selectio_wiz_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/selectio_wiz_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells mopshub_design_i/processing_system7_0]
