set_property SRC_FILE_INFO {cfile:/home/dcs/git/mopshub/Vivado/mopshub_v1/mopshub_board_v1/mopshub_board_v1.gen/sources_1/bd/mopshub_board_v1/ip/mopshub_board_v1_mopshub_top_board_16_0_0/mopshub_board_v1_mopshub_top_board_16_0_0_ooc.xdc rfile:../../../../../mopshub_board_v1.gen/sources_1/bd/mopshub_board_v1/ip/mopshub_board_v1_mopshub_top_board_16_0_0/mopshub_board_v1_mopshub_top_board_16_0_0_ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dcs/git/mopshub/Vivado/mopshub_v1/mopshub_board_v1/mopshub_board_v1.runs/mopshub_board_v1_mopshub_top_board_16_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 10.000 -name shift_clk [get_ports shift_clk]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/ip_xadc_wrapper0/xadc_wiz_inst/inst]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/ip_xadc_wrapper0/xadc_wiz_inst]
