#make_diff_pair_ports AUX[1] AUX_N[1]
#make_diff_pair_ports AUX[2] AUX_N[2]
#make_diff_pair_ports AUX[3] AUX_N[3]
#make_diff_pair_ports ELINK_CLK ELINK_CLK_N
#make_diff_pair_ports ELINK_RX ELINK_RX_N
#make_diff_pair_ports ELINK_TX ELINK_TX_N
#set_property DCI_CASCADE {} [get_iobanks 34]

set_property PACKAGE_PIN AA13 [get_ports {M_CSF[16]}]
set_property PACKAGE_PIN V13 [get_ports {M_CSF[15]}]
set_property PACKAGE_PIN U16 [get_ports {M_CSF[14]}]
set_property PACKAGE_PIN Y22 [get_ports {M_CSF[13]}]
set_property PACKAGE_PIN W20 [get_ports {M_CSF[12]}]
set_property PACKAGE_PIN Y18 [get_ports {M_CSF[11]}]
set_property PACKAGE_PIN K22 [get_ports {M_CSF[9]}]
set_property PACKAGE_PIN P15 [get_ports {M_CSF[10]}]
set_property PACKAGE_PIN L19 [get_ports {M_CSF[8]}]
set_property PACKAGE_PIN K17 [get_ports {M_CSF[7]}]
set_property PACKAGE_PIN H15 [get_ports {M_CSF[6]}]
set_property PACKAGE_PIN D22 [get_ports {M_CSF[5]}]
set_property PACKAGE_PIN AA13 [get_ports {M_CSF[16]}]
set_property PACKAGE_PIN V15 [get_ports {C_CSF[14]}]
set_property PACKAGE_PIN Y12 [get_ports {C_CSF[15]}]
set_property PACKAGE_PIN F21 [get_ports {C_CSF[5]}]
set_property PACKAGE_PIN M15 [get_ports {C_CSF[6]}]
set_property PACKAGE_PIN M17 [get_ports {C_CSF[7]}]
set_property PACKAGE_PIN R16 [get_ports {C_CSF[10]}]
set_property PACKAGE_PIN V18 [get_ports {C_CSF[11]}]
set_property PACKAGE_PIN AA20 [get_ports {C_CSF[12]}]
set_property PACKAGE_PIN AB22 [get_ports {C_CSF[13]}]
set_property PACKAGE_PIN AB12 [get_ports {C_CSF[16]}]

set_property PACKAGE_PIN G13 [get_ports {LED[1]}]
set_property PACKAGE_PIN K13 [get_ports {LED[2]}]
set_property PACKAGE_PIN L13 [get_ports {LED[3]}]
set_property PACKAGE_PIN L14 [get_ports {LED[4]}]
set_property PACKAGE_PIN L15 [get_ports {LED[5]}]
set_property PACKAGE_PIN M13 [get_ports {LED[6]}]

set_property PACKAGE_PIN W10 [get_ports C_SCLK_F]
set_property PACKAGE_PIN W11 [get_ports C_SDI_F]
set_property PACKAGE_PIN AA10 [get_ports M_SCLK]
set_property PACKAGE_PIN AB10 [get_ports M_SDI_F]
set_property PACKAGE_PIN AA9 [get_ports M_SDO_F]
set_property PACKAGE_PIN V10 [get_ports C_SDO_F]

set_property PACKAGE_PIN AA4 [get_ports AUX_4]


set_property PACKAGE_PIN B13 [get_ports {FPGA_TX[1]}]
set_property PACKAGE_PIN A16 [get_ports {FPGA_TX[2]}]
set_property PACKAGE_PIN C17 [get_ports {FPGA_TX[3]}]
set_property PACKAGE_PIN A19 [get_ports {FPGA_TX[4]}]
set_property PACKAGE_PIN B22 [get_ports {FPGA_TX[5]}]
set_property PACKAGE_PIN J14 [get_ports {FPGA_TX[6]}]
set_property PACKAGE_PIN H17 [get_ports {FPGA_TX[7]}]
set_property PACKAGE_PIN J19 [get_ports {FPGA_TX[8]}]
set_property PACKAGE_PIN H22 [get_ports {FPGA_TX[9]}]
set_property PACKAGE_PIN N14 [get_ports {FPGA_TX[10]}]
set_property PACKAGE_PIN T18 [get_ports {FPGA_TX[11]}]
set_property PACKAGE_PIN U20 [get_ports {FPGA_TX[12]}]
set_property PACKAGE_PIN V22 [get_ports {FPGA_TX[13]}]
set_property PACKAGE_PIN T15 [get_ports {FPGA_TX[14]}]
set_property PACKAGE_PIN Y16 [get_ports {FPGA_TX[15]}]
set_property PACKAGE_PIN AB17 [get_ports {FPGA_TX[16]}]


set_property PACKAGE_PIN A13 [get_ports {FPGA_RX[1]}]
set_property PACKAGE_PIN A15 [get_ports {FPGA_RX[2]}]
set_property PACKAGE_PIN B17 [get_ports {FPGA_RX[3]}]
set_property PACKAGE_PIN A18 [get_ports {FPGA_RX[4]}]
set_property PACKAGE_PIN A21 [get_ports {FPGA_RX[5]}]
set_property PACKAGE_PIN H13 [get_ports {FPGA_RX[6]}]
set_property PACKAGE_PIN G17 [get_ports {FPGA_RX[7]}]
set_property PACKAGE_PIN H19 [get_ports {FPGA_RX[8]}]
set_property PACKAGE_PIN G22 [get_ports {FPGA_RX[9]}]
set_property PACKAGE_PIN N13 [get_ports {FPGA_RX[10]}]
set_property PACKAGE_PIN R18 [get_ports {FPGA_RX[11]}]
set_property PACKAGE_PIN P20 [get_ports {FPGA_RX[12]}]
set_property PACKAGE_PIN T21 [get_ports {FPGA_RX[13]}]
set_property PACKAGE_PIN T14 [get_ports {FPGA_RX[14]}]
set_property PACKAGE_PIN AA15 [get_ports {FPGA_RX[15]}]
set_property PACKAGE_PIN AB18 [get_ports {FPGA_RX[16]}]


set_property PACKAGE_PIN F13 [get_ports {C_CSF[1]}]
set_property PACKAGE_PIN F15 [get_ports {C_CSF[2]}]
set_property PACKAGE_PIN F18 [get_ports {C_CSF[3]}]
set_property PACKAGE_PIN E19 [get_ports {C_CSF[4]}]
set_property PACKAGE_PIN M20 [get_ports {C_CSF[8]}]
set_property PACKAGE_PIN M22 [get_ports {C_CSF[9]}]

set_property PACKAGE_PIN D14 [get_ports {M_CSF[1]}]
set_property PACKAGE_PIN C15 [get_ports {M_CSF[2]}]
set_property PACKAGE_PIN E17 [get_ports {M_CSF[3]}]
set_property PACKAGE_PIN C19 [get_ports {M_CSF[4]}]



set_property PACKAGE_PIN K19 [get_ports CLK40MHZ]

set_property PACKAGE_PIN AB3 [get_ports ELINK_TX]
set_property PACKAGE_PIN AB2 [get_ports ELINK_TX_N]
set_property PACKAGE_PIN T1 [get_ports ELINK_RX]
set_property PACKAGE_PIN U1 [get_ports ELINK_RX_N]

set_property PACKAGE_PIN AB11 [get_ports WDI]
set_property PACKAGE_PIN B21 [get_ports IO[3]]
set_property PACKAGE_PIN C20 [get_ports IO[2]]
set_property PACKAGE_PIN E13 [get_ports IO[1]]
set_property PACKAGE_PIN C13 [get_ports IO[0]]



set_property PACKAGE_PIN A14 [get_ports SIMPLE_OUT]
set_property PACKAGE_PIN A20 [get_ports SHIFT_MODE]
set_property PACKAGE_PIN D15 [get_ports TMR_OUT]
set_property PACKAGE_PIN D17 [get_ports SHIFT_DATA]
set_property PACKAGE_PIN D19 [get_ports SHIFT_CLK]




set_property IOSTANDARD LVCMOS33 [get_ports {WDI}]
set_property DRIVE 12 [get_ports {WDI}]
set_property SLEW SLOW [get_ports {WDI}]

set_property IOSTANDARD LVCMOS33 [get_ports {SIMPLE_OUT}]
set_property DRIVE 12 [get_ports {SIMPLE_OUT}]
set_property SLEW SLOW [get_ports {SIMPLE_OUT}]

set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT_MODE}]
set_property DRIVE 12 [get_ports {SHIFT_MODE}]
set_property SLEW SLOW [get_ports {SHIFT_MODE}]

set_property IOSTANDARD LVCMOS33 [get_ports {TMR_OUT}]
set_property DRIVE 12 [get_ports {TMR_OUT}]
set_property SLEW SLOW [get_ports {TMR_OUT}]

set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT_DATA}]
set_property DRIVE 12 [get_ports {SHIFT_DATA}]
set_property SLEW SLOW [get_ports {SHIFT_DATA}]

set_property IOSTANDARD LVCMOS33 [get_ports {SHIFT_CLK}]
set_property DRIVE 12 [get_ports {SHIFT_CLK}]
set_property SLEW SLOW [get_ports {SHIFT_CLK}]

set_property IOSTANDARD LVCMOS33 [get_ports {IO[3]}]
set_property DRIVE 12 [get_ports {IO[3]}]
set_property SLEW SLOW [get_ports {IO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO[2]}]
set_property DRIVE 12 [get_ports {IO[2]}]
set_property SLEW SLOW [get_ports {IO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO[1]}]
set_property DRIVE 12 [get_ports {IO[1]}]
set_property SLEW SLOW [get_ports {IO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO[0]}]
set_property DRIVE 12 [get_ports {IO[0]}]
set_property SLEW SLOW [get_ports {IO[0]}]


#set_property DIRECTION OUT [get_ports {C_CSF[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[10]}]
set_property DRIVE 12 [get_ports {C_CSF[10]}]
set_property SLEW SLOW [get_ports {C_CSF[10]}]
#set_property DIRECTION OUT [get_ports {C_CSF[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[11]}]
set_property DRIVE 12 [get_ports {C_CSF[11]}]
set_property SLEW SLOW [get_ports {C_CSF[11]}]
#set_property DIRECTION OUT [get_ports {C_CSF[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[12]}]
set_property DRIVE 12 [get_ports {C_CSF[12]}]
set_property SLEW SLOW [get_ports {C_CSF[12]}]
#set_property DIRECTION OUT [get_ports {C_CSF[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[13]}]
set_property DRIVE 12 [get_ports {C_CSF[13]}]
set_property SLEW SLOW [get_ports {C_CSF[13]}]
#set_property DIRECTION OUT [get_ports {C_CSF[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[14]}]
set_property DRIVE 12 [get_ports {C_CSF[14]}]
set_property SLEW SLOW [get_ports {C_CSF[14]}]
#set_property DIRECTION OUT [get_ports {C_CSF[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[15]}]
set_property DRIVE 12 [get_ports {C_CSF[15]}]
set_property SLEW SLOW [get_ports {C_CSF[15]}]
#set_property DIRECTION OUT [get_ports {C_CSF[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[16]}]
set_property DRIVE 12 [get_ports {C_CSF[16]}]
set_property SLEW SLOW [get_ports {C_CSF[16]}]

#set_property DIRECTION OUT [get_ports {C_CSF[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[1]}]
set_property DRIVE 12 [get_ports {C_CSF[1]}]
set_property SLEW SLOW [get_ports {C_CSF[1]}]
#set_property DIRECTION OUT [get_ports {C_CSF[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[2]}]
set_property DRIVE 12 [get_ports {C_CSF[2]}]
set_property SLEW SLOW [get_ports {C_CSF[2]}]
#set_property DIRECTION OUT [get_ports {C_CSF[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[3]}]
set_property DRIVE 12 [get_ports {C_CSF[3]}]
set_property SLEW SLOW [get_ports {C_CSF[3]}]
#set_property DIRECTION OUT [get_ports {C_CSF[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[4]}]
set_property DRIVE 12 [get_ports {C_CSF[4]}]
set_property SLEW SLOW [get_ports {C_CSF[4]}]
#set_property DIRECTION OUT [get_ports {C_CSF[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[5]}]
set_property DRIVE 12 [get_ports {C_CSF[5]}]
set_property SLEW SLOW [get_ports {C_CSF[5]}]
#set_property DIRECTION OUT [get_ports {C_CSF[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[6]}]
set_property DRIVE 12 [get_ports {C_CSF[6]}]
set_property SLEW SLOW [get_ports {C_CSF[6]}]
#set_property DIRECTION OUT [get_ports {C_CSF[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[7]}]
set_property DRIVE 12 [get_ports {C_CSF[7]}]
set_property SLEW SLOW [get_ports {C_CSF[7]}]
#set_property DIRECTION OUT [get_ports {C_CSF[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[8]}]
set_property DRIVE 12 [get_ports {C_CSF[8]}]
set_property SLEW SLOW [get_ports {C_CSF[8]}]
#set_property DIRECTION OUT [get_ports {C_CSF[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C_CSF[9]}]
set_property DRIVE 12 [get_ports {C_CSF[9]}]
set_property SLEW SLOW [get_ports {C_CSF[9]}]







set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports AUX_{FPGA_RX[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_RX[9]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[10]}]
set_property DRIVE 12 [get_ports {FPGA_TX[10]}]
set_property SLEW SLOW [get_ports {FPGA_TX[10]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[11]}]
set_property DRIVE 12 [get_ports {FPGA_TX[11]}]
set_property SLEW SLOW [get_ports {FPGA_TX[11]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[12]}]
set_property DRIVE 12 [get_ports {FPGA_TX[12]}]
set_property SLEW SLOW [get_ports {FPGA_TX[12]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[13]}]
set_property DRIVE 12 [get_ports {FPGA_TX[13]}]
set_property SLEW SLOW [get_ports {FPGA_TX[13]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[14]}]
set_property DRIVE 12 [get_ports {FPGA_TX[14]}]
set_property SLEW SLOW [get_ports {FPGA_TX[14]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[15]}]
set_property DRIVE 12 [get_ports {FPGA_TX[15]}]
set_property SLEW SLOW [get_ports {FPGA_TX[15]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[16]}]
set_property DRIVE 12 [get_ports {FPGA_TX[16]}]
set_property SLEW SLOW [get_ports {FPGA_TX[16]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[1]}]
set_property DRIVE 12 [get_ports {FPGA_TX[1]}]
set_property SLEW SLOW [get_ports {FPGA_TX[1]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[2]}]
set_property DRIVE 12 [get_ports {FPGA_TX[2]}]
set_property SLEW SLOW [get_ports {FPGA_TX[2]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[3]}]
set_property DRIVE 12 [get_ports {FPGA_TX[3]}]
set_property SLEW SLOW [get_ports {FPGA_TX[3]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[4]}]
set_property DRIVE 12 [get_ports {FPGA_TX[4]}]
set_property SLEW SLOW [get_ports {FPGA_TX[4]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[5]}]
set_property DRIVE 12 [get_ports {FPGA_TX[5]}]
set_property SLEW SLOW [get_ports {FPGA_TX[5]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[6]}]
set_property DRIVE 12 [get_ports {FPGA_TX[6]}]
set_property SLEW SLOW [get_ports {FPGA_TX[6]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[7]}]
set_property DRIVE 12 [get_ports {FPGA_TX[7]}]
set_property SLEW SLOW [get_ports {FPGA_TX[7]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[8]}]
set_property DRIVE 12 [get_ports {FPGA_TX[8]}]
set_property SLEW SLOW [get_ports {FPGA_TX[8]}]
#set_property DIRECTION OUT [get_ports {FPGA_TX[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_TX[9]}]
set_property DRIVE 12 [get_ports {FPGA_TX[9]}]
set_property SLEW SLOW [get_ports {FPGA_TX[9]}]
#set_property DIRECTION OUT [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property DRIVE 12 [get_ports {LED[1]}]
set_property SLEW SLOW [get_ports {LED[1]}]
#set_property DIRECTION OUT [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property DRIVE 12 [get_ports {LED[2]}]
set_property SLEW SLOW [get_ports {LED[2]}]
#set_property DIRECTION OUT [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property DRIVE 12 [get_ports {LED[3]}]
set_property SLEW SLOW [get_ports {LED[3]}]
#set_property DIRECTION OUT [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property DRIVE 12 [get_ports {LED[4]}]
set_property SLEW SLOW [get_ports {LED[4]}]
#set_property DIRECTION OUT [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property DRIVE 12 [get_ports {LED[5]}]
set_property SLEW SLOW [get_ports {LED[5]}]
#set_property DIRECTION OUT [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property DRIVE 12 [get_ports {LED[6]}]
set_property SLEW SLOW [get_ports {LED[6]}]




#set_property DIRECTION OUT [get_ports {M_CSF[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[10]}]
set_property DRIVE 12 [get_ports {M_CSF[10]}]
set_property SLEW SLOW [get_ports {M_CSF[10]}]
#set_property DIRECTION OUT [get_ports {M_CSF[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[11]}]
set_property DRIVE 12 [get_ports {M_CSF[11]}]
set_property SLEW SLOW [get_ports {M_CSF[11]}]
#set_property DIRECTION OUT [get_ports {M_CSF[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[12]}]
set_property DRIVE 12 [get_ports {M_CSF[12]}]
set_property SLEW SLOW [get_ports {M_CSF[12]}]
#set_property DIRECTION OUT [get_ports {M_CSF[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[13]}]
set_property DRIVE 12 [get_ports {M_CSF[13]}]
set_property SLEW SLOW [get_ports {M_CSF[13]}]
#set_property DIRECTION OUT [get_ports {M_CSF[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[14]}]
set_property DRIVE 12 [get_ports {M_CSF[14]}]
set_property SLEW SLOW [get_ports {M_CSF[14]}]
#set_property DIRECTION OUT [get_ports {M_CSF[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[15]}]
set_property DRIVE 12 [get_ports {M_CSF[15]}]
set_property SLEW SLOW [get_ports {M_CSF[15]}]
#set_property DIRECTION OUT [get_ports {M_CSF[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[16]}]
set_property DRIVE 12 [get_ports {M_CSF[16]}]
set_property SLEW SLOW [get_ports {M_CSF[16]}]
#set_property DIRECTION OUT [get_ports {M_CSF[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[1]}]
set_property DRIVE 12 [get_ports {M_CSF[1]}]
set_property SLEW SLOW [get_ports {M_CSF[1]}]
#set_property DIRECTION OUT [get_ports {M_CSF[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[2]}]
set_property DRIVE 12 [get_ports {M_CSF[2]}]
set_property SLEW SLOW [get_ports {M_CSF[2]}]
#set_property DIRECTION OUT [get_ports {M_CSF[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[3]}]
set_property DRIVE 12 [get_ports {M_CSF[3]}]
set_property SLEW SLOW [get_ports {M_CSF[3]}]
#set_property DIRECTION OUT [get_ports {M_CSF[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[4]}]
set_property DRIVE 12 [get_ports {M_CSF[4]}]
set_property SLEW SLOW [get_ports {M_CSF[4]}]
#set_property DIRECTION OUT [get_ports {M_CSF[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[5]}]
set_property DRIVE 12 [get_ports {M_CSF[5]}]
set_property SLEW SLOW [get_ports {M_CSF[5]}]
#set_property DIRECTION OUT [get_ports {M_CSF[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[6]}]
set_property DRIVE 12 [get_ports {M_CSF[6]}]
set_property SLEW SLOW [get_ports {M_CSF[6]}]
#set_property DIRECTION OUT [get_ports {M_CSF[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[7]}]
set_property DRIVE 12 [get_ports {M_CSF[7]}]
set_property SLEW SLOW [get_ports {M_CSF[7]}]
#set_property DIRECTION OUT [get_ports {M_CSF[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[8]}]
set_property DRIVE 12 [get_ports {M_CSF[8]}]
set_property SLEW SLOW [get_ports {M_CSF[8]}]
#set_property DIRECTION OUT [get_ports {M_CSF[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_CSF[9]}]
set_property DRIVE 12 [get_ports {M_CSF[9]}]
set_property SLEW SLOW [get_ports {M_CSF[9]}]







#set_property DIRECTION INOUT [get_ports AUX_4]
set_property IOSTANDARD LVCMOS15 [get_ports AUX_4]
#set_property DRIVE 12 [get_ports AUX_4]
#set_property SLEW SLOW [get_ports AUX_4]
#set_property DIRECTION OUT [get_ports C_SCLK_F]
set_property IOSTANDARD LVCMOS33 [get_ports C_SCLK_F]
set_property DRIVE 12 [get_ports C_SCLK_F]
set_property SLEW FAST [get_ports C_SCLK_F]
set_property IOSTANDARD LVCMOS33 [get_ports C_SDI_F]
#set_property DIRECTION OUT [get_ports C_SDO_F]
set_property IOSTANDARD LVCMOS33 [get_ports C_SDO_F]
set_property DRIVE 12 [get_ports C_SDO_F]
set_property SLEW SLOW [get_ports C_SDO_F]
#set_property DIRECTION OUT [get_ports ELINK_RX]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_RX]
#set_property DIRECTION OUT [get_ports ELINK_RX_N]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_RX_N]
#set_property DIRECTION OUT [get_ports ELINK_TX]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_TX]
set_property SLEW SLOW [get_ports ELINK_TX]
#set_property DIRECTION OUT [get_ports ELINK_TX_N]
set_property IOSTANDARD DIFF_SSTL15_R [get_ports ELINK_TX_N]
set_property SLEW SLOW [get_ports ELINK_TX_N]
#set_property DIRECTION OUT [get_ports M_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports M_SCLK]
set_property DRIVE 12 [get_ports M_SCLK]
set_property SLEW FAST [get_ports M_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports M_SDI_F]
#set_property DIRECTION OUT [get_ports M_SDO_F]
set_property IOSTANDARD LVCMOS33 [get_ports M_SDO_F]
set_property DRIVE 12 [get_ports M_SDO_F]
set_property SLEW SLOW [get_ports M_SDO_F]
set_property IOSTANDARD LVCMOS33 [get_ports CLK40MHZ]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {CLK40MHZ_BUF}]
#set_property DIRECTION OUT [get_ports QSPI_CS]

