//
// Module mopshub_lib.bus_control_SM.fsm
//
// Created:
//          by - dcs.dcs (chipdev2.physik.uni-wuppertal.de)
//          at - 13:11:58 06/20/22
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//
`resetall
`timescale 1ns/10ps
module bus_control_SM( 
   // Port Declarations
   input   wire           abort,                  // Upon receiving a reset message on the CANbus. FSM goes into a known state
   input   wire           busy_p, 
   input   wire           clk,                    // posedge
   input   wire           cnt_done, 
   input   wire           end_cnt, 
   input   wire           end_read_elink,         // this signal goes high when CANopen block has finshed writing transmit message buffer register 
   input   wire           end_read_miso, 
   input   wire           end_write_elink_spi, 
   input   wire           irq_spi_tra, 
   input   wire           rst,                    // synchronous low active
   input   wire           start_bus_init,         // initialize request from bridge FSM of bridge controller 
   input   wire           start_mon_init, 
   input   wire           start_power_off, 
   input   wire           start_power_on, 
   input   wire           start_read_mon, 
   input   wire           start_read_power, 
   input   wire           timeoutrst,             // timeout reset signal to the state machine in case bridge controller is not respoding for a specified time
   output  reg     [4:0]  addr,                   // request to caninterface block
   output  reg            bus_en_done,            // indication to bridge FSM when initialization is finished 
   output  reg            cs_m, 
   output  reg            cs_p, 
   output  reg            end_spi_proc, 
   output  reg            entimeout, 
   output  reg            mon_en_done, 
   output  reg            read_spi_mode, 
   output  reg            spi_cs, 
   output  reg            start_cnt, 
   output  reg            start_init, 
   output  reg            start_read_elink,       // signal to read transmit message buffer register 
   output  reg            start_read_miso, 
   output  reg            start_write_elink_spi, 
   output  reg     [7:0]  statedeb,               // State debug signal 
   output  reg            transcieve_p
);

//tmrg default triplicate
//tmrg tmr_error false
// Internal Declarations


// Module Declarations

// State encoding
parameter 
          waittoact          = 8'd0,
          reset              = 8'd1,
          start              = 8'd2,
          ST_Init_1          = 8'd3,
          st_Init_2          = 8'd4,
          endinit1           = 8'd5,
          start1             = 8'd6,
          St_wait1           = 8'd7,
          St_wait2           = 8'd8,
          ST_Read_reg        = 8'd9,
          ST_Read_RS_3       = 8'd10,
          ST_Read_reg1       = 8'd11,
          ST_Read_RS_4       = 8'd12,
          St_wait3           = 8'd13,
          st_GPIOA           = 8'd14,
          st_GPIOA1          = 8'd15,
          st_GPIOA2          = 8'd16,
          End_Select         = 8'd17,
          st_GPIOA3          = 8'd18,
          st_GPIOA4          = 8'd19,
          st_GPIOA5          = 8'd20,
          st_GPIOA6          = 8'd21,
          st_GPIOA7          = 8'd22,
          st_GPIOA8          = 8'd23,
          ST_Read_reg5       = 8'd24,
          ST_Read_RS_8       = 8'd25,
          Write_Mosi         = 8'd26,
          read_elink_mes1    = 8'd27,
          CS_low             = 8'd28,
          Read_Miso          = 8'd29,
          Done               = 8'd30,
          write_elink        = 8'd31,
          Wait_Miso          = 8'd32,
          St_wait4           = 8'd33,
          St_wait11          = 8'd34,
          Offset_calibrate0  = 8'd35,
          Offset__calibrate1 = 8'd36,
          Offset__calibrate2 = 8'd37,
          Offset__calibrate3 = 8'd38,
          s0                 = 8'd39,
          s1                 = 8'd40,
          s2                 = 8'd41,
          Gain_calibrate0    = 8'd42,
          Gain_calibrate1    = 8'd43,
          Gain_calibrate2    = 8'd44,
          Gain_calibrate3    = 8'd45,
          s3                 = 8'd46,
          s4                 = 8'd47,
          s5                 = 8'd48,
          s6                 = 8'd49,
          write_csrs7        = 8'd50,
          write_csrs6        = 8'd51,
          write_csrs5        = 8'd52,
          write_csrs4        = 8'd53,
          write_csrs0        = 8'd54,
          write_csrs1        = 8'd55,
          write_csrs2        = 8'd56,
          ST_Config4         = 8'd57,
          ST_Config3         = 8'd58,
          ST_Config1         = 8'd59,
          ST_Config2         = 8'd60,
          ST_Rest_2          = 8'd61,
          ST_Rest_4          = 8'd62,
          ST_Rest_1          = 8'd63,
          St_wait            = 8'd64,
          ST_Rest_RS_1       = 8'd65,
          ST_Rest_RS_2       = 8'd66,
          st_GPIOA9          = 8'd67,
          st_GPIOA10         = 8'd68,
          st_GPIOA11         = 8'd69,
          w_busy15           = 8'd70,
          w_busy16           = 8'd71,
          w_busy17           = 8'd72,
          ST_IODIRA0         = 8'd73,
          w_busy0            = 8'd74,
          ST_IODIRA1         = 8'd75,
          w_busy1            = 8'd76,
          ST_IODIRA2         = 8'd77,
          w_busy2            = 8'd78,
          w_busy5            = 8'd79,
          st_IODIRB1         = 8'd80,
          st_IODIRB2         = 8'd81,
          st_IODIRB          = 8'd82,
          w_busy3            = 8'd83,
          w_busy4            = 8'd84,
          w_busy7            = 8'd85,
          st_GPIOB2          = 8'd86,
          st_GPIOB1          = 8'd87,
          w_busy8            = 8'd88,
          w_busy6            = 8'd89,
          st_GPIOB0          = 8'd90,
          st_GPPUA           = 8'd91,
          w_busy11           = 8'd92,
          w_busy9            = 8'd93,
          st_GPPUA2          = 8'd94,
          st_GPPUA1          = 8'd95,
          w_busy10           = 8'd96,
          st_GPPUB1          = 8'd97,
          w_busy13           = 8'd98,
          w_busy12           = 8'd99,
          st_GPPUB2          = 8'd100,
          w_busy14           = 8'd101,
          st_GPPUB           = 8'd102,
          CS_high0           = 8'd103,
          CS_high1           = 8'd104,
          CS_high2           = 8'd105,
          CS_high3           = 8'd106,
          CS_high4           = 8'd107,
          CS_high5           = 8'd108,
          start2             = 8'd109,
          End_Select1        = 8'd110,
          CS_high6           = 8'd111,
          CS_high11          = 8'd112,
          st_GPIOA12         = 8'd113,
          st_GPIOA13         = 8'd114,
          st_GPIOA14         = 8'd115,
          w_busy18           = 8'd116,
          w_busy19           = 8'd117,
          w_busy20           = 8'd118,
          ST_IODIRA4         = 8'd119,
          ST_IODIRA5         = 8'd120,
          ST_IODIRA6         = 8'd121,
          w_busy21           = 8'd122,
          w_busy22           = 8'd123,
          w_busy23           = 8'd124,
          w_busy24           = 8'd125,
          w_busy25           = 8'd126,
          w_busy26           = 8'd127,
          w_busy27           = 8'd128,
          w_busy28           = 8'd129,
          w_busy29           = 8'd130,
          w_busy30           = 8'd131,
          w_busy31           = 8'd132;

reg [7:0] current_state, next_state;

// Wait State Signals
reg [5:0] csm_timer;
reg [5:0] csm_next_timer;
reg       csm_timeout;
reg       csm_to_ST_Init_1;
reg       csm_to_ST_Read_RS_3;
reg       csm_to_ST_Read_RS_4;
reg       csm_to_ST_Read_RS_8;
reg       csm_to_CS_low;
reg       csm_to_Read_Miso;
reg       csm_to_s0;
reg       csm_to_s1;
reg       csm_to_s2;
reg       csm_to_s3;
reg       csm_to_s4;
reg       csm_to_s5;
reg       csm_to_s6;
reg       csm_to_ST_Rest_2;
reg       csm_to_ST_Rest_RS_2;

//-----------------------------------------------------------------
// Next State Block for machine csm
//-----------------------------------------------------------------
always @(
   busy_p, 
   csm_timeout, 
   current_state, 
   end_read_elink, 
   end_read_miso, 
   end_write_elink_spi, 
   irq_spi_tra, 
   rst, 
   start_bus_init, 
   start_mon_init, 
   start_power_off, 
   start_power_on, 
   start_read_mon, 
   start_read_power
)
begin : next_state_block_proc
   // Default assignments to Wait State entry flags
   csm_to_ST_Init_1 = 1'b0;
   csm_to_ST_Read_RS_3 = 1'b0;
   csm_to_ST_Read_RS_4 = 1'b0;
   csm_to_ST_Read_RS_8 = 1'b0;
   csm_to_CS_low = 1'b0;
   csm_to_Read_Miso = 1'b0;
   csm_to_s0 = 1'b0;
   csm_to_s1 = 1'b0;
   csm_to_s2 = 1'b0;
   csm_to_s3 = 1'b0;
   csm_to_s4 = 1'b0;
   csm_to_s5 = 1'b0;
   csm_to_s6 = 1'b0;
   csm_to_ST_Rest_2 = 1'b0;
   csm_to_ST_Rest_RS_2 = 1'b0;
   case (current_state) 
      waittoact: begin
         if (start_bus_init  == 1)
            next_state = start;
         else if (start_mon_init ==1)
            next_state = start1;
         else if (start_power_on ==1)
            next_state = st_GPIOA3;
         else if (start_power_off ==1)
            next_state = st_GPIOA6;
         else if (start_read_mon ==1)
            next_state = ST_Read_reg5;
         else if (irq_spi_tra ==1)
            next_state = read_elink_mes1;
         else if (start_read_power ==1)
            next_state = st_GPIOA9;
         else if (start_bus_init  == 1 && start_power_off)
            next_state = start2;
         else
            next_state = waittoact;
      end
      reset: begin
         if (rst == 1)
            next_state = waittoact;
         else
            next_state = reset;
      end
      start: begin
         next_state = ST_IODIRA0;
      end
      ST_Init_1: begin
         if (csm_timeout)
            next_state = st_Init_2;
         else
            next_state = ST_Init_1;
      end
      st_Init_2: begin
         next_state = ST_Rest_1;
      end
      endinit1: begin
         next_state = waittoact;
      end
      start1: begin
         next_state = ST_Init_1;
         csm_to_ST_Init_1 = 1'b1;
      end
      St_wait1: begin
         next_state = ST_Read_reg;
      end
      St_wait2: begin
         next_state = ST_Config1;
      end
      ST_Read_reg: begin
         next_state = ST_Read_RS_3;
         csm_to_ST_Read_RS_3 = 1'b1;
      end
      ST_Read_RS_3: begin
         if (csm_timeout)
            next_state = St_wait2;
         else
            next_state = ST_Read_RS_3;
      end
      ST_Read_reg1: begin
         next_state = ST_Read_RS_4;
         csm_to_ST_Read_RS_4 = 1'b1;
      end
      ST_Read_RS_4: begin
         if (csm_timeout)
            next_state = St_wait3;
         else
            next_state = ST_Read_RS_4;
      end
      St_wait3: begin
         next_state = write_csrs0;
      end
      st_GPIOA: begin
         next_state = w_busy15;
      end
      st_GPIOA1: begin
         next_state = w_busy16;
      end
      st_GPIOA2: begin
         next_state = w_busy17;
      end
      End_Select: begin
         next_state = waittoact;
      end
      st_GPIOA3: begin
         next_state = st_GPIOA4;
      end
      st_GPIOA4: begin
         next_state = st_GPIOA5;
      end
      st_GPIOA5: begin
         next_state = waittoact;
      end
      st_GPIOA6: begin
         next_state = st_GPIOA7;
      end
      st_GPIOA7: begin
         next_state = st_GPIOA8;
      end
      st_GPIOA8: begin
         next_state = waittoact;
      end
      ST_Read_reg5: begin
         next_state = ST_Read_RS_8;
         csm_to_ST_Read_RS_8 = 1'b1;
      end
      ST_Read_RS_8: begin
         if (csm_timeout)
            next_state = waittoact;
         else
            next_state = ST_Read_RS_8;
      end
      Write_Mosi: begin
         next_state = CS_low;
         csm_to_CS_low = 1'b1;
      end
      read_elink_mes1: begin
         if (end_read_elink == 1)
            next_state = Write_Mosi;
         else
            next_state = read_elink_mes1;
      end
      CS_low: begin
         if (csm_timeout) begin
            next_state = Read_Miso;
            csm_to_Read_Miso = 1'b1;
         end
         else
            next_state = CS_low;
      end
      Read_Miso: begin
         if (csm_timeout)
            next_state = Wait_Miso;
         else
            next_state = Read_Miso;
      end
      Done: begin
         next_state = waittoact;
      end
      write_elink: begin
         if (end_write_elink_spi ==1)
            next_state = Done;
         else
            next_state = write_elink;
      end
      Wait_Miso: begin
         if (end_read_miso == 1)
            next_state = write_elink;
         else
            next_state = Wait_Miso;
      end
      St_wait4: begin
         next_state = Offset_calibrate0;
      end
      St_wait11: begin
         next_state = ST_Read_reg1;
      end
      Offset_calibrate0: begin
         next_state = s0;
         csm_to_s0 = 1'b1;
      end
      Offset__calibrate1: begin
         next_state = s1;
         csm_to_s1 = 1'b1;
      end
      Offset__calibrate2: begin
         next_state = s2;
         csm_to_s2 = 1'b1;
      end
      Offset__calibrate3: begin
         next_state = Gain_calibrate0;
      end
      s0: begin
         if (csm_timeout)
            next_state = Offset__calibrate1;
         else
            next_state = s0;
      end
      s1: begin
         if (csm_timeout)
            next_state = Offset__calibrate2;
         else
            next_state = s1;
      end
      s2: begin
         if (csm_timeout)
            next_state = Offset__calibrate3;
         else
            next_state = s2;
      end
      Gain_calibrate0: begin
         next_state = s3;
         csm_to_s3 = 1'b1;
      end
      Gain_calibrate1: begin
         next_state = s4;
         csm_to_s4 = 1'b1;
      end
      Gain_calibrate2: begin
         next_state = s5;
         csm_to_s5 = 1'b1;
      end
      Gain_calibrate3: begin
         next_state = s6;
         csm_to_s6 = 1'b1;
      end
      s3: begin
         if (csm_timeout)
            next_state = Gain_calibrate1;
         else
            next_state = s3;
      end
      s4: begin
         if (csm_timeout)
            next_state = Gain_calibrate2;
         else
            next_state = s4;
      end
      s5: begin
         if (csm_timeout)
            next_state = Gain_calibrate3;
         else
            next_state = s5;
      end
      s6: begin
         if (csm_timeout)
            next_state = endinit1;
         else
            next_state = s6;
      end
      write_csrs7: begin
         next_state = St_wait4;
      end
      write_csrs6: begin
         next_state = write_csrs7;
      end
      write_csrs5: begin
         next_state = write_csrs6;
      end
      write_csrs4: begin
         next_state = write_csrs5;
      end
      write_csrs0: begin
         next_state = write_csrs1;
      end
      write_csrs1: begin
         next_state = write_csrs2;
      end
      write_csrs2: begin
         next_state = write_csrs4;
      end
      ST_Config4: begin
         next_state = St_wait11;
      end
      ST_Config3: begin
         next_state = ST_Config4;
      end
      ST_Config1: begin
         next_state = ST_Config2;
      end
      ST_Config2: begin
         next_state = ST_Config3;
      end
      ST_Rest_2: begin
         if (csm_timeout)
            next_state = ST_Rest_4;
         else
            next_state = ST_Rest_2;
      end
      ST_Rest_4: begin
         next_state = St_wait;
      end
      ST_Rest_1: begin
         next_state = ST_Rest_2;
         csm_to_ST_Rest_2 = 1'b1;
      end
      St_wait: begin
         next_state = ST_Rest_RS_1;
      end
      ST_Rest_RS_1: begin
         next_state = ST_Rest_RS_2;
         csm_to_ST_Rest_RS_2 = 1'b1;
      end
      ST_Rest_RS_2: begin
         if (csm_timeout)
            next_state = St_wait1;
         else
            next_state = ST_Rest_RS_2;
      end
      st_GPIOA9: begin
         next_state = st_GPIOA10;
      end
      st_GPIOA10: begin
         next_state = st_GPIOA11;
      end
      st_GPIOA11: begin
         next_state = waittoact;
      end
      w_busy15: begin
         if (busy_p==1)
            next_state = st_GPIOA1;
         else
            next_state = w_busy15;
      end
      w_busy16: begin
         if (busy_p==1)
            next_state = st_GPIOA2;
         else
            next_state = w_busy16;
      end
      w_busy17: begin
         if (busy_p==1)
            next_state = CS_high5;
         else
            next_state = w_busy17;
      end
      ST_IODIRA0: begin
         next_state = w_busy0;
      end
      w_busy0: begin
         if (busy_p==1)
            next_state = ST_IODIRA1;
         else
            next_state = w_busy0;
      end
      ST_IODIRA1: begin
         next_state = w_busy1;
      end
      w_busy1: begin
         if (busy_p==1)
            next_state = ST_IODIRA2;
         else
            next_state = w_busy1;
      end
      ST_IODIRA2: begin
         next_state = w_busy2;
      end
      w_busy2: begin
         if (busy_p==1)
            next_state = CS_high0;
         else
            next_state = w_busy2;
      end
      w_busy5: begin
         if (busy_p==1)
            next_state = CS_high1;
         else
            next_state = w_busy5;
      end
      st_IODIRB1: begin
         next_state = w_busy4;
      end
      st_IODIRB2: begin
         next_state = w_busy5;
      end
      st_IODIRB: begin
         next_state = w_busy3;
      end
      w_busy3: begin
         if (busy_p==1)
            next_state = st_IODIRB1;
         else
            next_state = w_busy3;
      end
      w_busy4: begin
         if (busy_p==1)
            next_state = st_IODIRB2;
         else
            next_state = w_busy4;
      end
      w_busy7: begin
         if (busy_p==1)
            next_state = st_GPIOB2;
         else
            next_state = w_busy7;
      end
      st_GPIOB2: begin
         next_state = w_busy8;
      end
      st_GPIOB1: begin
         next_state = w_busy7;
      end
      w_busy8: begin
         if (busy_p==1)
            next_state = CS_high2;
         else
            next_state = w_busy8;
      end
      w_busy6: begin
         if (busy_p==1)
            next_state = st_GPIOB1;
         else
            next_state = w_busy6;
      end
      st_GPIOB0: begin
         next_state = w_busy6;
      end
      st_GPPUA: begin
         next_state = w_busy9;
      end
      w_busy11: begin
         if (busy_p==1)
            next_state = st_GPPUA2;
         else
            next_state = w_busy11;
      end
      w_busy9: begin
         if (busy_p==1)
            next_state = st_GPPUA1;
         else
            next_state = w_busy9;
      end
      st_GPPUA2: begin
         next_state = w_busy10;
      end
      st_GPPUA1: begin
         next_state = w_busy11;
      end
      w_busy10: begin
         if (busy_p==1)
            next_state = CS_high3;
         else
            next_state = w_busy10;
      end
      st_GPPUB1: begin
         next_state = w_busy13;
      end
      w_busy13: begin
         if (busy_p==1)
            next_state = st_GPPUB2;
         else
            next_state = w_busy13;
      end
      w_busy12: begin
         if (busy_p==1)
            next_state = st_GPPUB1;
         else
            next_state = w_busy12;
      end
      st_GPPUB2: begin
         next_state = w_busy14;
      end
      w_busy14: begin
         if (busy_p==1)
            next_state = CS_high4;
         else
            next_state = w_busy14;
      end
      st_GPPUB: begin
         next_state = w_busy12;
      end
      CS_high0: begin
         next_state = w_busy26;
      end
      CS_high1: begin
         next_state = w_busy27;
      end
      CS_high2: begin
         next_state = w_busy28;
      end
      CS_high3: begin
         next_state = w_busy29;
      end
      CS_high4: begin
         next_state = w_busy30;
      end
      CS_high5: begin
         next_state = w_busy31;
      end
      start2: begin
         next_state = ST_IODIRA4;
      end
      End_Select1: begin
         next_state = waittoact;
      end
      CS_high6: begin
         next_state = w_busy24;
      end
      CS_high11: begin
         next_state = w_busy25;
      end
      st_GPIOA12: begin
         next_state = w_busy18;
      end
      st_GPIOA13: begin
         next_state = w_busy19;
      end
      st_GPIOA14: begin
         next_state = w_busy20;
      end
      w_busy18: begin
         if (busy_p==1)
            next_state = st_GPIOA13;
         else
            next_state = w_busy18;
      end
      w_busy19: begin
         if (busy_p==1)
            next_state = st_GPIOA14;
         else
            next_state = w_busy19;
      end
      w_busy20: begin
         if (busy_p==1)
            next_state = CS_high11;
         else
            next_state = w_busy20;
      end
      ST_IODIRA4: begin
         next_state = w_busy21;
      end
      ST_IODIRA5: begin
         next_state = w_busy22;
      end
      ST_IODIRA6: begin
         next_state = w_busy23;
      end
      w_busy21: begin
         if (busy_p==1)
            next_state = ST_IODIRA5;
         else
            next_state = w_busy21;
      end
      w_busy22: begin
         if (busy_p==1)
            next_state = ST_IODIRA6;
         else
            next_state = w_busy22;
      end
      w_busy23: begin
         if (busy_p==1)
            next_state = CS_high6;
         else
            next_state = w_busy23;
      end
      w_busy24: begin
         if (busy_p==1)
            next_state = st_GPIOA12;
         else
            next_state = w_busy24;
      end
      w_busy25: begin
         if (busy_p==1)
            next_state = End_Select1;
         else
            next_state = w_busy25;
      end
      w_busy26: begin
         if (busy_p==1)
            next_state = st_IODIRB;
         else
            next_state = w_busy26;
      end
      w_busy27: begin
         if (busy_p==1)
            next_state = st_GPIOB0;
         else
            next_state = w_busy27;
      end
      w_busy28: begin
         if (busy_p==1)
            next_state = st_GPPUA;
         else
            next_state = w_busy28;
      end
      w_busy29: begin
         if (busy_p==1)
            next_state = st_GPPUB;
         else
            next_state = w_busy29;
      end
      w_busy30: begin
         if (busy_p==1)
            next_state = st_GPIOA;
         else
            next_state = w_busy30;
      end
      w_busy31: begin
         if (busy_p==1)
            next_state = End_Select;
         else
            next_state = w_busy31;
      end
      default: 
         next_state = reset;
   endcase
end // Next State Block

//-----------------------------------------------------------------
// Output Block for machine csm
//-----------------------------------------------------------------
always @(
   current_state
)
begin : output_block_proc
   // Default Assignment
   addr = 5'b0;
   bus_en_done = 0;
   cs_m = 1;
   cs_p = 1;
   end_spi_proc = 0;
   entimeout = 1;
   mon_en_done = 0;
   read_spi_mode = 0;
   spi_cs = 1;
   start_cnt = 0;
   start_init = 0;
   start_read_elink = 0;
   start_read_miso = 0;
   start_write_elink_spi = 0;
   transcieve_p = 0;

   // Combined Actions
   case (current_state) 
      waittoact: begin
         entimeout =0;
      end
      reset: begin
         read_spi_mode =0;
      end
      start: begin
         start_init =1;
      end
      ST_Init_1: begin
         addr = 5'h1;
         cs_m = 0 ;
      end
      st_Init_2: begin
         addr = 5'h2;
         cs_m = 0 ;
      end
      endinit1: begin
         mon_en_done=1;
      end
      start1: begin
         start_init =1;
      end
      St_wait1: begin
         cs_m = 0 ;
      end
      St_wait2: begin
         cs_m = 0 ;
      end
      ST_Read_reg: begin
         addr = 5'h7;
         cs_m = 0 ;
      end
      ST_Read_RS_3: begin
         addr = 5'h4;
         cs_m = 0 ;
      end
      ST_Read_reg1: begin
         addr = 5'h7;
         cs_m = 0 ;
      end
      ST_Read_RS_4: begin
         addr = 5'h4;
         cs_m = 0 ;
      end
      St_wait3: begin
         cs_m = 0 ;
      end
      st_GPIOA: begin
         addr = 5'h13;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_GPIOA1: begin
         addr = 5'h1B;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_GPIOA2: begin
         addr = 5'h14;
         cs_p = 0 ;
         transcieve_p =1;
      end
      End_Select: begin
         bus_en_done =1;
      end
      st_GPIOA3: begin
         addr = 5'h13;
         cs_p = 0 ;
      end
      st_GPIOA4: begin
         addr = 5'h1B;
         cs_p = 0 ;
      end
      st_GPIOA5: begin
         addr = 5'h14;
         cs_p = 0 ;
      end
      st_GPIOA6: begin
         addr = 5'h13;
         cs_p = 0 ;
      end
      st_GPIOA7: begin
         addr = 5'h1B;
         cs_p = 0 ;
      end
      st_GPIOA8: begin
         addr = 5'h1A;
         cs_p = 0 ;
      end
      ST_Read_reg5: begin
         addr = 5'h7;
         cs_m = 0 ;
      end
      ST_Read_RS_8: begin
         addr = 5'h4;
         cs_m = 0 ;
      end
      Write_Mosi: begin
         spi_cs =0;
         read_spi_mode =1;
      end
      read_elink_mes1: begin
         start_read_elink = 1 ;
         read_spi_mode =1;
      end
      CS_low: begin
         spi_cs = 0;
         read_spi_mode =1;
      end
      Read_Miso: begin
         start_read_miso =1;
         spi_cs = 0;
         read_spi_mode =1;
      end
      Done: begin
         end_spi_proc =1;
         read_spi_mode =1;
      end
      write_elink: begin
         start_write_elink_spi =1;
         read_spi_mode =1;
      end
      Wait_Miso: begin
         read_spi_mode =1;
      end
      St_wait4: begin
         cs_m = 0 ;
      end
      St_wait11: begin
         cs_m = 0 ;
      end
      Offset_calibrate0: begin
         addr = 5'hF ;
         cs_m =0 ;
      end
      Offset__calibrate1: begin
         addr = 5'h10 ;
         cs_m =0 ;
      end
      Offset__calibrate2: begin
         addr = 5'h11 ;
         cs_m =0 ;
      end
      Offset__calibrate3: begin
         addr = 5'h12 ;
         cs_m =0 ;
      end
      s0: begin
         cs_m =0 ;
      end
      s1: begin
         cs_m =0 ;
      end
      s2: begin
         cs_m =0 ;
      end
      Gain_calibrate0: begin
         addr = 5'h1C ;
         cs_m =0 ;
      end
      Gain_calibrate1: begin
         addr = 5'h1D ;
         cs_m =0 ;
      end
      Gain_calibrate2: begin
         addr = 5'h1E ;
         cs_m =0 ;
      end
      Gain_calibrate3: begin
         addr = 5'h1F ;
         cs_m =0 ;
      end
      s3: begin
         cs_m =0 ;
      end
      s4: begin
         cs_m =0 ;
      end
      s5: begin
         cs_m =0 ;
      end
      s6: begin
         cs_m =0 ;
      end
      write_csrs7: begin
         addr = 5'hB;
         cs_m = 0 ;
      end
      write_csrs6: begin
         addr = 5'hD;
         cs_m = 0 ;
      end
      write_csrs5: begin
         addr = 5'hC;
         cs_m = 0 ;
      end
      write_csrs4: begin
         addr = 5'hB;
         cs_m = 0 ;
      end
      write_csrs0: begin
         addr = 5'h9;
         cs_m = 0 ;
      end
      write_csrs1: begin
         addr = 5'h4;
         cs_m = 0 ;
      end
      write_csrs2: begin
         addr = 5'hA;
         cs_m = 0 ;
      end
      ST_Config4: begin
         addr = 5'h4 ;
         cs_m = 0 ;
      end
      ST_Config3: begin
         addr = 5'h8 ;
         cs_m = 0 ;
      end
      ST_Config1: begin
         addr = 5'h3 ;
         cs_m = 0 ;
      end
      ST_Config2: begin
         addr = 5'h4 ;
         cs_m = 0 ;
      end
      ST_Rest_2: begin
         addr = 5'h4;
         cs_m = 0 ;
      end
      ST_Rest_4: begin
         addr = 5'h5;
         cs_m = 0 ;
      end
      ST_Rest_1: begin
         addr = 5'h3;
         cs_m = 0 ;
      end
      St_wait: begin
         cs_m = 0 ;
      end
      ST_Rest_RS_1: begin
         addr = 5'h3;
         cs_m = 0 ;
      end
      ST_Rest_RS_2: begin
         addr = 5'h4;
         cs_m = 0 ;
      end
      st_GPIOA9: begin
         addr = 5'h13;
         cs_p = 0 ;
      end
      st_GPIOA10: begin
         addr = 5'h1B;
         cs_p = 0 ;
      end
      st_GPIOA11: begin
         addr = 5'h1A;
         cs_p = 0 ;
      end
      w_busy15: begin
         cs_p = 0 ;
         addr = 5'h13;
      end
      w_busy16: begin
         cs_p = 0 ;
         addr = 5'h1B;
      end
      w_busy17: begin
         cs_p = 0 ;
         addr = 5'h14;
      end
      ST_IODIRA0: begin
         addr = 5'h13;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy0: begin
         cs_p =0;
         addr = 5'h13;
      end
      ST_IODIRA1: begin
         addr = 5'h1A;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy1: begin
         cs_p =0;
         addr = 5'h1A;
      end
      ST_IODIRA2: begin
         addr = 5'h1A;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy2: begin
         addr = 5'h1A;
         cs_p =0;
      end
      w_busy5: begin
         addr = 5'h1A;
         cs_p =0;
      end
      st_IODIRB1: begin
         addr = 5'h14;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_IODIRB2: begin
         addr = 5'h1A;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_IODIRB: begin
         addr = 5'h13;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy3: begin
         cs_p =0;
         addr = 5'h13;
      end
      w_busy4: begin
         cs_p =0;
         addr = 5'h14;
      end
      w_busy7: begin
         cs_p =0;
         addr = 5'h15;
      end
      st_GPIOB2: begin
         addr = 5'h1A;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_GPIOB1: begin
         addr = 5'h15;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy8: begin
         cs_p = 0 ;
         addr = 5'h1A;
      end
      w_busy6: begin
         cs_p =0;
         addr = 5'h13;
      end
      st_GPIOB0: begin
         addr = 5'h13;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_GPPUA: begin
         addr = 5'h13;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy11: begin
         cs_p = 0 ;
         addr = 5'h18;
      end
      w_busy9: begin
         cs_p = 0 ;
         addr = 5'h13;
      end
      st_GPPUA2: begin
         addr = 5'h18;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_GPPUA1: begin
         addr = 5'h16;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy10: begin
         cs_p =0;
         addr = 5'h16;
      end
      st_GPPUB1: begin
         addr = 5'h17;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy13: begin
         cs_p = 0 ;
         addr = 5'h17;
      end
      w_busy12: begin
         cs_p = 0 ;
         addr = 5'h13;
      end
      st_GPPUB2: begin
         addr = 5'h19;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy14: begin
         cs_p = 0 ;
         addr = 5'h19;
      end
      st_GPPUB: begin
         addr = 5'h13;
         cs_p = 0 ;
         transcieve_p =1;
      end
      CS_high0: begin
         cs_p =1;
         transcieve_p =1;
      end
      CS_high1: begin
         cs_p =1;
         transcieve_p =1;
      end
      CS_high2: begin
         cs_p =1;
         transcieve_p =1;
      end
      CS_high3: begin
         cs_p =1;
         transcieve_p =1;
      end
      CS_high4: begin
         cs_p =1;
         transcieve_p =1;
      end
      CS_high5: begin
         cs_p =1;
         transcieve_p =1;
      end
      start2: begin
         start_init =1;
      end
      End_Select1: begin
         bus_en_done =1;
      end
      CS_high6: begin
         cs_p =1;
         transcieve_p =1;
      end
      CS_high11: begin
         cs_p =1;
         transcieve_p =1;
      end
      st_GPIOA12: begin
         addr = 5'h13;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_GPIOA13: begin
         addr = 5'h1B;
         cs_p = 0 ;
         transcieve_p =1;
      end
      st_GPIOA14: begin
         addr = 5'h14;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy18: begin
         cs_p = 0 ;
         addr = 5'h13;
      end
      w_busy19: begin
         cs_p = 0 ;
         addr = 5'h1B;
      end
      w_busy20: begin
         cs_p = 0 ;
         addr = 5'h14;
      end
      ST_IODIRA4: begin
         addr = 5'h13;
         cs_p = 0 ;
         transcieve_p =1;
      end
      ST_IODIRA5: begin
         addr = 5'h1A;
         cs_p = 0 ;
         transcieve_p =1;
      end
      ST_IODIRA6: begin
         addr = 5'h1A;
         cs_p = 0 ;
         transcieve_p =1;
      end
      w_busy21: begin
         cs_p = 0 ;
         addr = 5'h13;
      end
      w_busy22: begin
         cs_p = 0 ;
         addr = 5'h1A;
      end
      w_busy23: begin
         cs_p = 0 ;
         addr = 5'h1A;
      end
      w_busy24: begin
         cs_p = 1 ;
      end
      w_busy25: begin
         cs_p = 1 ;
      end
      w_busy26: begin
         cs_p = 1 ;
      end
      w_busy27: begin
         cs_p = 1 ;
      end
      w_busy28: begin
         cs_p = 1 ;
      end
      w_busy29: begin
         cs_p = 1 ;
      end
      w_busy30: begin
         cs_p = 1 ;
      end
      w_busy31: begin
         cs_p = 1 ;
      end
   endcase
end // Output Block

//-----------------------------------------------------------------
// Clocked Block for machine csm
//-----------------------------------------------------------------
always @(
   posedge clk
) 
begin : clocked_block_proc
   if (!rst) begin
      current_state <= reset;
      csm_timer <= 6'd0;
   end
   else if (timeoutrst) begin
      current_state <= reset;
      csm_timer <= 6'd0;
   end
   else if (abort) begin
      current_state <= reset;
      csm_timer <= 6'd0;
   end
   else 
   begin
      current_state <= next_state;
      csm_timer <= csm_next_timer;
   end
end // Clocked Block

//-----------------------------------------------------------------
// Wait state logic for machine csm
//-----------------------------------------------------------------
always @(
   csm_timer,
   csm_to_ST_Init_1,
   csm_to_ST_Read_RS_3,
   csm_to_ST_Read_RS_4,
   csm_to_ST_Read_RS_8,
   csm_to_CS_low,
   csm_to_Read_Miso,
   csm_to_s0,
   csm_to_s1,
   csm_to_s2,
   csm_to_s3,
   csm_to_s4,
   csm_to_s5,
   csm_to_s6,
   csm_to_ST_Rest_2,
   csm_to_ST_Rest_RS_2
)
begin : csm_wait_block_proc
   csm_timeout = (csm_timer == 6'd0);
   if (csm_to_ST_Init_1 == 1'b1) begin
      csm_next_timer = 6'd14;  //no cycles(15)-1=14
   end
   else if (csm_to_ST_Read_RS_3 == 1'b1) begin
      csm_next_timer = 6'd2;  //no cycles(3)-1=2
   end
   else if (csm_to_ST_Read_RS_4 == 1'b1) begin
      csm_next_timer = 6'd2;  //no cycles(3)-1=2
   end
   else if (csm_to_ST_Read_RS_8 == 1'b1) begin
      csm_next_timer = 6'd2;  //no cycles(3)-1=2
   end
   else if (csm_to_CS_low == 1'b1) begin
      csm_next_timer = 6'd9;  //no cycles(10)-1=9
   end
   else if (csm_to_Read_Miso == 1'b1) begin
      csm_next_timer = 6'd39;  //no cycles(40)-1=39
   end
   else if (csm_to_s0 == 1'b1) begin
      csm_next_timer = 6'd1;  //no cycles(2)-1=1
   end
   else if (csm_to_s1 == 1'b1) begin
      csm_next_timer = 6'd1;  //no cycles(2)-1=1
   end
   else if (csm_to_s2 == 1'b1) begin
      csm_next_timer = 6'd1;  //no cycles(2)-1=1
   end
   else if (csm_to_s3 == 1'b1) begin
      csm_next_timer = 6'd1;  //no cycles(2)-1=1
   end
   else if (csm_to_s4 == 1'b1) begin
      csm_next_timer = 6'd1;  //no cycles(2)-1=1
   end
   else if (csm_to_s5 == 1'b1) begin
      csm_next_timer = 6'd1;  //no cycles(2)-1=1
   end
   else if (csm_to_s6 == 1'b1) begin
      csm_next_timer = 6'd1;  //no cycles(2)-1=1
   end
   else if (csm_to_ST_Rest_2 == 1'b1) begin
      csm_next_timer = 6'd1;  //no cycles(2)-1=1
   end
   else if (csm_to_ST_Rest_RS_2 == 1'b1) begin
      csm_next_timer = 6'd2;  //no cycles(3)-1=2
   end
   else begin
      csm_next_timer = (csm_timeout)? 6'd0: (csm_timer - 6'd1);
   end
end // Wait State Block
// State-As-Output assignment
always @(current_state)
statedeb = current_state;

endmodule // bus_control_SM
