//
// Module mopshub_lib.canakari_top.struct
//
// Created:
//          by - dcs.dcs (chipdev2.physik.uni-wuppertal.de)
//          at - 10:11:45 01/19/22
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//

`resetall
`timescale 1ns/10ps
module canakari_top( 
   // Port Declarations
   input   wire            clk, 
   input   wire            rst, 
   input   wire    [4:0]   address, 
   input   wire    [4:0]   bus_tra_select, 
   input   wire    [15:0]  writedata, 
   input   wire            write_n_sig, 
   output  wire            irq_can_tra, 
   output  wire            irq_can_rec, 
   input   wire            rx10, 
   input   wire            rx18, 
   input   wire            rx26, 
   input   wire            rx2, 
   input   wire            rx11, 
   input   wire            rx19, 
   input   wire            rx27, 
   input   wire            rx3, 
   input   wire            rx13, 
   input   wire            rx21, 
   input   wire            rx29, 
   input   wire            rx5, 
   input   wire            rx14, 
   input   wire            rx22, 
   input   wire            rx30, 
   input   wire            rx6, 
   input   wire            rx15, 
   input   wire            rx23, 
   input   wire            rx31, 
   input   wire            rx7, 
   output  wire            tx9, 
   output  wire            tx17, 
   output  wire            tx25, 
   output  wire            tx1, 
   output  wire            tx10, 
   output  wire            tx18, 
   output  wire            tx26, 
   output  wire            tx2, 
   output  wire            tx11, 
   output  wire            tx19, 
   output  wire            tx27, 
   output  wire            tx3, 
   output  wire            tx13, 
   output  wire            tx21, 
   output  wire            tx29, 
   output  wire            tx5, 
   output  wire            tx22, 
   output  wire            tx30, 
   output  wire            tx6, 
   output  wire            tx14, 
   output  wire            tx23, 
   output  wire            tx31, 
   output  wire            tx7, 
   output  wire            tx15, 
   input   wire            rx17, 
   input   wire            rx25, 
   input   wire            rx1, 
   input   wire            rx9, 
   output  wire    [4:0]   bus_rec_select, 
   input   wire            endwait, 
   input   wire            read_n_sig, 
   input   wire            enable_cs_sig, 
   output  wire    [15:0]  readdata, 
   input   wire            rx16, 
   input   wire            rx24, 
   input   wire            rx0, 
   input   wire            rx8, 
   output  wire            tx8, 
   output  wire            tx16, 
   output  wire            tx24, 
   output  wire            tx0, 
   output  wire            canakari_entimeout, 
   input   wire            main_timeoutrst, 
   input   wire            rx20, 
   input   wire            rx28, 
   input   wire            rx4, 
   input   wire            rx12, 
   output  wire            tx12, 
   output  wire            tx28, 
   output  wire            tx4, 
   output  wire            tx20
);


// Internal Declarations


// Local declarations

// Internal signal declarations
wire         irqsucrec8;
wire         irqsucrec16;
wire         irqsucrec0;
wire         irqsucrec9;
wire         irqsucrec17;
wire         irqsucrec1;
wire         irqsucrec10;
wire         irqsucrec18;
wire         irqsucrec2;
wire         irqsucrec11;
wire         irqsucrec19;
wire         irqsucrec3;
wire         irqsucrec13;
wire         irqsucrec21;
wire         irqsucrec5;
wire         irqsucrec15;
wire         irqsucrec23;
wire         irqsucrec7;
wire         irqsucrec14;
wire         irqsucrec22;
wire         irqsucrec6;
wire         read_n8;
wire         read_n16;
wire         read_n0;
wire         read_n9;
wire         read_n17;
wire         read_n1;
wire         read_n10;
wire         read_n18;
wire         read_n2;
wire         read_n11;
wire         read_n19;
wire         read_n3;
wire         read_n13;
wire         read_n21;
wire         read_n5;
wire         read_n14;
wire         read_n22;
wire         read_n6;
wire         read_n15;
wire         read_n23;
wire         read_n7;
wire         write_n8;
wire         write_n16;
wire         write_n0;
wire         irqsuctra1;
wire         irqsuctra2;
wire         irqsuctra3;
wire         irqsuctra4;
wire         irqsuctra5;
wire         irqsuctra6;
wire         irqsuctra7;
wire         irqsuctra0;
wire  [15:0] writedata8;
wire  [15:0] writedata16;
wire  [15:0] writedata0;
wire  [15:0] writedata9;
wire  [15:0] writedata17;
wire  [15:0] writedata1;
wire  [15:0] writedata10;
wire  [15:0] writedata18;
wire  [15:0] writedata2;
wire  [15:0] writedata11;
wire  [15:0] writedata19;
wire  [15:0] writedata3;
wire  [15:0] writedata12;
wire  [15:0] writedata20;
wire  [15:0] writedata4;
wire  [15:0] writedata13;
wire  [15:0] writedata21;
wire  [15:0] writedata5;
wire  [15:0] writedata14;
wire  [15:0] writedata22;
wire  [15:0] writedata6;
wire  [15:0] writedata15;
wire  [15:0] writedata23;
wire  [15:0] writedata7;
wire         write_n9;
wire         write_n17;
wire         write_n1;
wire         write_n10;
wire         write_n18;
wire         write_n2;
wire         write_n11;
wire         write_n19;
wire         write_n3;
wire         write_n12;
wire         write_n20;
wire         write_n4;
wire         write_n13;
wire         write_n21;
wire         write_n5;
wire         write_n14;
wire         write_n6;
wire         write_n22;
wire         write_n15;
wire         write_n7;
wire         write_n23;
wire         cs8;
wire         cs16;
wire         cs24;
wire         cs0;
wire         cs_rec0;
wire         cs_rec1;
wire         cs_rec2;
wire         cs_rec3;
wire         cs_rec4;
wire         cs_rec5;
wire         cs_rec6;
wire         cs_rec7;
wire         cs_tra0;
wire         ireqsucrec;
wire         cs9;
wire         cs17;
wire         cs25;
wire         cs1;
wire         cs10;
wire         cs18;
wire         cs26;
wire         cs2;
wire         cs13;
wire         cs21;
wire         cs29;
wire         cs5;
wire         cs14;
wire         cs22;
wire         cs30;
wire         cs6;
wire         cs15;
wire         cs23;
wire         cs31;
wire         cs7;
wire         cs12;
wire         cs20;
wire         cs28;
wire         cs4;
wire         cs11;
wire         cs19;
wire         cs27;
wire         cs3;
wire         cs_tra1;
wire         cs_tra2;
wire         cs_tra3;
wire         cs_tra4;
wire         cs_tra5;
wire         cs_tra6;
wire         cs_tra7;
wire         irqsuctra10;
wire         irqsuctra11;
wire         irqsuctra12;
wire         irqsuctra13;
wire         irqsuctra14;
wire         irqsuctra16;
wire         irqsuctra17;
wire         irqsuctra18;
wire         irqsuctra19;
wire         irqsuctra20;
wire         irqsuctra21;
wire         irqsuctra22;
wire         irqsuctra23;
wire         irqsuctra8;
wire         irqsuctra9;
wire         irqsucrec12;
wire         irqsucrec20;
wire         irqsucrec4;
wire         read_n12;
wire         read_n4;
wire         read_n20;
wire  [15:0] readdata12;
wire  [15:0] readdata20;
wire  [15:0] readdata4;
wire  [15:0] readdata5;
wire  [15:0] readdata21;
wire  [15:0] readdata13;
wire  [15:0] readdata0;
wire  [15:0] readdata16;
wire  [15:0] readdata8;
wire  [15:0] readdata1;
wire  [15:0] readdata17;
wire  [15:0] readdata9;
wire  [15:0] readdata2;
wire  [15:0] readdata18;
wire  [15:0] readdata10;
wire  [15:0] readdata3;
wire  [15:0] readdata19;
wire  [15:0] readdata11;
wire  [15:0] readdata6;
wire  [15:0] readdata22;
wire  [15:0] readdata14;
wire  [15:0] readdata7;
wire  [15:0] readdata23;
wire  [15:0] readdata15;
wire         cs_rec10;
wire         cs_rec11;
wire         cs_rec12;
wire         cs_rec13;
wire         cs_rec14;
wire         cs_rec15;
wire         cs_rec8;
wire         cs_rec9;
wire         cs_tra10;
wire         cs_tra11;
wire         cs_tra12;
wire         cs_tra13;
wire         cs_tra14;
wire         cs_tra15;
wire         cs_tra8;
wire         cs_tra9;
wire         irqsuctra15;
wire         cs_rec16;
wire         cs_rec17;
wire         cs_rec18;
wire         cs_rec19;
wire         cs_rec20;
wire         cs_rec21;
wire         cs_rec22;
wire         cs_rec23;
wire         cs_tra16;
wire         cs_tra17;
wire         cs_tra18;
wire         cs_tra19;
wire         cs_tra20;
wire         cs_tra21;
wire         cs_tra22;
wire         cs_tra23;
wire         cs_tra24;
wire         cs_tra25;
wire         cs_tra26;
wire         cs_tra27;
wire         cs_tra28;
wire         cs_tra29;
wire         cs_tra30;
wire         cs_tra31;
wire         write_n24;
wire         write_n25;
wire         write_n26;
wire         write_n27;
wire         write_n28;
wire         write_n29;
wire         write_n30;
wire         write_n31;
wire  [15:0] writedata24;
wire  [15:0] writedata25;
wire  [15:0] writedata26;
wire  [15:0] writedata27;
wire  [15:0] writedata28;
wire  [15:0] writedata29;
wire  [15:0] writedata30;
wire  [15:0] writedata31;
wire         irqsuctra24;
wire         irqsuctra25;
wire         irqsuctra26;
wire         irqsuctra27;
wire         irqsuctra28;
wire         irqsuctra29;
wire         irqsuctra30;
wire         irqsuctra31;
wire  [15:0] readdata24;
wire  [15:0] readdata25;
wire  [15:0] readdata26;
wire  [15:0] readdata27;
wire  [15:0] readdata28;
wire  [15:0] readdata29;
wire  [15:0] readdata30;
wire  [15:0] readdata31;
wire         read_n24;
wire         read_n25;
wire         read_n26;
wire         read_n27;
wire         read_n28;
wire         read_n29;
wire         read_n30;
wire         read_n31;
wire         cs_rec24;
wire         cs_rec25;
wire         cs_rec26;
wire         cs_rec27;
wire         cs_rec28;
wire         cs_rec29;
wire         cs_rec30;
wire         cs_rec31;
wire         irqsucrec24;
wire         irqsucrec25;
wire         irqsucrec26;
wire         irqsucrec27;
wire         irqsucrec28;
wire         irqsucrec29;
wire         irqsucrec30;
wire         irqsucrec31;


// Instances 
canakari_0_7 cancari_block0_7( 
   .address    (address), 
   .clk        (clk), 
   .cs0        (cs0), 
   .cs1        (cs1), 
   .cs2        (cs2), 
   .cs3        (cs3), 
   .cs4        (cs4), 
   .cs5        (cs5), 
   .cs6        (cs6), 
   .cs7        (cs7), 
   .read_n0    (read_n0), 
   .read_n1    (read_n1), 
   .read_n2    (read_n2), 
   .read_n3    (read_n3), 
   .read_n4    (read_n4), 
   .read_n5    (read_n5), 
   .read_n6    (read_n6), 
   .read_n7    (read_n7), 
   .rst        (rst), 
   .rx0        (rx0), 
   .rx1        (rx1), 
   .rx2        (rx2), 
   .rx3        (rx3), 
   .rx4        (rx4), 
   .rx5        (rx5), 
   .rx6        (rx6), 
   .rx7        (rx7), 
   .write_n0   (write_n0), 
   .write_n1   (write_n1), 
   .write_n2   (write_n2), 
   .write_n3   (write_n3), 
   .write_n4   (write_n4), 
   .write_n5   (write_n5), 
   .write_n6   (write_n6), 
   .write_n7   (write_n7), 
   .writedata0 (writedata0), 
   .writedata1 (writedata1), 
   .writedata2 (writedata2), 
   .writedata3 (writedata3), 
   .writedata4 (writedata4), 
   .writedata5 (writedata5), 
   .writedata6 (writedata6), 
   .writedata7 (writedata7), 
   .irqsucrec0 (irqsucrec0), 
   .irqsucrec1 (irqsucrec1), 
   .irqsucrec2 (irqsucrec2), 
   .irqsucrec3 (irqsucrec3), 
   .irqsucrec4 (irqsucrec4), 
   .irqsucrec5 (irqsucrec5), 
   .irqsucrec6 (irqsucrec6), 
   .irqsucrec7 (irqsucrec7), 
   .irqsuctra0 (irqsuctra0), 
   .irqsuctra1 (irqsuctra1), 
   .irqsuctra2 (irqsuctra2), 
   .irqsuctra3 (irqsuctra3), 
   .irqsuctra4 (irqsuctra4), 
   .irqsuctra5 (irqsuctra5), 
   .irqsuctra6 (irqsuctra6), 
   .irqsuctra7 (irqsuctra7), 
   .readdata0  (readdata0), 
   .readdata1  (readdata1), 
   .readdata2  (readdata2), 
   .readdata3  (readdata3), 
   .readdata4  (readdata4), 
   .readdata5  (readdata5), 
   .readdata6  (readdata6), 
   .readdata7  (readdata7), 
   .tx0        (tx0), 
   .tx1        (tx1), 
   .tx2        (tx2), 
   .tx3        (tx3), 
   .tx4        (tx4), 
   .tx5        (tx5), 
   .tx6        (tx6), 
   .tx7        (tx7)
); 

canakari_0_7 cancari_block8_15( 
   .address    (address), 
   .clk        (clk), 
   .cs0        (cs8), 
   .cs1        (cs9), 
   .cs2        (cs10), 
   .cs3        (cs11), 
   .cs4        (cs12), 
   .cs5        (cs13), 
   .cs6        (cs14), 
   .cs7        (cs15), 
   .read_n0    (read_n8), 
   .read_n1    (read_n9), 
   .read_n2    (read_n10), 
   .read_n3    (read_n11), 
   .read_n4    (read_n12), 
   .read_n5    (read_n13), 
   .read_n6    (read_n14), 
   .read_n7    (read_n15), 
   .rst        (rst), 
   .rx0        (rx8), 
   .rx1        (rx9), 
   .rx2        (rx10), 
   .rx3        (rx11), 
   .rx4        (rx12), 
   .rx5        (rx13), 
   .rx6        (rx14), 
   .rx7        (rx15), 
   .write_n0   (write_n8), 
   .write_n1   (write_n9), 
   .write_n2   (write_n10), 
   .write_n3   (write_n11), 
   .write_n4   (write_n12), 
   .write_n5   (write_n13), 
   .write_n6   (write_n14), 
   .write_n7   (write_n15), 
   .writedata0 (writedata8), 
   .writedata1 (writedata9), 
   .writedata2 (writedata10), 
   .writedata3 (writedata11), 
   .writedata4 (writedata12), 
   .writedata5 (writedata13), 
   .writedata6 (writedata14), 
   .writedata7 (writedata15), 
   .irqsucrec0 (irqsucrec8), 
   .irqsucrec1 (irqsucrec9), 
   .irqsucrec2 (irqsucrec10), 
   .irqsucrec3 (irqsucrec11), 
   .irqsucrec4 (irqsucrec12), 
   .irqsucrec5 (irqsucrec13), 
   .irqsucrec6 (irqsucrec14), 
   .irqsucrec7 (irqsucrec15), 
   .irqsuctra0 (irqsuctra8), 
   .irqsuctra1 (irqsuctra9), 
   .irqsuctra2 (irqsuctra10), 
   .irqsuctra3 (irqsuctra11), 
   .irqsuctra4 (irqsuctra12), 
   .irqsuctra5 (irqsuctra13), 
   .irqsuctra6 (irqsuctra14), 
   .irqsuctra7 (irqsuctra15), 
   .readdata0  (readdata8), 
   .readdata1  (readdata9), 
   .readdata2  (readdata10), 
   .readdata3  (readdata11), 
   .readdata4  (readdata12), 
   .readdata5  (readdata13), 
   .readdata6  (readdata14), 
   .readdata7  (readdata15), 
   .tx0        (tx8), 
   .tx1        (tx9), 
   .tx2        (tx10), 
   .tx3        (tx11), 
   .tx4        (tx12), 
   .tx5        (tx13), 
   .tx6        (tx14), 
   .tx7        (tx15)
); 

canakari_0_7 cancari_block16_23( 
   .address    (address), 
   .clk        (clk), 
   .cs0        (cs16), 
   .cs1        (cs17), 
   .cs2        (cs18), 
   .cs3        (cs19), 
   .cs4        (cs20), 
   .cs5        (cs21), 
   .cs6        (cs22), 
   .cs7        (cs23), 
   .read_n0    (read_n16), 
   .read_n1    (read_n17), 
   .read_n2    (read_n18), 
   .read_n3    (read_n19), 
   .read_n4    (read_n20), 
   .read_n5    (read_n21), 
   .read_n6    (read_n22), 
   .read_n7    (read_n23), 
   .rst        (rst), 
   .rx0        (rx16), 
   .rx1        (rx17), 
   .rx2        (rx18), 
   .rx3        (rx19), 
   .rx4        (rx20), 
   .rx5        (rx21), 
   .rx6        (rx22), 
   .rx7        (rx23), 
   .write_n0   (write_n16), 
   .write_n1   (write_n17), 
   .write_n2   (write_n18), 
   .write_n3   (write_n19), 
   .write_n4   (write_n20), 
   .write_n5   (write_n21), 
   .write_n6   (write_n22), 
   .write_n7   (write_n23), 
   .writedata0 (writedata16), 
   .writedata1 (writedata17), 
   .writedata2 (writedata18), 
   .writedata3 (writedata19), 
   .writedata4 (writedata20), 
   .writedata5 (writedata21), 
   .writedata6 (writedata22), 
   .writedata7 (writedata23), 
   .irqsucrec0 (irqsucrec16), 
   .irqsucrec1 (irqsucrec17), 
   .irqsucrec2 (irqsucrec18), 
   .irqsucrec3 (irqsucrec19), 
   .irqsucrec4 (irqsucrec20), 
   .irqsucrec5 (irqsucrec21), 
   .irqsucrec6 (irqsucrec22), 
   .irqsucrec7 (irqsucrec23), 
   .irqsuctra0 (irqsuctra16), 
   .irqsuctra1 (irqsuctra17), 
   .irqsuctra2 (irqsuctra18), 
   .irqsuctra3 (irqsuctra19), 
   .irqsuctra4 (irqsuctra20), 
   .irqsuctra5 (irqsuctra21), 
   .irqsuctra6 (irqsuctra22), 
   .irqsuctra7 (irqsuctra23), 
   .readdata0  (readdata16), 
   .readdata1  (readdata17), 
   .readdata2  (readdata18), 
   .readdata3  (readdata19), 
   .readdata4  (readdata20), 
   .readdata5  (readdata21), 
   .readdata6  (readdata22), 
   .readdata7  (readdata23), 
   .tx0        (tx16), 
   .tx1        (tx17), 
   .tx2        (tx18), 
   .tx3        (tx19), 
   .tx4        (tx20), 
   .tx5        (tx21), 
   .tx6        (tx22), 
   .tx7        (tx23)
); 

canakari_0_7 cancari_block24_31( 
   .address    (address), 
   .clk        (clk), 
   .cs0        (cs24), 
   .cs1        (cs25), 
   .cs2        (cs26), 
   .cs3        (cs27), 
   .cs4        (cs28), 
   .cs5        (cs29), 
   .cs6        (cs30), 
   .cs7        (cs31), 
   .read_n0    (read_n24), 
   .read_n1    (read_n25), 
   .read_n2    (read_n26), 
   .read_n3    (read_n27), 
   .read_n4    (read_n28), 
   .read_n5    (read_n29), 
   .read_n6    (read_n30), 
   .read_n7    (read_n31), 
   .rst        (rst), 
   .rx0        (rx24), 
   .rx1        (rx25), 
   .rx2        (rx26), 
   .rx3        (rx27), 
   .rx4        (rx28), 
   .rx5        (rx29), 
   .rx6        (rx30), 
   .rx7        (rx31), 
   .write_n0   (write_n24), 
   .write_n1   (write_n25), 
   .write_n2   (write_n26), 
   .write_n3   (write_n27), 
   .write_n4   (write_n28), 
   .write_n5   (write_n29), 
   .write_n6   (write_n30), 
   .write_n7   (write_n31), 
   .writedata0 (writedata24), 
   .writedata1 (writedata25), 
   .writedata2 (writedata26), 
   .writedata3 (writedata27), 
   .writedata4 (writedata28), 
   .writedata5 (writedata29), 
   .writedata6 (writedata30), 
   .writedata7 (writedata31), 
   .irqsucrec0 (irqsucrec24), 
   .irqsucrec1 (irqsucrec25), 
   .irqsucrec2 (irqsucrec26), 
   .irqsucrec3 (irqsucrec27), 
   .irqsucrec4 (irqsucrec28), 
   .irqsucrec5 (irqsucrec29), 
   .irqsucrec6 (irqsucrec30), 
   .irqsucrec7 (irqsucrec31), 
   .irqsuctra0 (irqsuctra24), 
   .irqsuctra1 (irqsuctra25), 
   .irqsuctra2 (irqsuctra26), 
   .irqsuctra3 (irqsuctra27), 
   .irqsuctra4 (irqsuctra28), 
   .irqsuctra5 (irqsuctra29), 
   .irqsuctra6 (irqsuctra30), 
   .irqsuctra7 (irqsuctra31), 
   .readdata0  (readdata24), 
   .readdata1  (readdata25), 
   .readdata2  (readdata26), 
   .readdata3  (readdata27), 
   .readdata4  (readdata28), 
   .readdata5  (readdata29), 
   .readdata6  (readdata30), 
   .readdata7  (readdata31), 
   .tx0        (tx24), 
   .tx1        (tx25), 
   .tx2        (tx26), 
   .tx3        (tx27), 
   .tx4        (tx28), 
   .tx5        (tx29), 
   .tx6        (tx30), 
   .tx7        (tx31)
); 

node_rec_mux node_rec_mux0( 
   .clk                (clk), 
   .enable_cs_sig      (enable_cs_sig), 
   .endwait            (endwait), 
   .ireqsucrec         (ireqsucrec), 
   .irqsucrec0         (irqsucrec0), 
   .irqsucrec1         (irqsucrec1), 
   .irqsucrec10        (irqsucrec10), 
   .irqsucrec11        (irqsucrec11), 
   .irqsucrec12        (irqsucrec12), 
   .irqsucrec13        (irqsucrec13), 
   .irqsucrec14        (irqsucrec14), 
   .irqsucrec15        (irqsucrec15), 
   .irqsucrec16        (irqsucrec16), 
   .irqsucrec17        (irqsucrec17), 
   .irqsucrec18        (irqsucrec18), 
   .irqsucrec19        (irqsucrec19), 
   .irqsucrec2         (irqsucrec2), 
   .irqsucrec20        (irqsucrec20), 
   .irqsucrec21        (irqsucrec21), 
   .irqsucrec22        (irqsucrec22), 
   .irqsucrec23        (irqsucrec23), 
   .irqsucrec24        (irqsucrec24), 
   .irqsucrec25        (irqsucrec25), 
   .irqsucrec26        (irqsucrec26), 
   .irqsucrec27        (irqsucrec27), 
   .irqsucrec28        (irqsucrec28), 
   .irqsucrec29        (irqsucrec29), 
   .irqsucrec3         (irqsucrec3), 
   .irqsucrec30        (irqsucrec30), 
   .irqsucrec31        (irqsucrec31), 
   .irqsucrec4         (irqsucrec4), 
   .irqsucrec5         (irqsucrec5), 
   .irqsucrec6         (irqsucrec6), 
   .irqsucrec7         (irqsucrec7), 
   .irqsucrec8         (irqsucrec8), 
   .irqsucrec9         (irqsucrec9), 
   .main_timeoutrst    (main_timeoutrst), 
   .read_n_sig         (read_n_sig), 
   .readdata0          (readdata0), 
   .readdata1          (readdata1), 
   .readdata10         (readdata10), 
   .readdata11         (readdata11), 
   .readdata12         (readdata12), 
   .readdata13         (readdata13), 
   .readdata14         (readdata14), 
   .readdata15         (readdata15), 
   .readdata16         (readdata16), 
   .readdata17         (readdata17), 
   .readdata18         (readdata18), 
   .readdata19         (readdata19), 
   .readdata2          (readdata2), 
   .readdata20         (readdata20), 
   .readdata21         (readdata21), 
   .readdata22         (readdata22), 
   .readdata23         (readdata23), 
   .readdata24         (readdata24), 
   .readdata25         (readdata25), 
   .readdata26         (readdata26), 
   .readdata27         (readdata27), 
   .readdata28         (readdata28), 
   .readdata29         (readdata29), 
   .readdata3          (readdata3), 
   .readdata30         (readdata30), 
   .readdata31         (readdata31), 
   .readdata4          (readdata4), 
   .readdata5          (readdata5), 
   .readdata6          (readdata6), 
   .readdata7          (readdata7), 
   .readdata8          (readdata8), 
   .readdata9          (readdata9), 
   .rst                (rst), 
   .bus_rec_select     (bus_rec_select), 
   .canakari_entimeout (canakari_entimeout), 
   .cs_rec0            (cs_rec0), 
   .cs_rec1            (cs_rec1), 
   .cs_rec10           (cs_rec10), 
   .cs_rec11           (cs_rec11), 
   .cs_rec12           (cs_rec12), 
   .cs_rec13           (cs_rec13), 
   .cs_rec14           (cs_rec14), 
   .cs_rec15           (cs_rec15), 
   .cs_rec16           (cs_rec16), 
   .cs_rec17           (cs_rec17), 
   .cs_rec18           (cs_rec18), 
   .cs_rec19           (cs_rec19), 
   .cs_rec2            (cs_rec2), 
   .cs_rec20           (cs_rec20), 
   .cs_rec21           (cs_rec21), 
   .cs_rec22           (cs_rec22), 
   .cs_rec23           (cs_rec23), 
   .cs_rec24           (cs_rec24), 
   .cs_rec25           (cs_rec25), 
   .cs_rec26           (cs_rec26), 
   .cs_rec27           (cs_rec27), 
   .cs_rec28           (cs_rec28), 
   .cs_rec29           (cs_rec29), 
   .cs_rec3            (cs_rec3), 
   .cs_rec30           (cs_rec30), 
   .cs_rec31           (cs_rec31), 
   .cs_rec4            (cs_rec4), 
   .cs_rec5            (cs_rec5), 
   .cs_rec6            (cs_rec6), 
   .cs_rec7            (cs_rec7), 
   .cs_rec8            (cs_rec8), 
   .cs_rec9            (cs_rec9), 
   .irq_can_rec        (irq_can_rec), 
   .read_n0            (read_n0), 
   .read_n1            (read_n1), 
   .read_n10           (read_n10), 
   .read_n11           (read_n11), 
   .read_n12           (read_n12), 
   .read_n13           (read_n13), 
   .read_n14           (read_n14), 
   .read_n15           (read_n15), 
   .read_n16           (read_n16), 
   .read_n17           (read_n17), 
   .read_n18           (read_n18), 
   .read_n19           (read_n19), 
   .read_n2            (read_n2), 
   .read_n20           (read_n20), 
   .read_n21           (read_n21), 
   .read_n22           (read_n22), 
   .read_n23           (read_n23), 
   .read_n24           (read_n24), 
   .read_n25           (read_n25), 
   .read_n26           (read_n26), 
   .read_n27           (read_n27), 
   .read_n28           (read_n28), 
   .read_n29           (read_n29), 
   .read_n3            (read_n3), 
   .read_n30           (read_n30), 
   .read_n31           (read_n31), 
   .read_n4            (read_n4), 
   .read_n5            (read_n5), 
   .read_n6            (read_n6), 
   .read_n7            (read_n7), 
   .read_n8            (read_n8), 
   .read_n9            (read_n9), 
   .readdata           (readdata)
); 

node_tra_demux node_tra_demux0( 
   .bus_tra_select (bus_tra_select), 
   .enable_cs_sig  (enable_cs_sig), 
   .cs_tra0        (cs_tra0), 
   .cs_tra1        (cs_tra1), 
   .cs_tra10       (cs_tra10), 
   .cs_tra11       (cs_tra11), 
   .cs_tra12       (cs_tra12), 
   .cs_tra13       (cs_tra13), 
   .cs_tra14       (cs_tra14), 
   .cs_tra15       (cs_tra15), 
   .cs_tra16       (cs_tra16), 
   .cs_tra17       (cs_tra17), 
   .cs_tra18       (cs_tra18), 
   .cs_tra19       (cs_tra19), 
   .cs_tra2        (cs_tra2), 
   .cs_tra20       (cs_tra20), 
   .cs_tra21       (cs_tra21), 
   .cs_tra22       (cs_tra22), 
   .cs_tra23       (cs_tra23), 
   .cs_tra24       (cs_tra24), 
   .cs_tra25       (cs_tra25), 
   .cs_tra26       (cs_tra26), 
   .cs_tra27       (cs_tra27), 
   .cs_tra28       (cs_tra28), 
   .cs_tra29       (cs_tra29), 
   .cs_tra3        (cs_tra3), 
   .cs_tra30       (cs_tra30), 
   .cs_tra31       (cs_tra31), 
   .cs_tra4        (cs_tra4), 
   .cs_tra5        (cs_tra5), 
   .cs_tra6        (cs_tra6), 
   .cs_tra7        (cs_tra7), 
   .cs_tra8        (cs_tra8), 
   .cs_tra9        (cs_tra9), 
   .write_n_sig    (write_n_sig), 
   .writedata      (writedata), 
   .irq_can_tra    (irq_can_tra), 
   .write_n0       (write_n0), 
   .write_n1       (write_n1), 
   .write_n2       (write_n2), 
   .write_n3       (write_n3), 
   .write_n4       (write_n4), 
   .write_n5       (write_n5), 
   .write_n6       (write_n6), 
   .write_n7       (write_n7), 
   .writedata0     (writedata0), 
   .writedata1     (writedata1), 
   .writedata2     (writedata2), 
   .writedata3     (writedata3), 
   .writedata4     (writedata4), 
   .writedata5     (writedata5), 
   .writedata6     (writedata6), 
   .writedata7     (writedata7), 
   .irqsuctra0     (irqsuctra0), 
   .write_n8       (write_n8), 
   .write_n9       (write_n9), 
   .write_n10      (write_n10), 
   .write_n11      (write_n11), 
   .write_n12      (write_n12), 
   .write_n13      (write_n13), 
   .write_n14      (write_n14), 
   .write_n15      (write_n15), 
   .write_n16      (write_n16), 
   .write_n17      (write_n17), 
   .write_n18      (write_n18), 
   .write_n19      (write_n19), 
   .write_n20      (write_n20), 
   .write_n21      (write_n21), 
   .write_n22      (write_n22), 
   .write_n23      (write_n23), 
   .write_n24      (write_n24), 
   .write_n25      (write_n25), 
   .write_n26      (write_n26), 
   .write_n27      (write_n27), 
   .write_n28      (write_n28), 
   .write_n29      (write_n29), 
   .write_n30      (write_n30), 
   .write_n31      (write_n31), 
   .writedata8     (writedata8), 
   .writedata9     (writedata9), 
   .writedata10    (writedata10), 
   .writedata11    (writedata11), 
   .writedata12    (writedata12), 
   .writedata13    (writedata13), 
   .writedata14    (writedata14), 
   .writedata15    (writedata15), 
   .writedata16    (writedata16), 
   .irqsuctra1     (irqsuctra1), 
   .writedata17    (writedata17), 
   .irqsuctra2     (irqsuctra2), 
   .irqsuctra3     (irqsuctra3), 
   .writedata18    (writedata18), 
   .irqsuctra4     (irqsuctra4), 
   .writedata19    (writedata19), 
   .irqsuctra5     (irqsuctra5), 
   .writedata20    (writedata20), 
   .irqsuctra6     (irqsuctra6), 
   .writedata21    (writedata21), 
   .writedata22    (writedata22), 
   .irqsuctra7     (irqsuctra7), 
   .irqsuctra8     (irqsuctra8), 
   .writedata23    (writedata23), 
   .irqsuctra9     (irqsuctra9), 
   .writedata24    (writedata24), 
   .irqsuctra10    (irqsuctra10), 
   .writedata25    (writedata25), 
   .irqsuctra11    (irqsuctra11), 
   .writedata26    (writedata26), 
   .irqsuctra12    (irqsuctra12), 
   .writedata27    (writedata27), 
   .writedata28    (writedata28), 
   .irqsuctra13    (irqsuctra13), 
   .writedata29    (writedata29), 
   .irqsuctra14    (irqsuctra14), 
   .writedata30    (writedata30), 
   .irqsuctra15    (irqsuctra15), 
   .writedata31    (writedata31), 
   .irqsuctra17    (irqsuctra17), 
   .irqsuctra18    (irqsuctra18), 
   .irqsuctra19    (irqsuctra19), 
   .irqsuctra20    (irqsuctra20), 
   .irqsuctra21    (irqsuctra21), 
   .irqsuctra16    (irqsuctra16), 
   .irqsuctra22    (irqsuctra22), 
   .irqsuctra23    (irqsuctra23), 
   .irqsuctra24    (irqsuctra24), 
   .irqsuctra25    (irqsuctra25), 
   .irqsuctra26    (irqsuctra26), 
   .irqsuctra27    (irqsuctra27), 
   .irqsuctra28    (irqsuctra28), 
   .irqsuctra29    (irqsuctra29), 
   .irqsuctra30    (irqsuctra30), 
   .irqsuctra31    (irqsuctra31)
); 

// HDL Embedded Text Block 1 cs_signal
// Canakari blocks  0-7                                       
assign cs0 = cs_rec0 | cs_tra0;
assign cs1 = cs_rec1 | cs_tra1;
assign cs2 = cs_rec2 | cs_tra2;
assign cs3 = cs_rec3 | cs_tra3;
assign cs4 = cs_rec4 | cs_tra4;
assign cs5 = cs_rec5 | cs_tra5;
assign cs6 = cs_rec6 | cs_tra6;
assign cs7 = cs_rec7 | cs_tra7;

// Canakari blocks  8-15                                       
assign cs8  = cs_rec8  | cs_tra8;
assign cs9  = cs_rec9  | cs_tra9;
assign cs10 = cs_rec10 | cs_tra10;
assign cs11 = cs_rec11 | cs_tra11;
assign cs12 = cs_rec12 | cs_tra12;
assign cs13 = cs_rec13 | cs_tra13;
assign cs14 = cs_rec14 | cs_tra14;
assign cs15 = cs_rec15 | cs_tra15;

// Canakari blocks  16-23                                       
assign cs16 = cs_rec16 | cs_tra16;
assign cs17 = cs_rec17 | cs_tra17;
assign cs18 = cs_rec18 | cs_tra18;
assign cs19 = cs_rec19 | cs_tra19;
assign cs20 = cs_rec20 | cs_tra20;
assign cs21 = cs_rec21 | cs_tra21;
assign cs22 = cs_rec22 | cs_tra22;
assign cs23 = cs_rec23 | cs_tra23;

// Canakari blocks  24-31                                       
assign cs24 = cs_rec24 | cs_tra24;
assign cs25 = cs_rec25 | cs_tra25;
assign cs26 = cs_rec26 | cs_tra26;
assign cs27 = cs_rec27 | cs_tra27;
assign cs28 = cs_rec28 | cs_tra28;
assign cs29 = cs_rec29 | cs_tra29;
assign cs30 = cs_rec30 | cs_tra30;
assign cs31 = cs_rec31 | cs_tra31;

assign ireqsucrec = irqsucrec0 |irqsucrec1 |irqsucrec2 |irqsucrec3 |irqsucrec4 |irqsucrec5 |irqsucrec6 |irqsucrec7 |
                    irqsucrec8 |irqsucrec9 |irqsucrec10|irqsucrec11|irqsucrec12|irqsucrec13|irqsucrec14|irqsucrec15|
                    irqsucrec16|irqsucrec17|irqsucrec18|irqsucrec19|irqsucrec20|irqsucrec21|irqsucrec22|irqsucrec23|
                    irqsucrec24|irqsucrec25|irqsucrec26|irqsucrec27|irqsucrec28|irqsucrec29|irqsucrec30|irqsucrec31;











endmodule // canakari_top

