//
// Module mopshub_lib.elink_to_fifo.struct
//
// Created:
//          by - dcs.dcs (chipdev2.physik.uni-wuppertal.de)
//          at - 09:21:15 11/03/21
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//

`resetall
`timescale 1ns/10ps
module elink_to_fifo #(
   // synopsys template
   parameter generate_mopshub = 0
)
( 
   // Port Declarations
   output  wire           fifo_empty, 
   input   wire           fifo_flush, 
   output  wire           fifo_full, 
   output  wire    [9:0]  fifo_dout, 
   input   wire           clk, 
   input   wire           reverse_rx, 
   input   wire           fifo_rd_en, 
   output  wire    [9:0]  dec10b_Out_dbg, 
   input   wire    [1:0]  data_2bit_in, 
   output  wire           dec10b_rdy_dbg, 
   input   wire           rst, 
   input   wire           enc_stream
);


// Internal Declarations


// Local declarations

// Internal signal declarations


// Instances 
elink_proc_in #(generate_mopshub) elink_proc_in0( 
   .EDATA_IN           (data_2bit_in), 
   .clk                (clk), 
   .enc_stream         (enc_stream), 
   .reverse_stream_10b (reverse_rx), 
   .rst                (rst), 
   .ISK                (dec10b_Out_dbg[9:8]), 
   .data_out           (dec10b_Out_dbg[7:0]), 
   .data_rdy           (dec10b_rdy_dbg)
); 

fifo_RXelink_wrap fifo_RXelink_wrap0( 
   .clk        (clk), 
   .din        (dec10b_Out_dbg), 
   .din_rdy    (dec10b_rdy_dbg), 
   .flush_fifo (fifo_flush), 
   .rd_en_fifo (fifo_rd_en), 
   .rst        (rst), 
   .dout_fifo  (fifo_dout), 
   .empty_fifo (fifo_empty), 
   .full_fifo  (fifo_full)
); 


endmodule // elink_to_fifo

