//
// Module mopshub_lib.mopshubCore.struct
//
// Created:
//          by - dcs.dcs (chipdev2.physik.uni-wuppertal.de)
//          at - 16:18:15 06/17/21
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//

`resetall
`timescale 1ns/10ps
module mopshubCore( 
   // Port Declarations
   output  wire    [4:0]   addr_can, 
   input   wire    [4:0]   bus_rec_select, 
   output  wire    [4:0]   bus_tra_select, 
   input   wire            clock, 
   input   wire            irq_can_rec, 
   input   wire    [15:0]  read_can, 
   output  wire            read_sig_can_n, 
   input   wire            reset, 
   output  wire    [15:0]  write_can, 
   output  wire            write_sig_can_n, 
   input   wire            irq_can_tra, 
   output  wire            enable_cs, 
   output  wire    [75:0]  data_rec_uplink, 
   input   wire    [75:0]  data_tra_uplink, 
   output  wire            choose_bus_end, 
   input   wire            end_read_elink, 
   input   wire            end_write_elink, 
   input   wire            irq_elink, 
   output  wire            start_read_elink, 
   output  wire            start_write_elink, 
   output  wire            send_mes_elink, 
   output  wire            sign_on_sig
);


// Internal Declarations


// Local declarations

// Internal signal declarations


// Instances 
bridgeController mopshub_bridge( 
   .can_rec_select    (bus_rec_select), 
   .clk               (clock), 
   .data_tra_uplink   (data_tra_uplink), 
   .end_read_elink    (end_read_elink), 
   .end_write_elink   (end_write_elink), 
   .endwait           (), 
   .irq_can_rec       (irq_can_rec), 
   .irq_can_tra       (irq_can_tra), 
   .irq_elink         (irq_elink), 
   .read_can          (read_can), 
   .rst               (reset), 
   .addr_can          (addr_can), 
   .can_tra_select    (bus_tra_select), 
   .data_rec_uplink   (data_rec_uplink), 
   .enable_cs         (enable_cs), 
   .end_can_proc      (choose_bus_end), 
   .read_sig_can_n    (read_sig_can_n), 
   .send_mes_elink    (send_mes_elink), 
   .sign_on_sig       (sign_on_sig), 
   .start_read_elink  (start_read_elink), 
   .start_write_elink (start_write_elink), 
   .write_can         (write_can), 
   .write_sig_can_n   (write_sig_can_n)
); 


endmodule // mopshubCore

