//
// Module mopshub_lib.mopshub_top.struct
//
// Created:
//          by - dcs.dcs (chipdev2.physik.uni-wuppertal.de)
//          at - 18:29:48 09/03/21
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//

`resetall
`timescale 1ns/10ps
module mopshub_top #(
   // synopsys template
   parameter max_cnt_size = 5,
   parameter n_buses      = 5'b11111
)
( 
   // Port Declarations
   input   wire           clk, 
   input   wire           en_osc_trim, 
   input   wire           end_cnt_dbg, 
   input   wire           rst, 
   input   wire           rx0, 
   input   wire           rx1, 
   input   wire           rx2, 
   input   wire           rx3, 
   input   wire           rx4, 
   input   wire           rx5, 
   input   wire           rx6, 
   input   wire           rx7, 
   input   wire           rx_elink1bit, 
   input   wire    [1:0]  rx_elink2bit, 
   output  wire           end_init, 
   output  wire           end_trim_bus, 
   output  wire           rst_mops_dbg, 
   output  wire           sign_on_sig, 
   output  wire           start_init, 
   output  wire           start_trim_osc, 
   output  wire           tx0, 
   output  wire           tx1, 
   output  wire           tx2, 
   output  wire           tx3, 
   output  wire           tx4, 
   output  wire           tx5, 
   output  wire           tx6, 
   output  wire           tx7, 
   output  wire           tx_elink1bit, 
   output  wire    [1:0]  tx_elink2bit
);


// Internal Declarations


// Local declarations

// Internal signal declarations
wire         bitCLK;
wire         bitCLKx2;
wire         buffer_en;
wire  [4:0]  can_rec_select;
wire  [4:0]  can_tra_select;
wire  [75:0] data_rec_uplink;
wire  [75:0] data_tra_uplink;
wire         end_read_elink;
wire         end_write_elink;
wire         irq_can_ack;
wire         irq_elink_rec;
wire         irq_elink_tra;
wire         start_read_elink;
wire         start_write_link;


// Instances 
clock_divider #(28'd2)
clock_divider2( 
   .clock_in  (clk), 
   .clock_out (bitCLKx2)
); 

clock_divider #(28'd4)
clock_divider4( 
   .clock_in  (clk), 
   .clock_out (bitCLK)
); 

elink_core elink_core0( 
   .rx_fifo_full      (), 
   .rx_elink1bit      (rx_elink1bit), 
   .bitCLK            (bitCLK), 
   .bitCLKx2          (bitCLKx2), 
   .clk               (clk), 
   .rst               (rst), 
   .data_rec_uplink   (data_rec_uplink), 
   .start_write_elink (start_write_link), 
   .rx_elink2bit      (rx_elink2bit), 
   .tx_efifo_full     (), 
   .tx_elink1bit      (tx_elink1bit), 
   .tx_elink2bit      (tx_elink2bit), 
   .irq_elink_rec     (irq_elink_rec), 
   .irq_elink_tra     (irq_elink_tra), 
   .data_tra_out      (data_tra_uplink), 
   .end_write_elink   (end_write_elink), 
   .start_read_elink  (start_read_elink), 
   .end_read_elink    (end_read_elink), 
   .buffer_tra_en     (buffer_en)
); 

mopshub_core #(max_cnt_size,n_buses) mopshub_core0( 
   .buffer_en         (buffer_en), 
   .can_rec_select    (can_rec_select), 
   .can_tra_select    (can_tra_select), 
   .clk               (clk), 
   .data_tra_uplink   (data_tra_uplink), 
   .en_osc_trim       (en_osc_trim), 
   .end_cnt_dbg       (end_cnt_dbg), 
   .end_read_elink    (end_read_elink), 
   .end_write_elink   (end_write_elink), 
   .irq_elink_tra     (irq_elink_tra), 
   .rst               (rst), 
   .rx0               (rx0), 
   .rx1               (rx1), 
   .rx2               (rx2), 
   .rx3               (rx3), 
   .rx4               (rx4), 
   .rx5               (rx5), 
   .rx6               (rx6), 
   .rx7               (rx7), 
   .data_rec_uplink   (data_rec_uplink), 
   .end_init          (end_init), 
   .end_trim_bus      (end_trim_bus), 
   .irq_can_ack       (irq_can_ack), 
   .rst_mops_dbg      (rst_mops_dbg), 
   .sign_on_sig       (sign_on_sig), 
   .start_init        (start_init), 
   .start_read_elink  (start_read_elink), 
   .start_trim_osc    (start_trim_osc), 
   .start_write_elink (start_write_link), 
   .tx0               (tx0), 
   .tx1               (tx1), 
   .tx2               (tx2), 
   .tx3               (tx3), 
   .tx4               (tx4), 
   .tx5               (tx5), 
   .tx6               (tx6), 
   .tx7               (tx7)
); 


endmodule // mopshub_top

