//
// Module mopshub_lib.node_tra_demux_16.struct
//
// Created:
//          by - dcs.dcs (chipdev2.physik.uni-wuppertal.de)
//          at - 14:44:10 10/11/22
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//

`resetall
`timescale 1ns/10ps
module node_tra_demux_16( 
   // Port Declarations
   input   wire    [4:0]   bus_tra_select, 
   input   wire            clk, 
   input   wire            enable_cs_sig, 
   input   wire            irqsuctra0, 
   input   wire            irqsuctra1, 
   input   wire            irqsuctra10, 
   input   wire            irqsuctra11, 
   input   wire            irqsuctra12, 
   input   wire            irqsuctra13, 
   input   wire            irqsuctra14, 
   input   wire            irqsuctra15, 
   input   wire            irqsuctra2, 
   input   wire            irqsuctra3, 
   input   wire            irqsuctra4, 
   input   wire            irqsuctra5, 
   input   wire            irqsuctra6, 
   input   wire            irqsuctra7, 
   input   wire            irqsuctra8, 
   input   wire            irqsuctra9, 
   input   wire            rst, 
   input   wire            write_n_sig, 
   input   wire    [15:0]  writedata, 
   output  wire            cs_tra0, 
   output  wire            cs_tra1, 
   output  wire            cs_tra10, 
   output  wire            cs_tra11, 
   output  wire            cs_tra12, 
   output  wire            cs_tra13, 
   output  wire            cs_tra14, 
   output  wire            cs_tra15, 
   output  wire            cs_tra2, 
   output  wire            cs_tra3, 
   output  wire            cs_tra4, 
   output  wire            cs_tra5, 
   output  wire            cs_tra6, 
   output  wire            cs_tra7, 
   output  wire            cs_tra8, 
   output  wire            cs_tra9, 
   output  wire            irq_can_tra, 
   output  wire            write_n0, 
   output  wire            write_n1, 
   output  wire            write_n10, 
   output  wire            write_n11, 
   output  wire            write_n12, 
   output  wire            write_n13, 
   output  wire            write_n14, 
   output  wire            write_n15, 
   output  wire            write_n2, 
   output  wire            write_n3, 
   output  wire            write_n4, 
   output  wire            write_n5, 
   output  wire            write_n6, 
   output  wire            write_n7, 
   output  wire            write_n8, 
   output  wire            write_n9, 
   output  wire    [15:0]  writedata0, 
   output  wire    [15:0]  writedata1, 
   output  wire    [15:0]  writedata10, 
   output  wire    [15:0]  writedata11, 
   output  wire    [15:0]  writedata12, 
   output  wire    [15:0]  writedata13, 
   output  wire    [15:0]  writedata14, 
   output  wire    [15:0]  writedata15, 
   output  wire    [15:0]  writedata2, 
   output  wire    [15:0]  writedata3, 
   output  wire    [15:0]  writedata4, 
   output  wire    [15:0]  writedata5, 
   output  wire    [15:0]  writedata6, 
   output  wire    [15:0]  writedata7, 
   output  wire    [15:0]  writedata8, 
   output  wire    [15:0]  writedata9
);


// Internal Declarations


// Local declarations

// Internal signal declarations
wire   cs_signal_write;
reg    def_value_0;
reg    def_value_1;


// Instances 
demux1_16_16bit demux1_16_16bit_writedata( 
   .sel       (bus_tra_select), 
   .input_bus (writedata), 
   .output0   (writedata0), 
   .output1   (writedata1), 
   .output2   (writedata2), 
   .output3   (writedata3), 
   .output4   (writedata4), 
   .output5   (writedata5), 
   .output6   (writedata6), 
   .output7   (writedata7), 
   .output8   (writedata8), 
   .output9   (writedata9), 
   .output10  (writedata10), 
   .output11  (writedata11), 
   .output12  (writedata12), 
   .output13  (writedata13), 
   .output14  (writedata14), 
   .output15  (writedata15)
); 

demux1_16_1bit demux1_16_1bit_cs( 
   .def_value  (def_value_0), 
   .sel        (bus_tra_select), 
   .input_port (cs_signal_write), 
   .output0    (cs_tra0), 
   .output1    (cs_tra1), 
   .output2    (cs_tra2), 
   .output3    (cs_tra3), 
   .output4    (cs_tra4), 
   .output5    (cs_tra5), 
   .output6    (cs_tra6), 
   .output7    (cs_tra7), 
   .output8    (cs_tra8), 
   .output9    (cs_tra9), 
   .output10   (cs_tra10), 
   .output11   (cs_tra11), 
   .output12   (cs_tra12), 
   .output13   (cs_tra13), 
   .output14   (cs_tra14), 
   .output15   (cs_tra15)
); 

demux1_16_1bit demux1_16_1bit_write( 
   .def_value  (def_value_1), 
   .sel        (bus_tra_select), 
   .input_port (write_n_sig), 
   .output0    (write_n0), 
   .output1    (write_n1), 
   .output2    (write_n2), 
   .output3    (write_n3), 
   .output4    (write_n4), 
   .output5    (write_n5), 
   .output6    (write_n6), 
   .output7    (write_n7), 
   .output8    (write_n8), 
   .output9    (write_n9), 
   .output10   (write_n10), 
   .output11   (write_n11), 
   .output12   (write_n12), 
   .output13   (write_n13), 
   .output14   (write_n14), 
   .output15   (write_n15)
); 

mux16_1_1bit mux16_1_1bit_irqtra( 
   .clk         (clk), 
   .rst         (rst), 
   .sel         (bus_tra_select), 
   .def_value   (def_value_0), 
   .output_port (irq_can_tra), 
   .input0      (irqsuctra0), 
   .input1      (irqsuctra1), 
   .input2      (irqsuctra2), 
   .input3      (irqsuctra3), 
   .input4      (irqsuctra4), 
   .input5      (irqsuctra5), 
   .input6      (irqsuctra6), 
   .input7      (irqsuctra7), 
   .input8      (irqsuctra8), 
   .input9      (irqsuctra9), 
   .input10     (irqsuctra10), 
   .input11     (irqsuctra11), 
   .input12     (irqsuctra12), 
   .input13     (irqsuctra13), 
   .input14     (irqsuctra14), 
   .input15     (irqsuctra15)
); 

// HDL Embedded Text Block 3 cs_signal2
// eb1 1                                        
assign cs_signal_write = enable_cs_sig && !write_n_sig;




// HDL Embedded Text Block 4 assign_wire1
// eb1 1  
initial                                      
begin
  def_value_1 = 1'b1;
  def_value_0 = 1'b0;
end  



endmodule // node_tra_demux_16

