//
// Module mopshub_lib.tb_fifoTXelink_wrap.struct
//
// Created:
//          by - dcs.dcs (chipdev2.physik.uni-wuppertal.de)
//          at - 18:09:44 03/08/21
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.4 (Build 4)
//

`resetall
`timescale 1ns/10ps
module tb_fifoTXelink_wrap; 
  parameter DATA_WIDTH           =18;
  parameter Byte_OUT_WIDTH       = 10;
  // Port Declarations
  reg                            rst;
  
  wire    [Byte_OUT_WIDTH-1:0]  dout; 
  wire                          doutRdy;

  
  wire  [DATA_WIDTH-1:0]       dout18bit; 
  wire  [Byte_OUT_WIDTH-1:0]       byte0;
  wire  [Byte_OUT_WIDTH-1:0]       byte1;
  wire  [1:0]                      word16_code;
  wire  byte_cnt;
  
  reg                            rd_en;
  reg                            rd_clk;
  reg                            wr_clk;
  
  
  
  // Data Generator Signals
  reg                            gen_clk;
  wire done;               // dbg
  wire [DATA_WIDTH-1:0] GEN_EDATA_10bit;
  wire rd_en_s;
  wire wen; //wr_en signal

  //wire                          prog_full; 
  //wire                          full; 
  //wire                          empty;
    
  assign dout18bit=TXelink_wrap.dout18bit;
  assign byte_cnt  = TXelink_wrap.byte_cnt;
  assign word16_code = TXelink_wrap.word16_code;
  assign byte0 = TXelink_wrap.byte0;
  assign byte1 = TXelink_wrap.byte1;
  assign rd_en_s = TXelink_wrap.rd_en_s;  
  // Instances 
  fifoTXelink_wrap TXelink_wrap( 
  .din       (GEN_EDATA_10bit), 
  .fifoFLUSH (rst), 
  .rd_clk    (rd_clk), 
  .rd_en     (rd_en), 
  .rst       (rst), 
  .wr_clk    (wr_clk), 
  .wr_en     (wen), 
  .dout      (dout), 
  .doutRdy   (doutRdy), 
  .empty     (), 
  .full      (), 
  .prog_full ()
  ); 
  
  data_generator DataGEN(
  .clk_usr(gen_clk),
  .enable(~rst),
  .loop_en(~rst),
  .done(done),
  .tx_fifo_pfull(0'b0),
  .dout(GEN_EDATA_10bit),
  .wen(wen)
  );  
  
  //Wr_clk to FIFO //40 Mb
  initial begin 
    wr_clk=0; 
    forever #1 wr_clk=~wr_clk; 
  end 

  //Generator clk // 80 Mb
  initial begin 
    gen_clk=0; 
    forever #3 gen_clk=~gen_clk; 
  end

  // rd_clk from FIFO //160 Mb
  initial begin 
    rd_clk=0; 
    forever #0.5 rd_clk=~rd_clk; 
  end
      
  
  // HDL Embedded Text Block 3 Initialize
  // Initialize 3                                        
  initial 
  begin 
    rd_en= 0;
    //rst module
    rst = 1;
    #2 rst =0;
    //data Generator
    rd_en=1;
  end

endmodule